"""
Gera os 60 JSONs nano banana para video-013-segundo-selo.
Cada JSON segue o schema do Q02.json template.
"""
import json
from pathlib import Path

OUT = Path("C:/Users/Leandro/Downloads/agencia/canais/sinais-do-fim/videos/video-013-segundo-selo/6-prompts-imagem")
OUT.mkdir(parents=True, exist_ok=True)

STYLE_REF = {
    "primary_image_url": "canais/sinais-do-fim/_config/style_refs/sinais_dark.png",
    "weight": 0.85,
    "transfer_targets": ["color_palette", "lighting", "texture", "atmosphere", "film_grain"],
    "textual_description": "dark cinematic chiaroscuro, Caravaggio-inspired, foreground in rich warm tones (crimson, amber, gold) with background in desaturated black-and-white, film grain, candlelight, floating orange embers"
}

VIDEO = "video-013-segundo-selo"
CANAL = "sinais-do-fim"

# (quadro, parte, ato, scene_title, narrative_beat, shot_type, camera_angle, focal_mm, aperture, dof,
#  primary, focal_point, secondary, props,
#  location, time_of_day, atmosphere,
#  rule, foreground, midground, background,
#  key, fill, rim, light_mood, shadow,
#  film_stock, post, texture,
#  emotion, tension,
#  sym_primary, sym_secondary,
#  in_scene_text (dict or None),
#  use_pro (bool))

FRAMES = [
    # ---------- PARTE 1 (Q01-Q12) ----------
    ("Q01", 1, "Gancho", "Vazio pre-apocaliptico", "Tela preta com brasa unica e rastro diagonal carmesim",
     "wide", "straight-on", 35, "f/4.0", "deep",
     "absolute black frame pierced only by a single orange ember drifting in lower right and a faint crimson diagonal streak above, like a missile trail without the missile itself",
     "the lone orange ember dissolving mid-fall",
     "The frame is 98 percent black, textured with subtle film grain; the ember emits soft amber glow dissipating into darkness",
     ["single floating orange ember", "faint crimson diagonal streak", "starless night void"],
     "infinite black void representing pre-dawn February 2026", "pre-dawn before missile impact", "ominous pre-apocalyptic silence",
     "negative space rule, centered minimalism",
     "single floating ember in rich amber",
     "pure black void",
     "imperceptible hint of starless night sky",
     "no visible key light except ember self-glow", "none", "faint amber rim on ember particle", "near-total darkness", "absolute crushed blacks",
     "Kodak Double-X black-and-white pushed", "heavy halation on ember, deep black crush, 35mm grain", "heavy film grain, minimal particulate",
     "ominous anticipation, suspended dread", "high",
     "dark before revelation, void awaiting the apocalyptic horseman",
     "a single ember as herald of what is to come",
     None, False),

    ("Q02", 1, "Gancho", "Misseis cruzam o ceu do Ira", "Tres rastros de missil diagonal sobre cidade persa",
     "wide", "low-angle", 24, "f/2.8", "deep",
     "three glowing missile trails slicing diagonally across a night sky above a sleeping Middle Eastern city skyline",
     "the three crimson-gold trails crossing at the apex of the frame",
     "Silhouettes of minarets and domes in deep black-and-white below, completely asleep; the trails leave phosphorescent afterglow",
     ["three diagonal missile trails in crimson-gold plasma", "ancient tile rooftop foreground", "silhouetted minarets and cupolas", "drifting embers"],
     "night sky above Tehran rooftops", "3 am madrugada", "violent beauty of distant war",
     "diagonal leading lines, rule of thirds",
     "antique ochre rooftop tiles in warm tones, glowing faintly",
     "three missile trails cutting crimson-gold diagonals",
     "silhouetted black-and-white Persian city asleep, minarets against starless sky",
     "harsh directional glow from missile trails", "faint amber bounce off rooftop tiles", "crimson rim-light on skyline edges", "violent nocturnal", "sharp diagonal shadows cast by trails",
     "Kodak Portra 800 pushed two stops", "halation on trails, crushed blacks, amber highlights, anamorphic flares", "35mm film grain, ash particulate",
     "violent distant beauty, helpless awe", "high",
     "missiles as the great sword of Apocalypse 6 descending",
     "an ancient city unaware of its judgment",
     None, False),

    ("Q03", 1, "Gancho", "Palacio atingido", "Colunas desabando em labaredas carmesim",
     "medium", "frontal", 40, "f/2.8", "medium",
     "a Persian palace of white marble struck by incoming missiles, columns partially collapsing in crimson-amber flames with black smoke rising",
     "a collapsing Persian dome fragmented in mid-explosion",
     "No human figures visible; shattered tiles and floating gold debris in mid-air, orange licks of flame illuminating ornate architectural details",
     ["marble columns mid-collapse", "crimson-amber flames", "gold debris suspended in air", "black smoke plumes", "ornate Persian tilework"],
     "exterior of Aiatola palace in Tehran", "pre-dawn under missile impact", "sacred destruction",
     "rule of thirds with collapsing central mass",
     "marble columns and flames in saturated crimson and ochre",
     "collapsing dome fragmented, gold debris mid-air",
     "desaturated black-and-white skyline of Persian city with smoke plumes",
     "explosive flame flash from left-foreground", "amber bounce from burning marble", "gold rim-light on falling debris", "apocalyptic destruction", "hard-edged fire shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber flame highlights, anamorphic flare", "35mm grain, flame particulate, ash",
     "sacred destruction, patriarchal fall", "high",
     "destruction of ancient power structures",
     "columns as collapsing pillars of an old order",
     None, False),

    ("Q04", 1, "Gancho", "Khamenei morre", "Silhueta em perfil com lagrima dourada",
     "close", "profile-lateral", 85, "f/2.0", "razor-thin",
     "profile silhouette of an ancient turbaned patriarch, long white beard visible, face entirely in deep shadow, backlit by crimson flames",
     "a single golden tear tracking down the shadowed cheek",
     "No facial features identifiable; only the white beard catches light; background faint Persian symbolism dissolved in gray",
     ["black turban profile", "long silvered white beard", "single luminous golden tear", "crimson flame backlight"],
     "inside collapsing palace chamber", "moment of death at dawn", "mourning of a patriarch",
     "profile silhouette, negative space left",
     "beard in warm silver highlights and crimson backlit rim",
     "profile silhouette in deep shadow",
     "crimson fire halo behind, desaturated Persian motifs",
     "crimson fire backlight", "no fill (silhouette)", "gold rim-light on beard and tear", "tragic silhouette", "absolute silhouette shadow",
     "Kodak Portra 800 pushed", "halation, crushed blacks, golden highlights", "35mm grain, dust particulate",
     "tragic end of dynasty, patriarchal death", "high",
     "death of a leader as prophetic marker",
     "the tear as lament for an unrepentant world",
     None, False),

    ("Q05", 1, "Gancho", "Mundo assiste CNN", "Smartphone ilumina face na mesa de jantar",
     "overhead", "top-down 75 deg", 35, "f/2.8", "medium",
     "an overhead view of a modern dining table in monochrome, with a single smartphone glowing amber-crimson from below lighting a man's shadowed face watching news",
     "the smartphone screen reflecting distant flames and scrolling headlines",
     "The face is barely visible, cheek and jaw caught in screen glow; a cold coffee cup and bread crumbs sit beside the phone",
     ["glowing smartphone screen in warm tones", "shadowed male face", "cold coffee cup", "bread crumbs on table"],
     "middle-class dining room at night", "late evening domestic scene", "apathy and alienation",
     "overhead symmetry, phone as center light source",
     "smartphone screen and illuminated face in rich warm amber-crimson",
     "black wood dining table with subtle texture",
     "totally desaturated black-and-white surroundings, vague kitchen shapes",
     "phone screen as only light source, warm and harsh", "minimal amber bounce on cheek", "faint gold rim on jawline", "claustrophobic intimacy", "deep enveloping shadows",
     "Kodak Vision3 500T", "crushed blacks, amber highlights, naturalistic grading", "35mm grain, dust in air",
     "dull alienated awareness, cosmic apathy", "medium",
     "modern world consuming catastrophe as content",
     "the smartphone as a one-way window into prophecy fulfilled",
     None, False),

    ("Q06", 1, "Gancho", "Livro de dois mil anos", "Codice biblico medieval aberto",
     "close", "straight-on macro", 100, "f/2.8", "razor-thin",
     "a medieval biblical codex open on a heavy wooden lectern, thick sepia-gold parchment pages, gothic calligraphy in crimson ink",
     "an illuminated capital letter worked in gold leaf at the start of Apocalypse 6",
     "A single beeswax candle burns beside the book casting warm lateral light; nothing modern visible",
     ["illuminated gold capital letter", "crimson gothic calligraphy", "beeswax candle flame", "thick sepia parchment"],
     "ruined monastic library at night", "candlelit midnight study", "reverent revelation",
     "rule of thirds on illuminated letter",
     "parchment and candlelight in saturated sepia-gold-crimson",
     "wooden lectern texture visible",
     "desaturated black-and-white ruined library shelves in background",
     "warm candlelight from right", "faint amber bounce off parchment", "gold rim on illuminated letter", "sacred study", "soft deep Caravaggio shadows",
     "Kodak Portra 800", "halation, warm highlights, crushed blacks, Caravaggio grading", "heavy 35mm grain, parchment fiber texture",
     "reverent ancient revelation", "medium-high",
     "the prophetic word preserved across two millennia",
     "gold illumination as divine authorship",
     None, False),

    ("Q07", 1, "Gancho", "O cavalo vermelho", "Cavaleiro sobre cavalo cor-de-fogo",
     "wide", "low-angle", 28, "f/2.8", "deep",
     "a massive medieval war horse with crimson fire-colored coat, golden glowing eyes, nostrils venting dark smoke, carrying a black-armored silhouetted rider holding a broad sword",
     "the horse's burning crimson coat and molten gold eyes",
     "Mane made of living sparks, hooves strike earth creating ember bursts, rider faceless inside black helmet",
     ["crimson fire-colored horse coat", "golden molten eyes", "black-armored rider silhouette", "broadsword raised", "ember bursts from hooves"],
     "ancient battlefield plain at dusk", "twilight of war", "prophetic vision",
     "low-angle hero shot, rule of thirds",
     "horse and rider in vivid crimson, gold, blackened steel",
     "cracked battlefield earth with scattered embers",
     "desaturated black-and-white battlefield with faded banners",
     "harsh dusk glow from right illuminating coat", "amber bounce from burning hooves", "gold rim on armor and eyes", "apocalyptic majesty", "hard-edged dramatic shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber highlights, anamorphic lens flares", "heavy 35mm grain, fire and ash particles",
     "overwhelming dread, divine judgment", "high",
     "the second horseman of Apocalypse 6:4 riding out",
     "the horse as pyrrhos, color of war-fire",
     None, False),

    ("Q08", 1, "Gancho", "A grande espada sobre pergaminho", "Espada de duas maos com runas em ouro",
     "overhead", "top-down 90", 50, "f/2.8", "medium",
     "a two-handed greatsword with aged steel blade and golden engraved runes resting across an open parchment bearing Apocalypse 6 verses",
     "the sword blade reflecting crimson and gold from candlelight",
     "The parchment shows sepia calligraphy and wax seal; candle burns nearby casting warm lateral light",
     ["two-handed medieval greatsword", "golden engraved runes", "sepia calligraphy parchment", "red wax seal", "beeswax candle"],
     "altar atop an ancient monastic chamber", "candlelit night of revelation", "sacred inevitability",
     "overhead symmetric composition",
     "sword and parchment in rich gold, crimson, steel tones",
     "dark wooden altar surface",
     "desaturated black-and-white chamber edges fading into shadow",
     "warm candlelight from lower-right", "gold bounce from blade", "crimson rim on wax seal", "ritual sacred", "deep Caravaggio shadows around edges",
     "Kodak Portra 800", "halation, crushed blacks, amber highlights, Caravaggio grading", "35mm grain, parchment and steel texture",
     "inevitability of prophecy", "high",
     "the machaira megale as divinely given weapon",
     "sword across scripture as covenant of judgment",
     None, False),

    ("Q09", 1, "Parte 1 Promessa", "Segundo selo rachado", "Selo de cera vermelha rachado com numeral II",
     "medium", "frontal", 50, "f/2.0", "medium",
     "a scroll with a deep red wax seal cracked down the middle on a gothic stone pedestal, with Roman numeral II branded into the wax",
     "the cracked II glowing crimson as if still hot",
     "Low smoke drifts near the base; the wax shows molten edges around the crack",
     ["red wax seal with Roman numeral II", "gothic stone pedestal", "rolled parchment", "low drifting smoke"],
     "chamber of the Lamb's throne", "moment just after seal is opened", "solemn confirmation",
     "centered symmetry",
     "wax seal and numeral in vivid crimson and molten gold",
     "carved stone pedestal",
     "desaturated black-and-white empty throne looming behind",
     "divine overhead beam", "crimson bounce from wax", "gold rim on pedestal edges", "confirmation solemn", "long shadows radiating outward",
     "Kodak Portra 800", "halation, crushed blacks, crimson highlights", "35mm grain, wax texture, stone particulate",
     "second seal broken as prophetic marker", "high",
     "the second seal opening in our own time",
     "numeral II as eternal chronology of judgment",
     {"enabled": True, "content": "II", "font_style": "heavy medieval branded Roman numeral", "medium": "burnt wax seal", "placement": "centered on the wax seal"},
     True),

    ("Q10", 1, "Parte 1 Promessa", "A grande espada moderna", "Missil balistico com runas em ouro",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "an extreme close-up of a ballistic missile styled as a giant sword-blade, steel body with crimson nose cone, Hebrew and Cyrillic engravings in gold along the flank",
     "the gold-engraved Hebrew and Cyrillic characters along the missile side",
     "The missile appears dormant in silo, subtle steam rising, no human presence",
     ["polished steel missile body", "crimson nose cone", "Hebrew and Cyrillic gold engravings", "rising steam vapor"],
     "subterranean missile silo", "night of activation", "technological terror",
     "rule of thirds on engravings",
     "missile and engravings in rich steel-crimson-gold",
     "steam and silo shadows",
     "desaturated black-and-white silo interior walls",
     "harsh overhead industrial light", "cold blue fill on steel", "gold rim on engravings", "technological chill", "hard reflections and deep blacks",
     "Kodak Vision3 500T", "halation, crushed blacks, metallic highlights", "35mm grain, cold steam, metallic texture",
     "dread of annihilation at human disposal", "high",
     "the machaira megale renamed as nuclear warhead",
     "engravings as ancient language on modern weapon",
     None, False),

    ("Q11", 1, "Parte 1 Promessa", "Sete selos em vitral gotico", "Figura humana contra vitral com sete selos",
     "wide", "symmetric frontal", 28, "f/2.8", "deep",
     "a contemporary human silhouette standing before a massive gothic cathedral stained-glass window depicting seven wax seals, two cracked and glowing crimson, five intact",
     "the two broken seals at top of the window pulsing with crimson light",
     "The figure is faceless, back to camera, illuminated warmly by the stained-glass reflection",
     ["seven wax seals in stained glass", "two cracked glowing crimson", "five intact in dim gold", "faceless silhouetted viewer"],
     "inside a gothic cathedral", "twilight hour", "cosmic confrontation",
     "centered symmetry with figure framing",
     "stained glass in rich crimson, gold, cobalt",
     "silhouetted figure in warm backlight",
     "desaturated black-and-white cathedral interior",
     "divine backlight through stained glass", "faint amber fill on figure", "gold rim on cracked seals", "cosmic awe", "long deep cathedral shadows",
     "Kodak Portra 800", "halation, crushed blacks, stained-glass color bleed", "heavy 35mm grain, dust motes in beams",
     "individual confronted with cosmic timeline", "high",
     "man standing before the apocalyptic schedule",
     "stained glass as divine calendar",
     None, False),

    ("Q12", 1, "Parte 1 Promessa", "Biblia aberta com cruz enferrujada", "Mesa com Biblia e cafe",
     "overhead", "top-down 90", 50, "f/2.8", "medium",
     "an overhead view of an open Bible on a worn wooden table, with a rusted iron cross and a steaming coffee cup beside it, lit by warm lamplight",
     "the rusted iron cross catching amber reflections",
     "Nothing modern except the coffee cup; background desaturated shows empty armchair and night window",
     ["open leather Bible", "rusted iron cross", "steaming coffee cup", "warm lamp overhead"],
     "a quiet home at night", "late evening reflection", "intimate conspiratorial invitation",
     "overhead symmetric composition",
     "Bible, cross, and lamplight in saturated warm ochre-gold",
     "dark wooden table surface",
     "desaturated armchair and night window visible at edges",
     "warm overhead lamp from above", "gold bounce off Bible pages", "amber rim on cross", "intimate", "deep warm shadows",
     "Kodak Portra 800", "halation, crushed blacks, warm highlights", "35mm grain, wood grain, steam particles",
     "invitation to see what the church ignores", "medium",
     "the viewer invited into prophetic reading",
     "rusted cross as enduring faith amid collapse",
     None, False),

    # ---------- PARTE 2 (Q13-Q25) ----------
    ("Q13", 2, "Parte 2 Grego", "Pergaminho grego com cera", "Close pergaminho com gota de cera",
     "close", "straight-on macro", 100, "f/2.8", "razor-thin",
     "a macro close-up of an ancient Greek parchment, koine letters in deep sepia ink, capital letters illuminated in gold",
     "a wax drop that has fallen on a specific Greek word",
     "The parchment fibers are visible in extreme detail, subtle candle flicker reflects off gold leaf",
     ["koine Greek calligraphy", "gold-illuminated capitals", "single wax drop", "visible parchment fibers"],
     "scriptorium of a medieval monk", "candlelit study", "reverent study",
     "rule of thirds on wax drop",
     "parchment and gold in saturated sepia-amber",
     "wax drop pooling over a word",
     "desaturated black-and-white scriptorium walls",
     "warm candlelight from side", "gold bounce off illumination", "amber rim on wax drop", "scholarly hush", "soft deep shadows",
     "Kodak Portra 800", "halation, warm highlights, crushed blacks", "heavy 35mm grain, parchment texture",
     "reverent philological study", "medium",
     "the original text as key to prophecy",
     "wax drop sealing one Greek word as destiny",
     None, False),

    ("Q14", 2, "Parte 2 Grego", "Palavra PYRRHOS em ouro", "Letras gregas em dourado fundido",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "an extreme close-up of the Greek word PYRRHOS calligraphed in molten gold leaf on ancient parchment, with tiny orange embers floating around it",
     "the letters themselves emitting warm glow",
     "The characters appear raised from the page, floating embers drift in slow motion around them",
     ["the exact Greek text PYRRHOS in gold calligraphy", "floating orange embers", "warm parchment glow"],
     "ancient manuscript page", "eternal moment of revelation", "etymological epiphany",
     "centered composition on word",
     "gold letters and embers in vivid amber-crimson",
     "aged parchment fiber texture",
     "completely black desaturated void beyond word",
     "self-emanating gold glow from letters", "amber bounce on parchment", "crimson rim on embers", "revelatory radiance", "deep chiaroscuro all around",
     "Kodak Portra 800 pushed", "halation, heavy halos, crushed blacks, amber saturation", "35mm grain, ember particles",
     "linguistic revelation carrying cosmic weight", "high",
     "the word pyrrhos revealing fire-red true meaning",
     "glowing Greek letters as living prophecy",
     {"enabled": True, "content": "ΠΥΡΡΟΣ", "font_style": "ornate Byzantine Greek calligraphy in molten gold leaf", "medium": "hand-illuminated manuscript", "placement": "centered dominating the frame"},
     True),

    ("Q15", 2, "Parte 2 Grego", "Forja medieval metal aquecido", "Ferreiro malhando metal em brasa",
     "medium", "side-angle", 50, "f/2.0", "medium",
     "interior of a medieval forge with a blacksmith silhouette hammering white-hot crimson metal on an anvil",
     "the glowing metal piece on anvil emitting sparks",
     "Gold-red sparks leap upward; blacksmith face shadowed; forge fire roaring behind",
     ["white-hot crimson metal", "blacksmith silhouette", "leaping gold-red sparks", "forge fire"],
     "medieval forge interior", "night firing", "infernal craftsmanship",
     "rule of thirds on metal",
     "metal and sparks in saturated crimson-gold",
     "anvil and tools in dark steel",
     "desaturated black-and-white forge walls and roof beams",
     "harsh forge fire from left", "amber bounce on anvil", "crimson rim on metal edges", "infernal work", "hard dramatic shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber highlights", "35mm grain, spark and ash particulate",
     "violent labor of war-craft", "medium-high",
     "pyrrhos as color of forge-born war",
     "smith as unwitting forger of judgment",
     None, False),

    ("Q16", 2, "Parte 2 Grego", "Cidade antiga em chamas ao horizonte", "Coluna grega com horizonte em fogo",
     "wide", "panoramic", 24, "f/5.6", "deep",
     "a panoramic wide shot of an ancient city burning on the horizon at sunset, viewed from a distant hill",
     "the entire burning horizon reflecting crimson-gold on low clouds",
     "A fallen Greek column lies in the foreground; no people visible; smoke plumes rise across horizon",
     ["fallen Greek column", "city burning on horizon", "crimson sunset clouds", "rising smoke plumes"],
     "distant hill overlooking antique city", "sunset of destruction", "epic devastation",
     "rule of thirds horizon",
     "fallen column and horizon flames in saturated ochre-crimson",
     "dry hilltop grasses",
     "desaturated black-and-white distant cityscape in smoke",
     "raking sunset from right", "amber bounce off column", "crimson rim on horizon", "epic sorrow", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-amber grading, anamorphic flare", "35mm grain, smoke and ash in air",
     "civilization burning at dusk", "high",
     "pyrrhos as the color of a city at its last light",
     "fallen column as relic of fallen peace",
     None, False),

    ("Q17", 2, "Parte 2 Grego", "Cavalo de fogo em pintura medieval", "Cavalo com pelagem de chamas reais",
     "medium", "side-lateral", 50, "f/2.8", "medium",
     "a medium lateral shot of a medieval painted war horse with coat made of real living flames, steam venting from nostrils, mane of flying sparks",
     "the burning coat textured with real fire licks",
     "A darkened armored rider astride; background plain empty desaturated; embers swirl",
     ["crimson flame horse coat", "spark-mane", "steam breath", "blackened armor rider"],
     "empty battlefield plain", "twilight of vision", "prophetic apparition",
     "rule of thirds on horse head",
     "horse and flames in vivid crimson-gold",
     "scorched earth with embers",
     "desaturated black-and-white empty plain",
     "ambient fire self-glow", "amber bounce on armor", "gold rim on mane sparks", "prophetic vision", "hard dramatic shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber saturation, anamorphic flare", "heavy 35mm grain, live fire particles",
     "Johns apocalyptic vision", "high",
     "horse not of parade red but of war-fire",
     "flame-coat as divine red of judgment",
     None, False),

    ("Q18", 2, "Parte 2 Grego", "Pergaminho PAX rasgado ao meio", "Maos rasgando pergaminho PAX",
     "overhead", "top-down 90", 50, "f/2.8", "medium",
     "an overhead shot of two masculine hands, one gloved in black, one bare, tearing an ancient parchment in half that shows the word PAX in gold calligraphy",
     "the tearing split releasing orange embers from the fiber",
     "The parchment fibers are visible mid-tear; no faces shown, only gloved and bare forearms",
     ["black gloved hand", "bare masculine hand", "parchment with word PAX in gold", "orange embers escaping tear"],
     "council chamber table", "moment of covenant breach", "deliberate violation",
     "overhead symmetric composition",
     "hands, parchment and PAX word in vivid gold-crimson",
     "jacaranda wood council table",
     "desaturated black-and-white empty council chairs around edges",
     "harsh overhead chandelier", "amber bounce off parchment", "gold rim on tearing edge", "violation", "deep chamber shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber highlights", "35mm grain, ember particulate",
     "the active verb of taking peace away", "high",
     "pax being literally torn by powers",
     "gloved hand as hidden authority",
     {"enabled": True, "content": "PAX", "font_style": "ornate Roman calligraphy in molten gold leaf", "medium": "ancient parchment", "placement": "centered across the tear line"},
     True),

    ("Q19", 2, "Parte 2 Grego", "Cavalo branco primeiro selo", "Cavalo branco com cavaleiro coroado",
     "wide", "frontal", 35, "f/4.0", "deep",
     "a majestic medieval white horse, coat luminous ivory-white, in regal pose carrying a crowned rider holding a bow",
     "the horse's luminous coat and the rider's gold crown",
     "The rider is faceless under helm; background shows silhouetted diplomatic signing table in mono",
     ["luminous white horse", "crowned rider with bow", "diplomatic signing table silhouettes"],
     "symbolic plain of false peace", "ceremonial daylight", "deceptive peace",
     "rule of thirds on horse",
     "white horse and gold crown in rich ivory-gold",
     "ceremonial stone floor",
     "desaturated diplomatic scene of signing robed figures",
     "diffuse overhead ceremonial light", "gold bounce on crown", "amber rim on horse mane", "deceptive majesty", "soft diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, dust particulate",
     "first seal as false peace of Abraham Accords", "medium",
     "white horse as treaty peace soon broken",
     "crowned rider as deceptive peace-maker",
     None, False),

    ("Q20", 2, "Parte 2 Grego", "MACHAIRA MEGALE em letras laminas", "Duas palavras gregas em ouro",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "an extreme close-up of the Greek words MACHAIRA MEGALE calligraphed in molten gold on parchment, each letter stroke shaped like a miniature sword-blade",
     "the blade-shaped letterforms glowing warm",
     "The parchment is dense sepia; background completely desaturated vault walls",
     ["Greek text MACHAIRA MEGALE", "blade-shaped gold letterforms", "sepia parchment"],
     "monastic treasury vault", "night of revelation", "terminal terminology",
     "centered on word",
     "gold letters in vivid amber",
     "parchment fiber",
     "desaturated black-and-white vault shadows",
     "self-glow from gold", "faint amber bounce", "gold rim on blade-letters", "revelatory terror", "deep shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber saturation", "35mm grain, parchment texture",
     "naming the weapon of total peace-removal", "high",
     "machaira megale as divinely authorized great sword",
     "letters-as-swords symbolizing word made weapon",
     {"enabled": True, "content": "ΜΑΧΑΙΡΑ ΜΕΓΑΛΗ", "font_style": "blade-shaped Byzantine Greek calligraphy in molten gold leaf", "medium": "hand-illuminated parchment", "placement": "centered across the frame"},
     True),

    ("Q21", 2, "Parte 2 Grego", "Cogumelo atomico vs cavalo de bronze", "Escala entre nuclear e cavalo em bronze",
     "wide", "frontal", 24, "f/5.6", "deep",
     "a wide frame dominated by a monochrome gray mushroom cloud in the background rising from a devastated plain",
     "a small bronze-gold miniature of a red horse on a stone pedestal in the foreground",
     "The scale contrast is brutal; no people; drifting embers between planes",
     ["monochrome mushroom cloud", "small bronze-gold horse statuette", "stone pedestal", "drifting embers"],
     "devastated plain with distant detonation", "moment after blast", "incomprehensible scale",
     "rule of thirds, horse foreground / cloud background",
     "bronze horse and pedestal in rich gold-crimson",
     "cracked earth foreground",
     "desaturated black-and-white mushroom cloud, vast gray scale",
     "diffuse gray blast light", "faint amber bounce on bronze", "gold rim on horse mane", "terror of scale", "long gray shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber foreground, gray background", "35mm grain, ash particulate",
     "machaira megale as nuclear arsenal", "high",
     "ancient prophecy and modern annihilation side by side",
     "small horse as prophetic token foretold cloud",
     None, False),

    ("Q22", 2, "Parte 2 Grego", "Mapa-mundi com pilhas de moedas nucleares", "Moedas de ouro com atomo",
     "overhead", "top-down 75", 50, "f/2.8", "medium",
     "an overhead parchment world map on oak table, with small piles of aged gold coins stamped with atomic symbols on each nuclear country",
     "the tallest piles on Russia and USA",
     "Smaller piles on China, France, UK, India, Pakistan, Israel, North Korea",
     ["parchment world map", "gold atomic-symbol coins", "pile sizes varying by country", "oak table grain"],
     "wartime intelligence chamber", "night analysis session", "ledger of doom",
     "overhead symmetric composition",
     "map and gold coins in vivid gold-ochre",
     "dark oak table surface",
     "desaturated black-and-white ledgers and quills at edges",
     "warm overhead lamp", "gold bounce off coins", "amber rim on piles", "forensic accounting", "deep table shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, dust particulate",
     "inventory of human capacity for annihilation", "high",
     "the great sword counted and weighed",
     "gold coins as ledger of nuclear sin",
     None, False),

    ("Q23", 2, "Parte 2 Grego", "Espada gigante cravada no chao", "Espada grande em campo de batalha",
     "medium", "low-angle", 35, "f/2.8", "medium",
     "a medium low-angle shot of a gigantic medieval greatsword stabbed into cracked earth, ornate gold hilt, steel blade reflecting crimson",
     "the ornate gold hilt towering above",
     "Swirling embers around base; distant ruined battlefield horizon",
     ["gigantic greatsword", "ornate gold hilt", "cracked earth ground", "swirling embers"],
     "devastated historic battlefield", "twilight of history", "monument of terror",
     "low-angle hero composition",
     "sword and embers in vivid gold-crimson-steel",
     "cracked earth with ember scatter",
     "desaturated black-and-white ruined battlefield horizon",
     "raking twilight from right", "amber bounce off blade", "gold rim on hilt", "monumental dread", "long hard shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber highlights", "35mm grain, ash and ember particulate",
     "unprecedented weapon of history", "high",
     "a sword larger than any civilization before",
     "hilt as crown of destruction",
     None, False),

    ("Q24", 2, "Parte 2 Grego", "Silhueta autoritaria do Kremlin", "Silhueta assinando documento",
     "close", "profile-lateral", 85, "f/2.0", "razor-thin",
     "a close-up profile silhouette of an authoritative male figure against stylized crimson Kremlin wall, hands crossed signing a document",
     "the signing hand in motion on the document",
     "No facial features visible; only profile silhouette and hand with pen",
     ["profile silhouette", "crimson Kremlin wall backdrop", "signing hand with ornate pen", "document sheet"],
     "Kremlin office at night", "late night decree", "cold authority",
     "profile silhouette composition",
     "wall and hand in rich crimson-gold",
     "document and pen in warm tones",
     "desaturated Kremlin details beyond",
     "harsh side lamp", "crimson bounce off wall", "gold rim on pen", "icy authority", "deep profile shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson highlights", "35mm grain, fountain-pen texture",
     "the wielder of the great sword identified", "high",
     "nuclear doctrine signed in shadow",
     "the silhouetted signature as transfer of machaira",
     None, False),

    ("Q25", 2, "Parte 2 Grego", "Espada sendo entregue a figura militar", "Transferencia sinistra da espada",
     "wide", "symmetric frontal", 35, "f/4.0", "medium",
     "a wide symmetric frame of a medieval greatsword being passed by two black-gloved hands to a silhouetted figure in contemporary military uniform",
     "the sword itself crossing between the parties",
     "The modern silhouette is faceless; background shows silhouetted nuclear silo infrastructure",
     ["medieval greatsword mid-transfer", "black-gloved giving hands", "faceless military silhouette receiving", "nuclear silo structures"],
     "symbolic meeting of ages", "night of transfer", "sinister covenant",
     "centered symmetric handoff",
     "sword in vivid gold-crimson-steel",
     "transition zone blurred",
     "desaturated black-and-white nuclear silo structures",
     "divine overhead beam on sword", "cold blue fill on modern figure", "gold rim on sword", "sinister solemnity", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber-steel highlights", "35mm grain, ember particulate",
     "the great sword delivered to present age", "high",
     "machaira megale now held by modern rulers",
     "transfer of divine weapon to human doctrine",
     None, False),

    # ---------- PARTE 3 (Q26-Q38) ----------
    ("Q26", 3, "Parte 3 Paz tirada", "Mapa com brasas sobre Oriente Medio", "Mapa-mundi com fogo no Oriente",
     "overhead", "top-down 90", 50, "f/2.8", "medium",
     "an overhead parchment world map on a council table, with real embers falling onto the regions",
     "the Middle East region marked with a crimson circle glowing with fire",
     "The rest of the map is desaturated; low smoke drifts across",
     ["parchment world map", "crimson-glowing Middle East region", "falling real embers", "low drifting smoke"],
     "strategic war room", "night of analysis", "forensic gravity",
     "overhead symmetric, Middle East off-center",
     "Middle East region in vivid crimson-gold",
     "parchment map surface",
     "desaturated rest of the world",
     "warm overhead lamp", "amber bounce on embers", "crimson rim on Middle East", "forensic", "deep ember shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson highlights, amber grading", "35mm grain, live ember particulate",
     "the site where peace was first torn", "high",
     "peace removal beginning in ancient lands",
     "crimson circle as prophetic focus",
     None, False),

    ("Q27", 3, "Parte 3 Paz tirada", "Tanque esmagando flor ucraniana", "Tanque sobre neve P&B com flor",
     "wide", "low-angle", 28, "f/2.8", "deep",
     "a wide low-angle of a dark silhouetted tank advancing across a snowy P&B plain, cannon forward",
     "a single yellow-blue flower crushed under the tread, rendered in ochre-crimson",
     "Breath of diesel and drifting embers; no soldiers visible",
     ["silhouetted battle tank", "crushed flower under tread", "snowy plain in monochrome", "drifting embers"],
     "Ukrainian plain in winter", "pre-dawn invasion 24 Feb 2022", "invasion historic",
     "low-angle converging lines",
     "crushed flower in vivid ochre-crimson",
     "tank treads visible",
     "desaturated black-and-white snowy plain",
     "cold dawn light", "faint amber bounce off flower", "crimson rim on petals", "historic violation", "long diagonal shadows",
     "Kodak Vision3 500T pushed", "halation, crushed blacks, amber-crimson pop, anamorphic flare", "35mm grain, snow mist",
     "invasion as second seal cracking", "high",
     "peace of Europe ended in one dawn",
     "crushed flower as 70 years of peace destroyed",
     None, False),

    ("Q28", 3, "Parte 3 Paz tirada", "Cemiterio militar infinito", "Cruzes ortodoxas e estrelas vermelhas",
     "wide", "panoramic", 24, "f/5.6", "deep",
     "a panoramic wide of a military cemetery stretching to the horizon, orthodox crosses and red stars aligned on frozen ground",
     "a single wooden cross in foreground with helmet hanging",
     "Background infinite rows in P&B; low drifting smoke",
     ["single wooden cross with helmet", "infinite orthodox crosses and red stars", "frozen ground", "drifting smoke"],
     "mass military cemetery in Eastern Europe", "winter dusk", "industrial mourning",
     "leading lines to vanishing point",
     "foreground cross in vivid ochre-amber",
     "frozen earth foreground",
     "desaturated infinite cross field to horizon",
     "raking dusk from left", "amber bounce on helmet", "gold rim on cross", "silent grief", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber highlights, anamorphic flare", "heavy 35mm grain, winter mist",
     "500000 dead counted in one frame", "high",
     "machaira megale in Ukraine",
     "single cross as personalized scale of catastrophe",
     None, False),

    ("Q29", 3, "Parte 3 Paz tirada", "Cerca de Gaza rasgada", "Kipa dourada e lenco sobre areia",
     "medium", "frontal", 40, "f/2.8", "medium",
     "a medium shot of a torn metal security fence, razor wire dangling in foreground",
     "a golden kippah and a faded keffiyeh on sand in foreground",
     "Desaturated Gaza desert at dawn; no human figures",
     ["torn metal fence", "hanging razor wire", "golden kippah", "faded keffiyeh on sand"],
     "Gaza fence border at dawn", "5 AM, October 7 2023", "sacred violation",
     "rule of thirds on objects",
     "kippah and keffiyeh in vivid gold-ochre",
     "sandy ground foreground",
     "desaturated Gaza desert dawn",
     "dawn side light from right", "amber bounce on kippah", "gold rim on fence", "sacred violation", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber highlights", "35mm grain, sand particulate",
     "Hamas breach as cascade trigger", "high",
     "second front of the second seal",
     "sacred items desecrated in sand",
     None, False),

    ("Q30", 3, "Parte 3 Paz tirada", "Tora e menora com fogo distante", "Pergaminho sobre mesa com reflexos",
     "close", "frontal", 60, "f/2.0", "medium",
     "a close-up of a Torah scroll on dark wood table with a golden menorah alongside",
     "distant fire flicker reflecting on the parchment",
     "No human figures; window behind shows bombed buildings in P&B",
     ["Torah scroll", "golden menorah", "flickering parchment reflection", "bombed window silhouettes"],
     "Israeli synagogue study", "night of war declaration", "antiquity in modern war",
     "rule of thirds on scroll",
     "Torah and menorah in vivid gold-crimson",
     "dark wood table",
     "desaturated bombed cityscape through window",
     "flickering distant fire glow", "amber bounce off parchment", "gold rim on menorah", "ancient war", "deep warm shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, parchment texture",
     "Israel's war declared", "high",
     "covenant people in ancient modern war",
     "menorah as enduring flame amid bombardment",
     None, False),

    ("Q31", 3, "Parte 3 Paz tirada", "Oriente Medio aereo em chamas", "Circulos concentricos de fogo",
     "wide", "aerial overhead 75", 35, "f/5.6", "deep",
     "an aerial stylized overhead of the entire Middle East region on fire, concentric circles of gold-crimson flame marking Israel, Lebanon, Yemen, Iraq, Iran",
     "the converging flame circles",
     "Desaturated rest of region; smoke curls upward",
     ["concentric fire circles marking 5 nations", "smoke columns rising", "regional scale"],
     "aerial view of Middle East", "72 hours after Oct 7", "region in combustion",
     "overhead aerial composition",
     "fire circles in vivid gold-crimson",
     "regional geography",
     "desaturated regional terrain",
     "diffuse overhead", "amber bounce from fires", "crimson rim on smoke", "regional apocalypse", "drifting shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-amber saturation", "35mm grain, smoke particulate",
     "Middle East ignited in 72 hours", "high",
     "Abraham Accords promise incinerated",
     "five fronts as five spokes of burning wheel",
     None, False),

    ("Q32", 3, "Parte 3 Paz tirada", "Ceu noturno com 300 misseis", "Jerusalem com rastros e Tel Aviv P&B",
     "wide", "low-angle", 24, "f/2.8", "deep",
     "a wide low-angle night sky filled with 300 missile and drone trails crossing diagonally",
     "the golden Jerusalem dome with orange flame reflections in foreground",
     "Background Tel Aviv skyline in monochrome; trails glow crimson-gold",
     ["golden Jerusalem dome", "300 missile trails", "monochrome Tel Aviv skyline", "orange reflections"],
     "Jerusalem night sky April 13 2024", "night of first direct Iranian strike", "historic threshold",
     "rule of thirds trails across upper half",
     "dome and trails in vivid gold-crimson",
     "rooftop silhouettes",
     "desaturated Tel Aviv",
     "missile trail glow", "amber bounce on dome", "crimson rim on rooftops", "threshold broken", "hard diagonal shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson saturation, anamorphic flare", "35mm grain, ash",
     "first direct Iranian strike on Israel", "high",
     "boundary of history transgressed",
     "trails as first blows of peace removal",
     None, False),

    ("Q33", 3, "Parte 3 Paz tirada", "Linha fronteirica rachada em mapa", "Linha dourada rachada por fogo",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "an extreme close-up of a border line drawn in gold ink on a map, now cracked down the middle by a thin line of crimson fire",
     "the crack propagating across the gold line",
     "Desaturated map surface around the line",
     ["gold-ink border line", "crimson fire crack", "map texture"],
     "war room map table", "moment of realization", "historical rupture",
     "centered composition",
     "border line and fire in vivid gold-crimson",
     "map paper texture",
     "desaturated surrounding map",
     "warm lamp overhead", "amber bounce on line", "gold rim on crack", "rupture", "deep chiaroscuro",
     "Kodak Portra 800", "halation, crushed blacks, amber-crimson highlights", "35mm grain, paper fiber",
     "border never crossed now crossed", "high",
     "transgression recorded",
     "gold line as inviolable barrier now broken",
     None, False),

    ("Q34", 3, "Parte 3 Paz tirada", "I DE OUTUBRO ceu com 180 misseis", "Calendario e trajetorias",
     "overhead", "top-down 75", 35, "f/4.0", "deep",
     "an overhead shot of a night sky seen from below with 180 ballistic missile trails crossing, and an ancient calendar foreground marking I DE OUTUBRO",
     "the crimson-marked date on the parchment calendar",
     "Below, desaturated city illuminated by explosions",
     ["180 missile trajectories", "parchment calendar with date I DE OUTUBRO", "desaturated city below"],
     "sky over Israel 1 October 2024", "night of second salvo", "escalated retaliation",
     "overhead composition",
     "calendar and trails in vivid crimson-gold",
     "trails mid-sky",
     "desaturated illuminated city below",
     "missile glow", "amber bounce on calendar", "crimson rim on date", "escalation", "hard shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson highlights", "35mm grain, ash",
     "second Iranian salvo", "high",
     "escalation of the second seal",
     "calendar as prophetic timestamp",
     {"enabled": True, "content": "I DE OUTUBRO", "font_style": "ornate Roman-numeral calligraphy in crimson ink", "medium": "aged parchment calendar", "placement": "lower foreground centered"},
     True),

    ("Q35", 3, "Parte 3 Paz tirada", "F-35 cruzando por-do-sol carmesim", "Jato sobre montanhas aridas",
     "wide", "lateral", 35, "f/4.0", "deep",
     "a wide lateral of an F-35 stealth fighter silhouette crossing a blood-crimson sunset over arid Iranian mountains",
     "the silhouetted jet reflecting faint gold on canopy",
     "No other aircraft visible; monochrome mountain ridges below",
     ["F-35 silhouette", "crimson sunset sky", "arid mountain ridges", "condensation trail"],
     "over Iranian highlands October 26 2024", "dusk of retaliation", "precedent crossed",
     "rule of thirds jet",
     "sunset sky in vivid crimson-ochre",
     "jet silhouette mid-frame",
     "desaturated mountain ridges",
     "sunset back glow", "amber bounce on cockpit", "gold rim on wings", "precedent", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-ochre grading, anamorphic flare", "35mm grain, high altitude haze",
     "Israel strikes Iran directly", "high",
     "retaliation precedent",
     "jet as modern arrow of judgment",
     None, False),

    ("Q36", 3, "Parte 3 Paz tirada", "Instalacao nuclear iraniana cortada", "Cross-section em estilo medieval",
     "medium", "lateral", 40, "f/4.0", "medium",
     "a medium lateral cross-section styled as a medieval illuminated illustration of a subterranean Iranian nuclear facility",
     "crimson-gold reactor cores being struck",
     "Layered structure visible; embers falling from ceiling",
     ["cross-section nuclear facility", "crimson reactor cores", "falling embers", "labeled chambers with illegible script"],
     "underground Iranian facility Fordow", "June 2025 12-day war", "surgical destruction",
     "layered cross-section",
     "reactor cores in vivid crimson-gold",
     "facility walls in stone",
     "desaturated rest of facility",
     "reactor glow from below", "amber bounce off walls", "gold rim on ceiling", "surgical", "dramatic cross-section shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson highlights", "35mm grain, stone and steel texture",
     "12-day war strikes", "high",
     "great sword striking the forge of another great sword",
     "reactor cores as infernal altars",
     None, False),

    ("Q37", 3, "Parte 3 Paz tirada", "Livro Apocalipse com pena e relogio", "Pena preta sobre versiculo 4",
     "overhead", "top-down 90", 50, "f/2.0", "medium",
     "an overhead of an open leather Bible showing Apocalypse 6 with a single black feather on verse 4, beside an antique brass pocket clock",
     "the feather resting on the verse",
     "The clock reads 3:17; warm light from left",
     ["open Bible Apocalypse 6", "single black feather", "brass pocket clock at 3:17", "worn wooden altar"],
     "altar of contemplation", "dawn of Khameneis death", "prophetic weight",
     "overhead symmetric",
     "feather and clock in vivid crimson-gold",
     "dark wooden altar",
     "desaturated altar cloth and walls",
     "warm overhead lantern", "amber bounce on pages", "gold rim on clock", "heavy prophecy", "deep altar shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber-crimson highlights", "35mm grain, parchment",
     "Khameneis death as prophetic marker", "high",
     "the verse and the hour",
     "feather as weight of a falling soul",
     None, False),

    ("Q38", 3, "Parte 3 Paz tirada", "Cavalo vermelho em disparada", "Cavalo com cauda de fogo pisando cadaveres",
     "wide", "dynamic 3/4 forward", 28, "f/2.8", "deep",
     "a wide 3/4 forward dynamic of the red horse from Q07 now in full gallop, flame tail streaming",
     "the horse mid-stride with fire tail",
     "Below the horse, a P&B field of fallen soldiers; no individual faces shown",
     ["galloping crimson fire horse", "streaming flame tail", "fallen figures in P&B", "swirling embers"],
     "field of devastation", "climax of second seal", "prophetic accusation",
     "dynamic diagonal",
     "horse in vivid crimson-gold",
     "cracked ground",
     "desaturated fallen soldiers",
     "galloping embers glow", "amber bounce on horse", "gold rim on flame tail", "accusatory", "long diagonal shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson saturation, anamorphic flare", "heavy 35mm grain, fire particles",
     "the second seal in motion today", "high",
     "the rider taking peace as literal reality",
     "horse-as-history riding through corpses",
     None, False),

    # ---------- PARTE 4 (Q39-Q51) ----------
    ("Q39", 4, "Parte 4 Gog", "Ezequiel medieval iluminura", "Profeta em manto azul-dourado",
     "close", "3/4 frontal", 85, "f/2.0", "razor-thin",
     "a close-up 3/4 of a medieval illuminated depiction of prophet Ezekiel, bearded, robed in cobalt-blue and gold, eyes wide",
     "his wide eyes catching gold leaf reflection",
     "He holds an open scroll; no modern elements",
     ["Ezekiel bearded face", "cobalt-blue and gold robe", "open scroll in hand", "halo gold leaf"],
     "Babylonian exile by the river Chebar", "vision moment", "ancient seeing modern",
     "rule of thirds on face",
     "robe and halo in vivid cobalt-gold-crimson",
     "parchment scroll",
     "desaturated background mostly black",
     "divine overhead beam", "amber bounce on face", "gold rim on halo", "prophetic awe", "deep Caravaggio shadows",
     "Kodak Portra 800", "halation, crushed blacks, cobalt and gold saturation", "35mm grain, parchment fiber",
     "Ezekiel 38 authored 2600 years ago", "high",
     "ancient prophet seeing modern coalition",
     "halo as divine inspiration confirming geopolitical map",
     None, False),

    ("Q40", 4, "Parte 4 Gog", "Rolo de Ezequiel com palavra GOG", "Pluma escrevendo em hebraico",
     "overhead", "top-down 90", 50, "f/2.0", "medium",
     "an overhead of an unrolled parchment scroll on dark wood, Hebrew characters in sepia ink",
     "a quill pen writing the word GOG in dramatic crimson at the top",
     "Candlelight from left; no figures",
     ["unrolled parchment", "Hebrew text of Ezekiel 38", "quill pen mid-stroke", "GOG written in crimson"],
     "scribe's desk in exile", "moment of inspiration", "written prophecy",
     "overhead symmetric",
     "parchment and word GOG in vivid crimson-gold",
     "dark wood desk",
     "desaturated scriptorium edges",
     "warm candlelight left", "amber bounce on parchment", "gold rim on quill", "inspired writing", "deep desk shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson saturation", "35mm grain, parchment texture",
     "the naming of Gog in scripture", "high",
     "the coalition named in advance",
     "crimson word GOG as call of judgment",
     {"enabled": True, "content": "גוג", "font_style": "archaic Hebrew calligraphy in crimson ink", "medium": "ancient parchment scroll", "placement": "centered top area of the scroll"},
     True),

    ("Q41", 4, "Parte 4 Gog", "Ganchos dourados no queixo", "Figura gigante fisgando exercito",
     "medium", "frontal", 50, "f/2.8", "medium",
     "a medium frontal of a medieval stylized illustration showing a giant divine figure literally hooking the jaw of a colossal beast with gold hooks",
     "the gold hooks piercing the jaw",
     "Background horde army faintly visible monochrome",
     ["giant divine hand with gold hooks", "colossal beast jaw", "monochrome horde army"],
     "symbolic desert prophecy", "moment of divine command", "prophetic dragging",
     "rule of thirds on hooks",
     "hooks and beast jaw in vivid gold-crimson",
     "rocky desert ground",
     "desaturated horde army in background",
     "divine overhead beam", "amber bounce on hooks", "gold rim on beast scales", "prophetic dragging", "dramatic shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber-crimson highlights", "35mm grain, stone and bone texture",
     "God drags Gog to appointed battle", "high",
     "gold hooks as divine determinism",
     "beast as proxy for massed armies",
     None, False),

    ("Q42", 4, "Parte 4 Gog", "Mapa Russia com cidade medieval", "Kremlin em iluminura com linhas de fogo",
     "wide", "overhead 60", 35, "f/5.6", "deep",
     "a wide overhead medieval illustrated map parchment showing Russian plains, with Moscow drawn as a medieval city with golden cupolas",
     "lines of crimson fire connecting Moscow to northern Israel",
     "Background desaturated rest of world map",
     ["medieval Moscow with gold cupolas", "crimson fire connection lines", "parchment world map"],
     "scriptorium map chamber", "study of prophecy", "geographic revelation",
     "overhead with leading fire lines",
     "Moscow and fire lines in vivid gold-crimson",
     "parchment texture",
     "desaturated rest of map",
     "warm overhead lamp", "amber bounce on cupolas", "gold rim on fire lines", "revelatory", "deep map shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-amber saturation", "35mm grain, parchment fiber",
     "Meseque Tubal identified as Russia", "high",
     "ancient names mapped to modern territory",
     "fire lines as prophetic causation",
     None, False),

    ("Q43", 4, "Parte 4 Gog", "Imperador persa em perfil", "Perfil com turbante dourado",
     "close", "profile-lateral", 85, "f/2.0", "razor-thin",
     "a close-up profile of an ancient Persian emperor, long black beard, golden turban, crimson robe with ochre embroidery",
     "the gold turban catching light",
     "Background desaturated modern Iranian oil refinery towers",
     ["Persian emperor profile", "golden turban", "crimson ochre-embroidered robe", "long black beard"],
     "palace of ancient Persia", "historical eternal moment", "timeless identity",
     "profile composition",
     "turban and robe in vivid gold-crimson-ochre",
     "marble column nearby",
     "desaturated oil refinery towers",
     "warm side light", "amber bounce on beard", "gold rim on turban", "timeless identity", "deep profile shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold-crimson saturation", "35mm grain, fabric texture",
     "Persia explicitly named is Iran", "medium-high",
     "Iran as ancient Persia in prophecy",
     "emperor as continuity of national destiny",
     None, False),

    ("Q44", 4, "Parte 4 Gog", "Triptico Gomer Pute Cuxe", "Tres iluminuras com guerreiros",
     "overhead", "top-down 90", 50, "f/2.8", "medium",
     "an overhead of three medieval illustrated panels arranged as a triptych on a table: a Turkish warrior, a Libyan chieftain, an Ethiopian soldier",
     "each figure in vivid color on their panel",
     "Around them a monochrome world map; low smoke",
     ["three medieval warrior portraits", "monochrome world map", "low smoke"],
     "scriptorium prophecy table", "study of coalition", "ancestral coalition",
     "overhead tripartite symmetry",
     "three warriors in vivid gold-crimson-ochre",
     "map surface",
     "desaturated world map",
     "warm overhead lamp", "amber bounce on panels", "gold rim on frames", "ancestral identification", "deep table shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber saturation", "35mm grain, parchment",
     "Gomer Pute Cush named as Turkey Libya Ethiopia", "medium",
     "three nations of the coalition identified",
     "triptych as prophetic census",
     None, False),

    ("Q45", 4, "Parte 4 Gog", "Joel Rosenberg silhueta com livro", "Mao segurando livro dourado",
     "medium", "3/4 profile", 50, "f/2.8", "medium",
     "a medium 3/4 profile silhouette of a contemporary male figure at an American library desk, holding a leather book titled with illegible gold lettering",
     "the gold-lettered book cover",
     "Background desaturated American library shelves",
     ["silhouetted male figure", "leather book with gold lettering", "mahogany desk", "library shelves"],
     "American Christian scholar's library", "late evening study", "analytical authority",
     "rule of thirds on book",
     "book and hand in vivid gold-crimson",
     "dark mahogany desk",
     "desaturated library shelves",
     "warm desk lamp", "amber bounce on book", "gold rim on fingers", "scholarly authority", "deep library shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, leather texture",
     "Rosenberg mapping the coalition", "medium",
     "analyst presenting prophetic thesis",
     "gold book as authoritative scholarship",
     None, False),

    ("Q46", 4, "Parte 4 Gog", "A beira da guerra de Gog", "Figura caminhando sobre linha do deserto",
     "wide", "panoramic", 24, "f/5.6", "deep",
     "a wide panoramic of a line drawn across desert sand, one side monochrome modern world, other side crimson-gold prophetic vision",
     "a solitary hooded figure walking on the exact line",
     "Embers fall on the crimson side; stillness on the mono side",
     ["line across desert", "hooded solitary figure", "falling embers on crimson side", "dust clouds on monochrome side"],
     "metaphorical desert of prophecy", "twilight threshold", "apocalyptic brink",
     "rule of thirds on figure",
     "figure and crimson side in vivid ochre-crimson-gold",
     "desert sand",
     "desaturated monochrome half",
     "raking twilight", "amber bounce on crimson side", "gold rim on figure", "threshold", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-ochre saturation, anamorphic flare", "35mm grain, sand particulate",
     "brink of Gog-Magog war", "high",
     "walker on the threshold of prophecy",
     "line as divide between epochs",
     None, False),

    ("Q47", 4, "Parte 4 Gog", "Placas Pentagon Knesset White House", "Mesa institucional com tres placas",
     "overhead", "top-down 90", 50, "f/2.8", "medium",
     "an overhead of an institutional oak table with three engraved metal plates: PENTAGON, KNESSET, WHITE HOUSE",
     "the three gold plates in a row",
     "An empty leather chair at center with open leather book",
     ["three aged brass plaques PENTAGON KNESSET WHITE HOUSE", "empty leather chair", "open leather book"],
     "institutional conference table", "empty evening chamber", "institutional credibility",
     "overhead symmetric",
     "plates and book in vivid gold-brass-crimson",
     "oak table",
     "desaturated chamber edges",
     "warm overhead lamp", "gold bounce on plates", "amber rim on book", "institutional", "deep table shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold-amber highlights", "35mm grain, brass patina",
     "Rosenberg's institutional access", "medium",
     "the prophetic thesis in seats of power",
     "empty chair as invited witness",
     {"enabled": True, "content": "PENTAGON · KNESSET · WHITE HOUSE", "font_style": "engraved Trajan capitals on aged brass", "medium": "metal institutional plaques", "placement": "centered across the table in a row"},
     True),

    ("Q48", 4, "Parte 4 Gog", "Tratado Russia-Ira selos", "Maos sobre documento com aguia e leao",
     "medium", "overhead 60", 50, "f/2.8", "medium",
     "a medium overhead of two masculine hands shaking over an official document bearing a Russian gold eagle and a Persian ochre lion seal",
     "the two seals catching warm light",
     "Gold pens lie beside; background Kremlin hall silhouetted",
     ["Russian gold eagle seal", "Persian ochre lion seal", "two masculine hands shaking", "gold fountain pens", "Kremlin hall silhouettes"],
     "Kremlin signing hall", "January 2025", "alliance sealed",
     "overhead with seals centered",
     "seals and hands in vivid gold-ochre-crimson",
     "dark mahogany desk",
     "desaturated Kremlin hall",
     "warm chandelier overhead", "amber bounce on seals", "gold rim on pens", "alliance", "deep desk shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold-amber saturation", "35mm grain, wax and paper texture",
     "Russia-Iran strategic partnership", "high",
     "Gog-Persia alliance documented",
     "sealed handshake as historic binding",
     None, False),

    ("Q49", 4, "Parte 4 Gog", "Bandeira turca rasgada", "Metade em cores e metade em po P&B",
     "wide", "lateral", 35, "f/2.8", "deep",
     "a wide lateral of a Turkish flag stylized on parchment being torn down the middle, one half still with vivid crimson-gold crescent emblem, the other dissolving into gray dust",
     "the dividing tear releasing ash",
     "Background desaturated Ankara cityscape",
     ["Turkish flag parchment", "torn middle", "vivid crescent half", "gray dust half", "background Ankara"],
     "symbolic realignment moment", "historic pivot", "tectonic realignment",
     "rule of thirds on tear",
     "vivid half in rich crimson-gold",
     "torn line",
     "desaturated Ankara and dust half",
     "raking side light", "amber bounce on crescent", "gold rim on tear", "realignment", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-gold saturation", "35mm grain, ash particulate",
     "Turkey pivots toward Moscow and Teheran", "medium-high",
     "Gomer realigns in real time",
     "torn flag as divided allegiance",
     None, False),

    ("Q50", 4, "Parte 4 Gog", "Coalizao formada em mesa redonda", "Cinco figuras silhuetadas ao redor de Israel",
     "wide", "symmetric frontal", 28, "f/4.0", "deep",
     "a wide symmetric of five silhouetted figures around a medieval round table, each lit with a distinct rich hue (crimson, ochre, gold, copper, terracotta)",
     "a parchment at center showing the word Israel in Hebrew and Latin",
     "No faces visible; each figure's shadow falls across the parchment",
     ["five silhouetted figures", "round medieval table", "central parchment reading Israel", "five colored lights"],
     "coalition chamber", "midnight meeting", "prophecy fulfilled",
     "symmetric circular composition",
     "five hues and parchment in vivid saturated tones",
     "round table surface",
     "desaturated chamber edges",
     "five colored side-lights", "mixed amber bounce", "gold rim on parchment", "coalition gathered", "radial shadows from each figure",
     "Kodak Portra 800", "halation, crushed blacks, multi-hue saturation", "35mm grain, dust",
     "Ezekiels coalition assembled today", "high",
     "prophecy of five nations now fulfilled",
     "multi-colored silhouettes around one target",
     {"enabled": True, "content": "ISRAEL", "font_style": "bilingual Hebrew calligraphy in crimson and Latin engraving in gold", "medium": "central parchment", "placement": "centered on round table"},
     True),

    ("Q51", 4, "Parte 4 Gog", "Balanca com Ezequiel e manchetes", "Balanca dourada desnivelada",
     "close", "symmetric frontal", 85, "f/2.0", "razor-thin",
     "a close-up symmetric of an antique gold balance scale, on one side the open book of Ezekiel, on the other a stack of modern newspaper headlines in grayscale",
     "the fulcrum tipping toward Ezekiel",
     "Both sides weighted but the ancient book tips slightly lower",
     ["antique gold balance scale", "open Ezekiel book", "stack of gray newspaper headlines", "mahogany base"],
     "scholar's judgment desk", "moment of verdict", "personal judgment",
     "centered symmetric",
     "balance and book in vivid gold-sepia",
     "mahogany base",
     "desaturated background",
     "warm desk lamp", "amber bounce on gold pans", "gold rim on scale arm", "verdict", "deep desk shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold saturation", "35mm grain, paper and metal texture",
     "coincidence or prophecy fulfilled", "high",
     "weighing scripture against news",
     "balance as personal summons",
     None, False),

    # ---------- PARTE 5 (Q52-Q60) ----------
    ("Q52", 5, "Parte 5 Tribulacao", "Sete selos em fileira sobre pergaminho", "Dois rachados cinco intactos",
     "overhead", "top-down 90", 50, "f/2.8", "medium",
     "an overhead of seven wax seals in a row on a long parchment, the first two cracked and glowing crimson, the other five intact in dull gold",
     "the two cracked glowing seals",
     "Single candle flame left; low drifting smoke",
     ["seven wax seals in a row", "two cracked crimson seals", "five intact gold seals", "candle flame"],
     "altar of prophecy", "candlelit final exposition", "apocalyptic accounting",
     "overhead horizontal composition",
     "seals in vivid crimson-gold",
     "parchment",
     "desaturated altar cloth",
     "warm candlelight left", "amber bounce on seals", "gold rim on cracked ones", "accounting", "deep altar shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson saturation", "35mm grain, wax and parchment",
     "seals are sequential and trackable", "high",
     "two down five to go",
     "seals as clock of end times",
     None, False),

    ("Q53", 5, "Parte 5 Tribulacao", "Cavalo branco resumo", "Cavaleiro coroado com arco",
     "medium", "side-lateral", 50, "f/2.8", "medium",
     "a medium lateral of the white horse of the first seal, coat luminous ivory, rider faceless under crowned helm holding a golden bow",
     "the crown and bow catching gold light",
     "Background desaturated view of Jerusalem at peace",
     ["luminous white horse", "faceless crowned rider", "golden bow", "desaturated peaceful Jerusalem"],
     "plain of deceptive peace", "midday ceremonial", "peace that was",
     "rule of thirds",
     "horse and crown in vivid ivory-gold",
     "ceremonial ground",
     "desaturated Jerusalem",
     "diffuse overhead", "gold bounce on crown", "amber rim on mane", "remembered peace", "soft diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, dust",
     "first seal: the peace that was", "medium",
     "white horse recap",
     "crown as false peace",
     None, False),

    ("Q54", 5, "Parte 5 Tribulacao", "Cavalo vermelho resumo com espada erguida", "Cavaleiro levantando grande espada",
     "medium", "side-lateral", 50, "f/2.8", "medium",
     "a medium lateral of the red horse of the second seal, flame-crimson coat, rider raising the great sword above head",
     "the raised sword blade reflecting crimson",
     "Background desaturated modern city ruins",
     ["crimson flame horse", "armored rider with raised great sword", "desaturated city ruins"],
     "battlefield of seals present", "climax moment", "seal in execution",
     "rule of thirds on sword",
     "horse and sword in vivid crimson-gold",
     "cracked ground",
     "desaturated ruins",
     "harsh flame glow", "amber bounce on armor", "gold rim on sword", "executing judgment", "hard shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson saturation", "35mm grain, fire particles",
     "second seal in action now", "high",
     "red horse recap",
     "raised sword as current reality",
     None, False),

    ("Q55", 5, "Parte 5 Tribulacao", "Cavalo preto no horizonte", "Terceiro selo surgindo com balanca",
     "wide", "panoramic", 35, "f/4.0", "deep",
     "a wide panoramic with the red horse seen from behind in foreground, and at far horizon a distant black horse silhouette carrying a gold balance",
     "the distant black horse on horizon",
     "Red horse rich crimson from behind; distant silhouette emerging",
     ["red horse from behind foreground", "distant black horse silhouette", "gold balance held by distant rider", "horizon line"],
     "symbolic plain of transition", "dusk of transition", "next wave",
     "leading line to horizon",
     "red horse in vivid crimson",
     "plain with embers",
     "desaturated black horse silhouette with gold balance",
     "raking dusk", "amber bounce on red horse", "gold rim on distant balance", "anticipation", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-gold saturation", "35mm grain, dust",
     "third seal rising while second still rides", "high",
     "sequential opening of the seals",
     "black horse on horizon foreshadowing famine",
     None, False),

    ("Q56", 5, "Parte 5 Tribulacao", "Balanca com trigo e moedas", "Balanca dourada desnivelada",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "an extreme close-up of an antique gold balance unevenly tipped, one side holding a single vibrant wheat grain, the other side spilling gold coins",
     "the single wheat grain glowing warm",
     "Background desaturated ruined Ukrainian granary",
     ["gold balance", "single wheat grain", "spilling gold coins", "desaturated granary"],
     "granary of scarcity", "dusk of want", "imminent scarcity",
     "centered symmetric",
     "balance and wheat in vivid gold-ochre",
     "balance base",
     "desaturated granary",
     "warm side light", "amber bounce on wheat", "gold rim on coins", "want", "deep shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold-ochre saturation", "35mm grain, grain dust",
     "wheat and the price of bread", "high",
     "third seal economic of hunger",
     "wheat grain as weighed destiny",
     None, False),

    ("Q57", 5, "Parte 5 Tribulacao", "Celeiro ucraniano em ruinas", "Trator enferrujado com girassois queimados",
     "overhead", "top-down 75", 35, "f/5.6", "deep",
     "an overhead of a ruined Ukrainian granary with spilled wheat grains on the floor, a single rusted tractor in warm ochre tones",
     "the rusted tractor",
     "Background desaturated scorched sunflower fields",
     ["ruined granary", "spilled wheat grains", "rusted tractor", "scorched sunflower fields"],
     "Ukrainian farmland after war", "post-harvest of destruction", "famished economy",
     "overhead converging lines",
     "tractor and grain in vivid ochre-crimson",
     "granary floor",
     "desaturated sunflower fields",
     "diffuse overcast light", "amber bounce on tractor", "gold rim on wheat", "famished", "long diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, ochre saturation", "35mm grain, dust and ash",
     "war destroyed the world's grain", "medium-high",
     "famine already in motion",
     "rusted tractor as halted harvest",
     None, False),

    ("Q58", 5, "Parte 5 Tribulacao", "Cordeiro medieval em manto branco-dourado", "Cordeiro com chagas e bencao",
     "wide", "frontal symmetric", 35, "f/4.0", "deep",
     "a wide symmetric frontal of a medieval Lamb of God figure in luminous white-gold robes, golden wounds visible, one hand raised in blessing",
     "the raised blessing hand",
     "Background transitions from desaturated gray to warm gold sky",
     ["medieval Lamb figure", "luminous white-gold robes", "golden wounds", "raised blessing hand", "transitioning sky"],
     "celestial chamber of rescue", "dawn of hope", "theological hope",
     "centered symmetric",
     "Lamb in vivid white-gold-crimson",
     "robes drapery",
     "desaturated to gold transition sky",
     "divine overhead beam", "amber bounce on robes", "gold rim on wounds", "hope", "soft radial shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold saturation, divine halation", "35mm grain, dust motes",
     "Apocalypse 7 rescue alongside judgment", "medium",
     "the Lamb as rescuer not destroyer",
     "wounds as sign of suffering redeemer",
     None, False),

    ("Q59", 5, "Parte 5 Tribulacao", "Maos do Cordeiro rachando selo", "Dedos com chagas sobre selo vermelho",
     "overhead", "top-down 90", 60, "f/2.0", "medium",
     "a dramatic overhead of the Lamb's hands (gold and crimson stained) gripping a wax seal from the scroll and pulling it apart",
     "the cracking seal mid-break",
     "Vertical divine beam; no faces visible",
     ["Lambs golden bloodied hands", "wax seal being broken", "divine overhead beam", "scroll"],
     "heavenly altar before the throne", "eternal moment", "cosmic act",
     "overhead symmetric",
     "hands and seal in vivid gold-crimson",
     "scroll surface",
     "desaturated throne edges",
     "vertical divine beam", "amber bounce on hands", "gold rim on seal", "cosmic act", "deep throne shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold-crimson saturation, divine halation", "35mm grain, dust motes",
     "the Lamb opening the seals one by one", "high",
     "authority over the apocalypse",
     "wounded hands cracking seals",
     None, False),

    ("Q60", 5, "Parte 5 Tribulacao", "Tela final com cavalo dissipando em brasas", "Silhueta distante em brasas",
     "wide", "empty frame", 35, "f/5.6", "deep",
     "a wide nearly-black frame with only the faintest silhouetted contour of a distant red horse dissolving into floating embers in the lower-right corner",
     "the dissolving ember trail",
     "Frame is 95 percent black, textured grain",
     ["faint distant red horse silhouette", "floating embers", "nearly-black frame"],
     "void of fade-to-black", "moment of closing", "prophetic closure",
     "negative space composition",
     "distant horse and embers in muted crimson-amber",
     "deep void",
     "near-total black",
     "no visible key light", "ember self-glow", "faint amber rim on particles", "closure", "absolute black",
     "Kodak Double-X pushed", "halation on embers, crushed blacks", "heavy 35mm grain",
     "end of transmission closure", "medium",
     "the horse rides on into the next seal",
     "fade to black as punctuation",
     None, False),
]


def build_json(f):
    (quadro, parte, ato, scene_title, narrative_beat, shot_type, cam_angle, focal, aperture, dof,
     primary, focal_point, secondary, props,
     location, time_of_day, atmosphere,
     rule, foreground, midground, background,
     key, fill, rim, light_mood, shadow,
     film_stock, post, texture,
     emotion, tension,
     sym_primary, sym_secondary,
     in_scene_text, use_pro) = f

    ist = in_scene_text if in_scene_text else {"enabled": False}

    api_hints = {
        "multimodal_inputs": [
            {"type": "image", "source": "style_reference.primary_image_url", "role": "style_reference",
             "instruction": "Transfer color palette, lighting, grain, atmosphere only. Do not copy composition."},
            {"type": "text", "source": "serialized_prompt_from_this_json", "role": "scene_description"}
        ]
    }
    if use_pro:
        api_hints = {"model_override": "pro", **api_hints}

    return {
        "id": f"video-013_PARTE{parte}_{quadro}",
        "version": "nano-banana-v1",
        "model_target": "gemini-2.5-flash-image",
        "scene_title": scene_title,
        "narrative_beat": narrative_beat,
        "canal_context": {
            "canal": CANAL, "video": VIDEO, "parte_suno": parte, "quadro": quadro, "ato": ato
        },
        "style_reference": STYLE_REF,
        "shot": {
            "type": shot_type, "camera_angle": cam_angle, "focal_length_mm": focal,
            "aperture": aperture, "depth_of_field": dof, "aspect_ratio": "16:9"
        },
        "subject": {
            "primary": primary, "focal_point": focal_point, "secondary": secondary, "props": props
        },
        "environment": {
            "location": location, "time_of_day": time_of_day, "atmosphere": atmosphere
        },
        "composition": {
            "rule": rule, "foreground": foreground, "midground": midground, "background": background,
            "safe_zone_for_overlay": "lower 20% of frame"
        },
        "lighting": {
            "key_light": key, "fill_light": fill, "rim_light": rim,
            "mood": light_mood, "shadow_quality": shadow
        },
        "style": {
            "film_stock": film_stock, "post_processing": post, "texture_detail": texture
        },
        "mood": {"emotion": emotion, "tension": tension},
        "symbolism": {"primary": sym_primary, "secondary": sym_secondary},
        "negative_as_positive": [
            "clean frame without visible text or watermarks",
            "photorealistic documentary cinematography, not illustrated or cartoon",
            "analog film photography aesthetic, no digital art flatness",
            "muted desaturated background palette, warm saturated foreground only",
            "tack-sharp focus on primary subject"
        ],
        "in_scene_text": ist,
        "api_call_hints": api_hints
    }


def main():
    count = 0
    for f in FRAMES:
        q = f[0]
        data = build_json(f)
        path = OUT / f"{q}.json"
        with path.open("w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=2)
        count += 1
    print(f"Gerados {count} JSONs em {OUT}")


if __name__ == "__main__":
    main()
