"""One-off: generate Q01-Q60 nano-banana JSONs for video-014-arrebatamento."""
import json
from pathlib import Path

OUT = Path(r"C:/Users/Leandro/Downloads/agencia/canais/sinais-do-fim/videos/video-014-arrebatamento/6-prompts-imagem")
OUT.mkdir(parents=True, exist_ok=True)

STYLE_REF = {
    "primary_image_url": "canais/sinais-do-fim/_config/style_refs/sinais_dark.png",
    "weight": 0.85,
    "transfer_targets": ["color_palette", "lighting", "texture", "atmosphere", "film_grain"],
    "textual_description": "dark cinematic chiaroscuro, Caravaggio-inspired, foreground in rich warm tones (crimson, amber, gold) with background in desaturated black-and-white, film grain, candlelight, floating orange embers"
}
NEG = [
    "clean frame without visible text or watermarks",
    "photorealistic documentary cinematography, not illustrated or cartoon",
    "analog film photography aesthetic, no digital art flatness",
    "muted desaturated background palette, warm saturated foreground only",
    "tack-sharp focus on primary subject"
]
STYLE_BLOCK = {
    "film_stock": "Kodak Portra 800 pushed two stops",
    "post_processing": "halation, crushed blacks, amber highlights, anamorphic lens flares",
    "texture_detail": "35mm film grain, dust particles, floating orange embers"
}

def hints(pro=False):
    h = {"multimodal_inputs": [
            {"type": "image", "source": "style_reference.primary_image_url", "role": "style_reference", "instruction": "Transfer color palette, lighting, grain, atmosphere only. Do not copy composition."},
            {"type": "text", "source": "serialized_prompt_from_this_json", "role": "scene_description"}
        ]}
    if pro:
        h = {"model_override": "pro", **h}
    return h

# (quadro, parte, ato, title, narrative_beat, shot_type, angle, fl, ap, dof, subj, focal, second, props_list, loc, tod, atm, rule, fg, mg, bg, key, fill, rim, mood_str, shadow, emotion, tension, sym_primary, sym_sec, narr, in_scene_enabled, in_scene_content, pro)
quadros = [
    # ========== PARTE 1 — GANCHO (Q01-Q12) ==========
    ("Q01", 1, "Gancho", "Abertura tela preta", "Tela preta absoluta com uma unica brasa laranja no centro-baixo se desfazendo",
     "black frame", "overhead implicit", 50, "f/2.8", "n/a",
     "an absolute black frame with a single orange ember particle dissolving at lower-center",
     "one glowing orange ember particle at screen center-bottom dissolving into smoke",
     "pure void blackness surrounds the ember, no other visible elements",
     ["single orange ember particle", "wisp of rising smoke"],
     "pure black void", "before dawn, cosmic silence", "ominous, suspended, pre-event dread",
     "minimalist single-point focus", "nothing but the glowing ember", "void blackness", "absolute black void",
     "no key light except the ember self-glow", "none", "none",
     "pre-apocalyptic silence", "pure blackness",
     "ominous, suspended", "high",
     "the single spark before revelation", "dying light of warning",
     "[silencio 2s + drone entra]",
     False, None, True),

    ("Q02", 1, "Gancho", "O pastor no pulpito", "Pregador arquetipico em pulpito, bracos erguidos, manto negro com gola bordo, rosto parcial na sombra",
     "medium", "frontal", 50, "f/2.8", "shallow",
     "an archetypal 50-year-old preacher at a dark wooden pulpit with raised arms",
     "the preacher's raised hands catching golden overhead light",
     "Black robe with deep burgundy collar, face partially in shadow hiding identity. Golden overhead beam isolates his silhouette.",
     ["dark wooden carved pulpit", "black clerical robe with burgundy collar", "open Bible on pulpit in warm amber"],
     "megachurch auditorium at night", "evening service under stage light", "manipulative charisma, theatrical",
     "rule of thirds", "preacher in rich crimson and gold tones, dramatic chiaroscuro",
     "pulpit with open Bible glowing warm amber", "desaturated black-and-white blurred crowd silhouettes in pews",
     "harsh warm top-down light from above-front", "faint amber bounce from open Bible",
     "gold rim along robe shoulders", "theatrical ominous",
     "deep hard-edged Caravaggio shadows",
     "manipulative, theatrical", "high",
     "false prophet archetype", "charismatic deception",
     "Em setembro de dois mil e vinte e cinco, um pastor sul-africano convenceu milhares de cristaos a venderem tudo.",
     False, None, False),

    ("Q03", 1, "Gancho", "A venda dos bens", "Overhead mesa com chaves, escritura, macos de dinheiro, mao assinando venda",
     "overhead", "overhead", 35, "f/4.0", "moderate",
     "a dark wooden table viewed from directly above with keys, deed papers, stacked cash, and a signing hand",
     "a hand signing a sale document in golden light",
     "Car keys on a brass ring, rolled deed document, bundles of banknotes, a fountain pen, all in warm vivid tones against a black background.",
     ["car keys on brass ring", "rolled deed document", "stacks of banknotes", "fountain pen"],
     "empty garage and living room combined", "midday cold light", "material renunciation",
     "centered symmetry", "objects in rich crimson and gold tones", "dark wood table grain",
     "desaturated black-and-white empty garage in far background",
     "overhead soft warm spotlight on the objects", "faint amber bounce",
     "gold edge along cash bundles", "transactional solemnity",
     "deep crushed blacks around edges",
     "renunciation, finality", "medium",
     "giving up the earthly in exchange for false promise", "the cost of deception",
     "Carros. Casas. Poupancas da vida inteira.",
     False, None, False),

    ("Q04", 1, "Gancho", "Porta destrancada", "Wide de porta de casa destrancada aberta a noite, interior vazio iluminado em dourado",
     "wide", "frontal low", 24, "f/5.6", "deep",
     "a suburban house front door left unlocked and slightly ajar at night",
     "the crack of warm golden light escaping from the empty interior",
     "Door hangs open showing empty hallway within, warm amber light spilling out contrasting the cold monochrome street outside.",
     ["wooden front door slightly ajar", "empty hallway visible", "floating embers in air"],
     "suburban street at 3 AM", "dead of night", "abandonment, absolute renunciation",
     "centered one-point perspective", "interior glowing in warm gold and amber", "threshold of door frame",
     "desaturated black-and-white empty street outside", "warm golden spill from interior",
     "cool blue ambient from street lamp", "warm gold rim on door frame",
     "abandonment eerie", "long stretched shadows",
     "eerie abandonment", "medium",
     "total surrender to a lie", "the empty home as monument to deception",
     "Um grupo deixou a porta da casa destrancada — porque nao ia mais precisar de casa.",
     False, None, False),

    ("Q05", 1, "Gancho", "O pastor sul-africano", "Close lateral silhueta parcial, microfone dourado em primeiro plano, rosto em sombra",
     "close-up", "3/4 side", 85, "f/2.0", "razor-thin",
     "a side-profile silhouette of a black man in elegant dark suit near a golden microphone",
     "a golden vintage broadcast microphone in sharp focus foreground",
     "Crimson velvet sleeve, face in deep shadow with only jaw and ear edge visible, golden microphone catches hard light.",
     ["vintage golden broadcast microphone", "crimson velvet suit sleeve", "dark shadow obscuring face"],
     "podcast studio", "late evening", "opaque identification, suspense",
     "foreground microphone dominance", "microphone and sleeve in rich gold and crimson",
     "dark shadow of head and shoulder", "desaturated black-and-white blurred congregation beyond",
     "single key light from below-front catching microphone", "none",
     "gold rim on microphone mesh", "conspiratorial",
     "deep crushed blacks hiding identity",
     "mysterious, suspicious", "high",
     "the man behind the false prophecy", "hidden identity amplified",
     "O nome dele e Joshua Mhlakela. E ele disse ter visto Jesus Cristo em pessoa.",
     False, None, False),

    ("Q06", 1, "Gancho", "A data cravada", "Close extremo de calendario antigo, dia 23 de setembro circulado em vermelho sangue",
     "extreme close-up", "frontal", 100, "f/2.8", "razor-thin",
     "an extreme macro of an old paper wall calendar with the 23rd of September circled in blood red",
     "the blood-red circle around the number 23 written with a trembling hand",
     "Vintage grayscale calendar page with September layout, the 23 encircled in thick crimson ink, fountain pen laying beside.",
     ["vintage paper calendar page", "blood-red ink circle around 23", "fallen fountain pen"],
     "dark wooden desk", "candlelight", "false prophetic marking",
     "center focus on circled date", "the red circle in vivid crimson ink",
     "grid of grayscale calendar numbers", "absolute black surrounding",
     "candlelight from lower-left casting raking shadow", "none",
     "warm amber rim around ink circle", "false marking of divine time",
     "harsh lateral candlelight",
     "ominous marking", "high",
     "human presumption over divine secrecy", "the date that would not come",
     "Vinte e tres de setembro de dois mil e vinte e cinco. O dia do arrebatamento da Igreja.",
     True, {"content": "SEP 23", "font": "vintage printed serif", "medium": "ink on paper", "placement": "center of frame, circled in red"}, True),

    ("Q07", 1, "Gancho", "Viralizacao TikTok", "Overhead de parede de celulares flutuantes em P&B conectados por linhas de fogo vermelho",
     "wide", "overhead 60", 24, "f/8.0", "deep",
     "an overhead view of dozens of floating smartphones arranged in grid formation",
     "the network of crimson fire-lines connecting the phones",
     "Black-and-white phones each showing a generic gold play triangle icon, crimson glowing filaments linking them in web pattern.",
     ["floating smartphones in grid", "gold play icons on screens", "crimson fire filaments connecting phones"],
     "abstract digital void", "no time", "viral contagion",
     "symmetrical grid", "crimson fire network in rich red and gold",
     "grid of phone screens in desaturated monochrome", "black digital void",
     "no single source — each phone emits own glow", "red ambient from the filaments",
     "gold rim on phone edges", "viral hysteria",
     "hard rim lighting from screen glows",
     "contagious panic", "high",
     "digital false prophecy spreading", "the network of deception",
     "A hashtag RaptureTok atingiu trezentos mil posts no TikTok em menos de duas semanas.",
     False, None, False),

    ("Q08", 1, "Gancho", "Lua de sangue sobre Brasil", "Wide de lua gigante carmesim, silhuetas de palmeiras em P&B abaixo",
     "wide", "frontal cosmic", 35, "f/4.0", "deep",
     "a massive crimson blood moon dominating the night sky over a Brazilian landscape",
     "the deep crimson orb of the moon hanging low",
     "Lush palm tree silhouettes in desaturated grayscale below the horizon, small coastal town lights faintly visible, crimson embers floating up.",
     ["giant blood-red moon", "palm tree silhouettes", "crimson floating embers"],
     "Brazilian coastal night sky", "10 PM", "astronomical omen",
     "lower horizon rule of thirds", "crimson moon and gold horizon in rich hues",
     "palm trees and distant town in grayscale", "deep indigo-black desaturated sky",
     "moon itself is the key light source", "ambient red from the moon",
     "crimson rim on palm fronds", "prophetic astronomical omen",
     "deep chiaroscuro from lunar light only",
     "cosmic foreboding", "high",
     "fulfillment of Joel's prophecy", "the sign in the heavens",
     "Sete de setembro: a Lua ficou vermelha sobre o Brasil.",
     False, None, False),

    ("Q09", 1, "Gancho", "Contagem regressiva", "Close-up relogio de bolso dourado pendurado, ponteiros em numeros romanos vermelhos",
     "close-up", "frontal", 85, "f/2.0", "shallow",
     "an antique golden pocket watch hanging from a chain against black backdrop",
     "the Roman numerals glowing warm red near the XII position",
     "Ornate gold engraved case, Roman numeral dial, minute hand slightly past XII, chain extending upward into darkness.",
     ["ornate gold pocket watch", "chain extending upward", "Roman numeral dial with red glow"],
     "pure black void", "frozen moment", "time running out",
     "centered hanging composition", "watch in vivid gold and red",
     "chain fading into black", "absolute black background",
     "harsh single key light from upper-left", "none",
     "gold edge rim on watch case", "inexorable countdown",
     "deep blacks, high contrast",
     "time pressure", "high",
     "human countdown toward false date", "chronological arrogance",
     "Doze dias depois: a data que o pastor havia cravado.",
     False, None, False),

    ("Q10", 1, "Gancho", "O dia que chegou", "Overhead de mesa vazia com calendario folhinha dia 23 SET rasgado ao meio",
     "overhead", "overhead 90", 35, "f/5.6", "moderate",
     "an overhead view of an empty wooden table with only a torn calendar page",
     "the ripped calendar page showing SEP 23 split diagonally",
     "The calendar page torn cleanly across the numbered date, a small brass cross fallen nearby, cold blue-grey light.",
     ["torn paper calendar page reading SEP 23", "fallen small brass cross", "empty table surface"],
     "empty wooden table", "overcast morning", "failure, emptiness",
     "diagonal torn paper focal", "torn edge with faint gold in the rip",
     "grayscale calendar grid", "desaturated wooden table background",
     "cold overcast window light", "none",
     "faint gold on cross edge", "cold empty failure",
     "soft flat shadowless",
     "desolate failure", "medium",
     "the non-event", "exposed deception",
     "O dia vinte e tres chegou. E o pastor sumiu.",
     True, {"content": "SEP 23", "font": "calendar serif", "medium": "torn paper", "placement": "center, ripped"}, False),

    ("Q11", 1, "Gancho", "Os arruinados", "Wide de familia silhuetas sentadas no chao de casa vazia, Biblia aberta no chao",
     "wide", "low frontal", 24, "f/5.6", "deep",
     "a family of indistinct silhouettes sitting on the floor of an empty home",
     "an open Bible on the floor glowing warm in the center of the frame",
     "Cardboard boxes scattered, bare walls, father figure head in hands, mother and child huddled beside, open Bible emitting soft gold light.",
     ["cardboard moving boxes", "open Bible glowing on bare floor", "huddled family silhouettes"],
     "empty stripped living room", "twilight", "desolation after deception",
     "low horizon rule of thirds", "open Bible in rich warm crimson and gold",
     "family silhouettes in warm low amber", "desaturated black-and-white bare walls and boxes",
     "warm glow from the Bible itself on floor", "cold blue ambient from uncovered window",
     "gold rim on Bible pages", "broken faith",
     "long diffuse shadows",
     "desolation, shattered faith", "high",
     "ruin after believing the lie", "faith surviving the deception",
     "Houve apenas pessoas arruinadas, com fe abalada, sem emprego, sem poupanca.",
     False, None, False),

    ("Q12", 1, "Gancho", "Mateus 24:36 iluminado", "Close extremo Biblia aberta em Mateus 24:36, feixe de luz dourada divina sobre o versiculo",
     "extreme close-up", "frontal", 100, "f/2.8", "razor-thin",
     "an extreme macro of an old leather-bound Bible open to Matthew chapter 24",
     "a vertical golden beam of divine light striking verse 36 specifically",
     "Aged parchment pages with Portuguese gothic script, verse 36 glowing with warm amber divine light, soft embers floating.",
     ["open leather Bible", "aged parchment pages", "vertical divine light beam", "floating amber embers"],
     "dark sacred interior", "pre-dawn", "revelation of the rule",
     "centered divine axis", "Bible page with glowing verse in vivid gold and cream",
     "leather cover edges in warm brown", "absolute black surrounding void",
     "vertical divine key light from above", "none — only the beam",
     "gold highlights on page edges", "sacred revelation",
     "hard-edged divine shadow outside beam",
     "reverent revelation", "high",
     "the rule that was broken", "divine secrecy",
     "Essa regra esta em Mateus, capitulo vinte e quatro, versiculo trinta e seis.",
     True, {"content": "Mt 24:36", "font": "aged serif Bible typeface", "medium": "ink on parchment", "placement": "lower portion of page, highlighted by golden beam"}, True),

    # ========== PARTE 2 — O VERSICULO QUE TODOS IGNORAM (Q13-Q24) ==========
    ("Q13", 2, "Versiculo", "Atril gotico Mateus 24", "Wide de Biblia monumental em atril gotico dentro de capela, feixe dourado sobre pagina aberta",
     "wide", "frontal symmetric", 35, "f/5.6", "deep",
     "a monumental Bible resting open on a gothic wooden lectern inside a vast cathedral",
     "the Bible pages catching a single vertical shaft of golden divine light",
     "Massive carved oak lectern, cathedral stone pillars in desaturated grayscale, stained glass above dim, the Bible a golden focal point.",
     ["monumental Bible", "carved gothic lectern", "single golden light shaft", "floating dust motes"],
     "abandoned gothic cathedral interior", "sunrise through stained glass", "canonical authority",
     "centered symmetry", "Bible and lectern in rich gold and warm amber",
     "gothic pillars fading into shadow", "desaturated grayscale cathedral depth",
     "vertical golden beam from clerestory", "ambient cool blue from shadows",
     "gold rim on lectern carvings", "reverent sacred",
     "deep architectural shadows",
     "sacred authority", "medium",
     "Word of God as throne", "canonical weight",
     "Mateus vinte e quatro, versiculo trinta e seis.",
     False, None, False),

    ("Q14", 2, "Versiculo", "Cristo falando", "Medium de figura de Cristo renascentista em veste branca-dourada, maos erguidas, halo leve",
     "medium", "frontal", 50, "f/2.8", "shallow",
     "a Renaissance-style figure of Christ in a long white and gold robe with raised hands",
     "Christ's serene face with a subtle golden halo emanating",
     "Flowing white linen robe with gold trim, hands palms-up at chest level, soft golden halo behind head, bearded ethereal expression.",
     ["white and gold linen robe", "subtle golden halo", "raised open hands"],
     "Mount of Olives overlook", "golden hour", "divine authority speaking",
     "centered figure rule of thirds", "Christ figure in vivid white, gold, crimson",
     "distant olive trees warm bronze", "desaturated black-and-white Jerusalem skyline below",
     "warm golden rim light from behind", "soft amber fill frontal",
     "gold halo backlight", "divine authority",
     "soft diffused halo glow",
     "divine solemnity", "medium",
     "Jesus as sole authority on the day and hour", "Christ declaring his own limitation",
     "Jesus falando. Nao Paulo. Nao Joao. Nao um profeta do Antigo Testamento.",
     False, None, True),

    ("Q15", 2, "Versiculo", "A Trindade", "Overhead de tres velas formando triangulo equilatero sobre altar de marmore",
     "overhead", "overhead 90", 35, "f/4.0", "moderate",
     "an overhead view of three lit candles on a white marble altar forming an equilateral triangle",
     "the central larger gold candle flame taller than the flanking crimson and white",
     "White Carrara marble altar surface, three beeswax candles of different colors and sizes, vertical light from above.",
     ["three lit candles (gold/crimson/white)", "white marble altar", "triangular arrangement"],
     "sacred abside interior", "midnight vigil", "trinitarian sacredness",
     "centered triangular composition", "three candle flames in vivid gold, crimson, white",
     "marble surface in muted ivory", "desaturated black-and-white abside architecture",
     "overhead vertical divine beam", "candle flames self-illuminate",
     "gold rim on wax surfaces", "trinitarian mystery",
     "soft triangular light pattern",
     "sacred mystery", "medium",
     "the Trinity where only the Father knows", "divine triune secrecy",
     "Jesus — o proprio filho de Deus, a segunda pessoa da Trindade.",
     False, None, False),

    ("Q16", 2, "Versiculo", "A citacao em pergaminho", "Close extremo pergaminho com texto 'NINGUEM sabe' em caligrafia dourada iluminada",
     "extreme close-up", "frontal", 100, "f/2.8", "razor-thin",
     "an extreme macro of an aged parchment scroll with calligraphic text in glowing gold",
     "the word NINGUEM (NO ONE) glowing brighter than surrounding text",
     "Portuguese calligraphy in gothic style, gold ink catching light, parchment fibers visible, quill pen laying beside.",
     ["aged parchment scroll", "golden calligraphy text", "quill pen laid beside"],
     "dark scriptorium desk", "candlelight", "textual revelation",
     "centered word emphasis", "glowing text in vivid gold",
     "parchment texture warm cream", "absolute black surrounding void",
     "candlelight lateral from lower-left", "none",
     "gold highlights on each letter", "textual absolute",
     "hard raking candlelight",
     "revelation absolute", "high",
     "the verse that ends all speculation", "textual finality",
     "'Mas acerca daquele dia e hora ninguem sabe, nem os anjos dos ceus, nem o Filho, senao o Pai.'",
     True, {"content": "NINGUEM SABE", "font": "gothic calligraphy", "medium": "gold ink on parchment", "placement": "center of frame, glowing"}, True),

    ("Q17", 2, "Versiculo", "Anjos com cabecas baixas", "Wide de coro de anjos medievais em vestes brancas e douradas, cabecas baixas e maos sobre olhos",
     "wide", "symmetric frontal", 24, "f/5.6", "deep",
     "a Renaissance-style choir of seven medieval angels in white and gold robes",
     "all angels with heads bowed and hands covering their eyes in gesture of unknowing",
     "Open detailed wings of varied feather colors, flowing white and cream robes with gold trim, lined symmetrically in cloudscape.",
     ["seven angels in robes", "open feathered wings", "hands over eyes", "golden halos"],
     "cosmic cloudscape", "eternal dawn", "angelic humility",
     "symmetric horizontal line", "angels in vivid white, gold, crimson accents",
     "clouds in warm amber", "desaturated grayscale far cosmos with faint stars",
     "warm golden light from above", "amber fill from below",
     "gold rim on wings", "humble sacred",
     "soft diffused clouds",
     "humble unknowing", "medium",
     "even angels do not know the day", "celestial humility",
     "Ninguem. Nem os anjos. Nem o Filho.",
     False, None, False),

    ("Q18", 2, "Versiculo", "Balanca medieval", "Medium simetrico de balanca de bronze com Cristo dourado em prato e lingua de serpente em outro",
     "medium", "frontal", 50, "f/4.0", "moderate",
     "a bronze medieval balance scale on a stone altar with two unequal pans",
     "the left pan holds a miniature gold Christ figurine, the right holds a crimson serpent tongue",
     "Patinated bronze scales, fine chain links, left pan weighted down by gold figurine, right pan elevated with crimson coiled serpent tongue.",
     ["bronze balance scale", "miniature gold Christ figurine", "coiled crimson serpent tongue"],
     "stone altar interior", "ritual candlelight", "moral dichotomy",
     "centered symmetry", "scale arms in rich bronze, figurine in gold, serpent in crimson",
     "stone altar base warm gray", "desaturated dark stone wall",
     "vertical key light overhead", "warm amber fill from below",
     "gold rim on Christ figurine", "moral judgment",
     "deep chiaroscuro",
     "theological dilemma", "high",
     "two options — Christ lying or pastor lying", "binary moral truth",
     "Ou Jesus mudou de posicao... ou o pastor esta mentindo. Nao existe uma terceira opcao.",
     False, None, False),

    ("Q19", 2, "Versiculo", "William Miller 1844", "Wide cinematografico de multidao do seculo XIX em colina, pregador central em sobrecasaca carmesim",
     "wide", "epic frontal", 35, "f/8.0", "deep",
     "a Renaissance-style wide shot of a 19th-century crowd gathered on a hillside at dawn",
     "the central preacher in a crimson frock coat holding an illuminated Bible skyward",
     "Crowd in black-and-white period dress looking upward at empty sky, central preacher standing on rock with Bible raised in gold light.",
     ["crowd in Victorian dress", "central preacher in crimson coat", "raised illuminated Bible", "empty sky"],
     "American rural hillside 1844", "dawn", "historical disappointment",
     "rule of thirds with preacher center", "preacher and Bible in vivid crimson and gold",
     "crowd silhouettes in warm mid-tones", "desaturated black-and-white dawn sky",
     "soft dawn light from horizon", "ambient cool blue from sky",
     "gold rim on Bible", "failed expectation",
     "long sunrise shadows",
     "collective false hope", "medium",
     "the Great Disappointment of 1844", "historical precedent of deception",
     "William Miller — Estados Unidos, mil oitocentos e quarenta e quatro. Convenceu cinquenta mil cristaos.",
     False, None, False),

    ("Q20", 2, "Versiculo", "Grande Desapontamento", "Overhead de jornais amarelados com manchetes apocalipticas e vela apagada sobre eles",
     "overhead", "overhead 75", 50, "f/4.0", "moderate",
     "an overhead view of five yellowed antique newspapers scattered on wooden floor",
     "a single extinguished beeswax candle laying on top with golden smoke rising",
     "Grayscale newspapers with apocalyptic headlines in old English type, the candle fallen diagonally, gold smoke curling up.",
     ["yellowed antique newspapers", "extinguished candle", "rising golden smoke"],
     "abandoned attic floor", "morning after", "historical documentation",
     "diagonal newspaper arrangement", "candle and smoke in warm gold",
     "newspaper pages in aged sepia", "desaturated wooden floor planks",
     "overhead soft light", "none",
     "warm amber on smoke tendrils", "documented failure",
     "soft diffuse shadows",
     "historical post-mortem", "low",
     "yesterday's false prophecy", "silence after the lie",
     "Ficou conhecido como 'O Grande Desapontamento'.",
     False, None, False),

    ("Q21", 2, "Versiculo", "Microfone de radio anos 90", "Close lateral de microfone de radio antigo em cores ricas, ondas sonoras vermelhas",
     "close-up", "3/4 side", 85, "f/2.8", "razor-thin",
     "a vintage 1990s broadcast microphone in gold and chrome",
     "the microphone with visible red sound waves emanating from the grille",
     "Chrome body with amber panel, foam windscreen missing, crimson sound waves radiating outward, dust particles visible.",
     ["vintage chrome broadcast microphone", "crimson sound wave rings", "floating dust particles"],
     "abandoned radio studio", "dusk", "obsolete transmission",
     "foreground microphone dominance", "microphone in vivid gold and chrome",
     "sound waves in rich crimson", "desaturated black-and-white empty chair behind",
     "single warm key from front", "cool blue ambient from back",
     "gold rim on chrome", "obsolete prophecy",
     "hard lateral raking light",
     "fallen transmission", "medium",
     "Harold Camping on dead radio waves", "voice of false prophecy",
     "Harold Camping — radio Gospel americano. Cravou o fim do mundo para setembro de mil novecentos e noventa e quatro.",
     False, None, False),

    ("Q22", 2, "Versiculo", "Whisenant 88 razoes", "Medium livro pequeno capa dourada envelhecida, numero 88 em dourado brilhante, po dourado caindo",
     "medium", "side 3/4", 60, "f/2.8", "shallow",
     "a medium shot of a small aged book with gold embossed cover resting atop a stack",
     "the gilt numerals 88 glowing brighter than surrounding cover",
     "Leather cover dog-eared, gold 88 in art-deco lettering, supporting stack of identical books in grayscale, gold dust falling from pages.",
     ["small leather book with gold 88", "stack of identical books", "falling gold dust"],
     "dusty bookseller counter", "window light afternoon", "bestseller deception",
     "diagonal book stack", "top book in rich gold and crimson", "lower stack in muted brown",
     "desaturated black-and-white bookshop interior", "side window key light",
     "none", "gold rim on book edges", "bestseller obsolescence",
     "medium contrast shadows",
     "commercial deception", "medium",
     "4.5 million false prophecies sold", "profit from deception",
     "Edgar Whisenant — publicou 'Oitenta e Oito Razoes Para o Arrebatamento'. Vendeu quatro milhoes e meio de copias.",
     True, {"content": "88", "font": "art-deco gilt", "medium": "gold embossing on leather", "placement": "center of book cover"}, False),

    ("Q23", 2, "Versiculo", "Galeria dos fracassos", "Wide de galeria gotica com dezenas de pergaminhos emoldurados, cada um com X vermelho queimado",
     "wide", "frontal symmetric", 24, "f/8.0", "deep",
     "a wide gothic museum gallery hallway with dozens of framed parchments in rows",
     "each parchment burned with a large blood-red X across its surface",
     "Vaulted gothic ceiling, marble floor, identical ornate frames in stone alcoves, every parchment bearing the crimson X mark.",
     ["framed parchments in rows", "crimson X burn marks", "marble floor", "gothic archways"],
     "abandoned gothic gallery", "dusk", "archive of failed prophecies",
     "one-point perspective", "crimson X marks in vivid blood red",
     "parchments in warm cream", "desaturated grayscale gothic architecture",
     "side lancet windows casting warm gold", "cool blue ambient from far end",
     "gold rim on frames", "accumulated failure",
     "long receding architectural shadows",
     "historical weight", "medium",
     "2000 years of failed date-setting", "archived deception",
     "Dois mil anos. Dezenas de datas. Zero acertos.",
     False, None, False),

    ("Q24", 2, "Versiculo", "Ladrao de noite", "Close dramatico mao encapuzada com chave mestra de ouro entrando em fechadura escura",
     "close-up", "macro tight", 85, "f/2.0", "razor-thin",
     "a cinematic close-up of a gloved hand holding an antique gold skeleton key entering a dark lock",
     "the gold key turning halfway into the keyhole",
     "Black leather glove, ornate gold skeleton key with intricate bow, heavy wooden door with tarnished iron escutcheon.",
     ["gloved hand", "ornate gold skeleton key", "dark wooden door lock"],
     "unlit corridor interior", "3 AM", "thief in the night",
     "foreground hand-and-key dominance", "key in vivid gold", "glove in deep crimson leather",
     "desaturated grayscale dark corridor beyond door", "door wood in warm brown shadow",
     "harsh single lateral key light", "none",
     "gold rim on key teeth", "stealth intrusion",
     "deep crushed blacks",
     "covert approach", "high",
     "the Lord coming as a thief in the night", "unannounced arrival",
     "Um ladrao nao avisa a hora que vai chegar. Esse e o ponto inteiro.",
     False, None, True),

    # ========== PARTE 3 — O QUE A BIBLIA REALMENTE DIZ (Q25-Q37) ==========
    ("Q25", 3, "Biblia realmente diz", "Anjo gigante com trombeta", "Wide de anjo medieval renascentista gigante com asas douradas abertas, trombeta em maos",
     "wide", "epic frontal", 24, "f/5.6", "deep",
     "a monumental Renaissance angel filling the frame with outstretched golden wings",
     "the long golden herald trumpet held vertically by the angel",
     "Flowing crimson and white robe with gold trim, feathered wings in amber and bronze tones, trumpet glowing gold.",
     ["monumental angel", "outstretched feathered wings", "golden herald trumpet", "flowing crimson robe"],
     "volumetric heavenly cloudscape", "eternal dawn", "angelic proclamation",
     "centered heroic composition", "angel in vivid crimson, gold, white",
     "feathered wings in warm bronze", "desaturated black-and-white cloudbank",
     "warm divine backlight behind wings", "amber fill from below",
     "gold rim on wing edges and trumpet", "heraldic majesty",
     "dramatic chiaroscuro wing shadows",
     "majestic annunciation", "medium",
     "biblical rapture without date speculation", "heralded truth",
     "O que a Biblia REALMENTE diz sobre o arrebatamento.",
     False, None, False),

    ("Q26", 3, "Biblia realmente diz", "Paulo escrevendo", "Medium de Paulo velho, manto carmesim, escrevendo em pergaminho a luz de vela em cela romana",
     "medium", "3/4 side", 50, "f/2.8", "shallow",
     "a medium shot of the elderly Apostle Paul writing on parchment by candlelight",
     "his weathered hand holding a quill pen poised above the parchment",
     "White beard, deep crimson hooded robe, hand with quill, iron chains on his ankle, parchment with partial text.",
     ["elderly Paul", "crimson hooded robe", "quill pen and parchment", "iron ankle chains"],
     "Roman prison cell", "night candlelight", "apostolic authorship",
     "rule of thirds with Paul center", "Paul in rich crimson and amber",
     "candlelight on table warm", "desaturated grayscale stone cell walls",
     "single candle lateral from right", "none",
     "gold rim on forehead and quill", "apostolic solemnity",
     "deep raking candlelight shadows",
     "reverent authorship", "medium",
     "Paul writing to Thessalonica about the rapture", "scripture being born",
     "Primeira Epistola aos Tessalonicenses, capitulo quatro. Paulo escrevendo para a Igreja de Tessalonica.",
     False, None, False),

    ("Q27", 3, "Biblia realmente diz", "Cristo descendo das nuvens", "Wide dramatico de Cristo descendo em nuvens rasgadas de luz dourada, manto branco esvoacando",
     "wide", "low heroic", 24, "f/5.6", "deep",
     "a wide epic shot of Christ descending through torn clouds in golden light",
     "Christ with open arms emerging from a vertical rift of divine light",
     "Flowing white and gold robe caught mid-air, arms outstretched, clouds parted in rays of amber, golden particles ascending.",
     ["descending Christ figure", "white flowing robe", "torn cloudscape", "ascending gold particles"],
     "cosmic cloudscape", "apocalyptic sunrise", "second coming",
     "vertical divine axis", "Christ in vivid white and gold", "clouds in warm amber",
     "desaturated grayscale distant cloudbanks", "divine vertical beam from above",
     "warm amber fill from parted clouds", "gold rim on robe edges",
     "apocalyptic epiphany", "dramatic god-rays",
     "epiphanic glory", "high",
     "1 Thessalonians 4:16 made visible", "the Lord himself descending",
     "'O proprio Senhor descera do ceu com alarido, com voz de arcanjo.'",
     False, None, True),

    ("Q28", 3, "Biblia realmente diz", "Alarido cosmico", "Close extremo de boca de arcanjo em grito, ondas sonoras douradas distorcendo ar",
     "extreme close-up", "frontal", 100, "f/2.0", "razor-thin",
     "an extreme macro of an archangel's open mouth mid-shout",
     "visible golden sound waves distorting the air in concentric rings",
     "Parted lips, hint of golden teeth and tongue, fierce beard hair at edges, concentric sonic wave rings radiating.",
     ["open angelic mouth", "golden sonic waves", "distorted air ripples"],
     "pure black void", "instant of proclamation", "sonic divine shout",
     "centered mouth with radial waves", "mouth in vivid gold and crimson",
     "sonic waves in warm amber", "absolute black void",
     "internal mouth light", "none",
     "gold rim on lip edge", "cosmic vocalization",
     "hard interior glow",
     "explosive proclamation", "high",
     "the shout that signals the rapture", "audible divine command",
     "Alarido. Uma declaracao sonora — nao um evento silencioso ou secreto.",
     False, None, False),

    ("Q29", 3, "Biblia realmente diz", "Arcanjo Miguel", "Medium de arcanjo Miguel em armadura dourada, espada flamejante em riste, asas abertas",
     "medium", "frontal heroic", 35, "f/4.0", "moderate",
     "a medium heroic shot of Archangel Michael in gilded armor with raised flaming sword",
     "the flaming sword in his right hand with golden fire",
     "Ornate gold breastplate and greaves, feathered wings spread wide, fierce expression, crimson cape behind.",
     ["Michael in gold armor", "flaming golden sword", "outstretched wings", "crimson cape"],
     "cosmic battlefield", "eternal twilight", "angelic majesty",
     "centered heroic", "Michael in vivid gold and crimson",
     "wings in warm amber", "desaturated grayscale starfield and distant nebulae",
     "warm backlight from behind wings", "amber fill frontal",
     "gold rim on armor edges", "warrior archangel",
     "dramatic heroic chiaroscuro",
     "celestial majesty", "medium",
     "the voice of the archangel", "heavenly commander",
     "Voz de arcanjo. Uma voz sobrenatural que todo o universo vai ouvir.",
     False, None, False),

    ("Q30", 3, "Biblia realmente diz", "Trombeta de Deus", "Close macro de trombeta dourada monumental soprada, ar vibrando",
     "close-up", "macro frontal", 85, "f/2.8", "razor-thin",
     "a close-up macro of a massive golden herald trumpet being blown",
     "the gold mouth of the trumpet with visible air vibrations",
     "Ornately engraved gold bell of trumpet, mouth wide open, visible heat-ripple distortion at opening, suggestion of embossed cherubim.",
     ["monumental golden trumpet bell", "visible air vibrations", "engraved cherubim"],
     "cosmic backdrop", "moment of summons", "divine summons",
     "center trumpet bell dominance", "trumpet in vivid aged gold",
     "air vibrations in warm amber", "desaturated grayscale silhouetted angelic army beyond",
     "warm backlight from within trumpet", "amber ambient",
     "gold rim on engravings", "military summons",
     "deep lateral shadows",
     "sacred summons", "high",
     "the trumpet of God gathering the elect", "divine roll-call",
     "Trombeta de Deus. O sinal de convocacao de um exercito.",
     False, None, False),

    ("Q31", 3, "Biblia realmente diz", "Mortos ressuscitando", "Wide de cemiterio com sepulturas abertas em fogo dourado, figuras envoltas em mantos saindo",
     "wide", "epic frontal", 24, "f/5.6", "deep",
     "a wide epic shot of a gothic cemetery with tombs bursting open in golden fire",
     "multiple white-robed figures rising from graves with raised arms",
     "Ornate tombstones toppled and open, golden flames spiraling upward, robed figures in various poses of awakening, rising gold particles.",
     ["broken gothic tombstones", "golden flames from graves", "robed resurrected figures", "rising embers"],
     "gothic cemetery at resurrection moment", "apocalyptic sunrise", "resurrection glory",
     "horizontal grave line across frame", "flames and figures in vivid gold and cream",
     "tombstones in warm gray", "desaturated grayscale distant necropolis and sky",
     "vertical golden column from each grave", "ambient amber wash",
     "gold rim on rising figures", "resurrection triumph",
     "intense chiaroscuro",
     "glorious resurrection", "high",
     "the dead in Christ rising first", "first fruits of the rapture",
     "Os mortos em Cristo ressuscitando primeiro. Corpos saindo das covas.",
     False, None, True),

    ("Q32", 3, "Biblia realmente diz", "Vivos arrebatados", "Wide cinematografico de multiplas silhuetas humanas subindo em espirais de luz dourada",
     "wide", "low upward", 24, "f/5.6", "deep",
     "a wide low-angle shot of dozens of human silhouettes lifted ascending in golden spirals of light",
     "the central figure in silhouette with arms raised mid-ascension",
     "Silhouettes in various poses of surprise and surrender, caught in golden vortex spirals, clouds torn open above.",
     ["ascending human silhouettes", "golden light spirals", "torn clouds above", "rising gold particles"],
     "modern city viewed from above", "mid-afternoon", "living caught up together",
     "vertical ascent composition", "ascension spirals in vivid gold and amber",
     "clouds in warm cream", "desaturated grayscale modern cityscape below",
     "vertical key light from torn sky", "ambient amber glow",
     "gold rim on figures", "euphoric ascent",
     "dramatic vertical chiaroscuro",
     "rapturous elevation", "high",
     "the living caught up with the dead", "gathering of the saints",
     "Depois — os vivos sendo arrebatados nas nuvens.",
     False, None, False),

    ("Q33", 3, "Biblia realmente diz", "Terra com pontos dourados", "Overhead cosmico do planeta Terra iluminado com pontos dourados ascendentes",
     "wide", "cosmic overhead", 35, "f/8.0", "deep",
     "a cosmic overhead view of planet Earth with golden points of light rising globally",
     "hundreds of golden ascending light trails emerging from continents",
     "Earth photorealistic with recognizable continents, glowing gold specks leaving atmosphere, faint aurora, deep space beyond.",
     ["planet Earth from space", "golden ascending light points", "faint aurora halo"],
     "low Earth orbit perspective", "day-night terminator", "planetary event",
     "centered spherical Earth", "gold light points in vivid amber",
     "atmosphere glow in warm ember", "desaturated grayscale deep space and nebulae",
     "sun backlight from edge of frame", "ambient blue from space",
     "gold rim on cloud tops", "planetary phenomenon",
     "soft planetary terminator",
     "cosmic scale", "medium",
     "rapture visible from orbit", "planetary divine event",
     "Isso nao e metafora. E a descricao de um evento fisico, audivel, visivel, global.",
     False, None, False),

    ("Q34", 3, "Biblia realmente diz", "Arca de Noe", "Medium de arca monumental em madeira dourada sobre colina, Noe entrando pela rampa",
     "medium", "epic frontal", 35, "f/5.6", "deep",
     "a medium epic shot of the monumental wooden Ark of Noah on a hillside",
     "Noah at the boarding ramp in crimson robe with a raised staff",
     "Massive wooden hull with pitched roof, gold-grained timber, Noah in red-ochre robe, pairs of animals silhouetted inside.",
     ["monumental wooden ark", "Noah in crimson robe", "boarding ramp", "animal silhouettes"],
     "pre-flood hillside", "late afternoon gathering storm", "pre-flood normality",
     "rule of thirds ark left", "ark and Noah in vivid gold and crimson",
     "hillside grass in warm ochre", "desaturated grayscale feasting crowd distant",
     "golden side sunlight", "storm-cloud blue ambient",
     "gold rim on ark timbers", "pre-cataclysm",
     "dramatic storm-front lighting",
     "solemn preparation", "medium",
     "as in the days of Noah", "chosen preparation",
     "'Como foi nos dias de Noe, assim tambem sera nos dias do Filho do Homem.'",
     False, None, False),

    ("Q35", 3, "Biblia realmente diz", "Banquete inconsciente", "Wide de cena de festa renascentista em cores ricas, tsunami gigante P&B ao fundo",
     "wide", "symmetric", 24, "f/5.6", "deep",
     "a wide Renaissance-style feast scene with rich warm tones",
     "the unaware feasters raising goblets in the center foreground",
     "Long banquet table with wine, bread, fruit, revelers in period dress, musicians playing — all oblivious to the massive grayscale tsunami wall behind.",
     ["feasting revelers", "banquet table with wine and bread", "massive tsunami wall behind", "unnoticed threat"],
     "ancient feast hall open to sky", "golden hour", "oblivious normalcy",
     "horizontal table with rising wave", "feast in vivid crimson, gold, amber",
     "table linen in warm cream", "desaturated grayscale looming tsunami wall",
     "warm side sunlight on feast", "cold blue ambient from tsunami",
     "gold rim on goblets and bread", "oblivious tragedy",
     "dramatic warm-cold contrast",
     "tragic obliviousness", "high",
     "eating and drinking until the flood", "unawareness of impending judgment",
     "Comiam, bebiam, casavam-se... normalidade ate o ultimo segundo.",
     False, None, True),

    ("Q36", 3, "Biblia realmente diz", "Espelho antigo", "Close de espelho antigo moldura dourada refletindo silhueta em sombra",
     "close-up", "frontal", 85, "f/2.8", "shallow",
     "a close-up of an ornate gilded antique mirror reflecting a shadowy silhouette",
     "the blurred silhouette of a viewer reflected in the mirror center",
     "Baroque gold frame with carved cherubs, mirror glass with tarnished edges, silhouette indistinct suggesting any viewer.",
     ["ornate gilded baroque mirror", "tarnished mirror glass", "ambiguous silhouette"],
     "empty dim bedroom", "candlelight", "self-confrontation",
     "centered mirror", "gold frame in vivid warm amber",
     "silhouette in dark ochre", "desaturated grayscale empty room behind",
     "candlelight lateral", "none",
     "gold rim on frame carvings", "existential interrogation",
     "deep raking candlelight",
     "interior reckoning", "medium",
     "are you ready for the rapture?", "self-examination",
     "Se o arrebatamento fosse amanha de manha — voce estaria pronto?",
     False, None, True),

    ("Q37", 3, "Biblia realmente diz", "Caminho bifurcado", "Overhead pergaminho com caminho bifurcado dourado e sombra carmesim",
     "overhead", "overhead 90", 50, "f/4.0", "moderate",
     "an overhead view of an aged parchment map with a forked path illustrated",
     "one branch in glowing gold, the other in crimson shadow",
     "Hand-drawn illustration in calligraphy, path branches at center — left path in gold leaf, right in blood crimson fading to black.",
     ["aged parchment map", "gold-illuminated path", "crimson shadow path"],
     "scriptorium desk", "candlelight", "existential choice",
     "centered bifurcation", "paths in vivid gold and crimson",
     "parchment in warm cream", "absolute black void beyond",
     "candlelight lateral", "none",
     "gold edge on illumination", "choice made or avoided",
     "raking parchment shadow",
     "moral fork", "high",
     "the decision you have or have not made", "binary destiny",
     "Para uma decisao que voce ja tomou — ou nao tomou.",
     False, None, False),

    # ========== PARTE 4 — OS SINAIS SAO REAIS (Q38-Q50) ==========
    ("Q38", 4, "Sinais reais", "Rolo pergaminho com simbolos", "Wide de pergaminho desenrolando-se com simbolos apocalipticos dourados",
     "wide", "frontal symmetric", 24, "f/5.6", "deep",
     "a wide shot of an aged parchment scroll unfurling in mid-air",
     "the illuminated apocalyptic symbols glowing gold on the scroll surface",
     "Scroll unfurling diagonally, symbols of darkened sun, blood moon, falling stars, crown — all in gold leaf on parchment.",
     ["unfurling parchment scroll", "gold apocalyptic symbols", "darkened sun icon", "blood moon icon"],
     "cosmic darkness", "no time", "prophetic enumeration",
     "diagonal scroll composition", "scroll symbols in vivid gold",
     "parchment in warm cream", "desaturated grayscale cosmos with faint stars",
     "vertical divine key light", "ambient amber",
     "gold rim on scroll edges", "prophetic revelation",
     "deep cosmic shadow",
     "prophetic gravity", "medium",
     "the signs Jesus listed in Matthew 24", "biblical enumeration",
     "A Biblia fala em sinais. Jesus passou um capitulo inteiro listando sinais.",
     False, None, False),

    ("Q39", 4, "Sinais reais", "Bussola dourada", "Medium overhead de bussola antiga apontando para horizonte, agulha em chama",
     "medium", "overhead 60", 50, "f/4.0", "moderate",
     "a medium overhead shot of an antique golden brass compass on an old maritime map",
     "the compass needle is a living flame pointing toward the map horizon",
     "Ornate brass compass with engraved rose, needle replaced with living flame, aged map in warm sepia.",
     ["antique brass compass", "flame-shaped needle", "aged maritime map"],
     "navigation desk", "dusk candlelight", "directional prophecy",
     "overhead centered compass", "compass and flame in vivid gold and crimson",
     "map in warm sepia", "desaturated grayscale wood grain edges",
     "warm overhead candlelight", "none",
     "gold rim on compass housing", "prophetic direction",
     "soft golden diffusion",
     "navigational truth", "medium",
     "signs point to a direction, not a date", "biblical orientation",
     "Sinais apontam para uma direcao. Nao marcam uma data.",
     False, None, False),

    ("Q40", 4, "Sinais reais", "Lua vermelha Brasil", "Wide panoramico de lua carmesim monstruosa sobre paisagem brasileira P&B",
     "wide", "static horizon", 35, "f/5.6", "deep",
     "a wide panoramic shot of a monstrous crimson moon hanging over a Brazilian coastal nightscape",
     "the massive crimson lunar disc dominating upper frame",
     "Crimson lunar surface with craters visible, palm silhouettes lower, low coastal houses, floating red ember particles.",
     ["enormous crimson moon", "palm tree silhouettes", "coastal town lights", "red ember particles"],
     "Brazilian coastline at night", "10 PM September 7 2025", "astronomical sign",
     "rule of thirds horizon low", "crimson moon in vivid blood red",
     "palms in warm ochre silhouette", "desaturated grayscale coastal distance",
     "moon itself as key light", "crimson ambient",
     "crimson rim on fronds", "cosmic omen",
     "dramatic lunar-only lighting",
     "prophetic astronomy", "high",
     "September 7, 2025 blood moon over Brazil", "Joel 2:31 fulfilled",
     "Sete de setembro de dois mil e vinte e cinco. A Lua ficou vermelha no ceu do Brasil.",
     False, None, False),

    ("Q41", 4, "Sinais reais", "Joel 2:31 iluminado", "Close macro Biblia aberta em Joel 2, feixe de luz dourada sobre versiculo 31",
     "extreme close-up", "frontal", 100, "f/2.8", "razor-thin",
     "an extreme macro of a leather Bible open to the book of Joel chapter 2",
     "a focused vertical golden beam striking verse 31 in highlighted illumination",
     "Aged parchment with Portuguese gothic script, verse 31 glowing amber, floating embers around.",
     ["open leather Bible at Joel 2", "golden light beam", "floating embers"],
     "sacred interior", "candle hour", "prophetic confirmation",
     "centered divine axis", "highlighted verse in vivid gold",
     "parchment in warm cream", "absolute black void surrounding",
     "vertical divine key from above", "none",
     "gold rim on page edges", "textual prophetic confirmation",
     "hard-edged divine shadow",
     "biblical prophetic authority", "high",
     "Joel 2:31 predicting the blood moon", "prophecy made text",
     "Joel dois e trinta e um: 'O sol se convertera em trevas, e a lua em sangue.'",
     True, {"content": "Joel 2:31", "font": "aged serif Bible", "medium": "ink on parchment", "placement": "lower page, golden beam highlighted"}, False),

    ("Q42", 4, "Sinais reais", "Relogio do Juizo Final", "Wide dramatico de relogio gigante de parede, ponteiro 85s para meia-noite, luz vermelha pulsante",
     "wide", "centered", 35, "f/5.6", "deep",
     "a wide dramatic shot of a massive classical wall clock with Roman numerals",
     "the minute hand at 85 seconds to midnight pulsing red",
     "Aged brass and dark wood clock, Roman numerals glowing amber, pulsing red around hand, pendulum still.",
     ["massive classical wall clock", "Roman numeral dial", "red pulsing minute hand"],
     "government research hall interior", "late night", "scientific apocalypse countdown",
     "centered clock face", "clock dial in vivid gold", "red pulse in blood crimson",
     "wood frame in warm brown", "desaturated grayscale distant mushroom cloud",
     "red pulsing key light around hand", "cool blue ambient",
     "gold rim on numerals", "terminal urgency",
     "hard pulsing shadows",
     "scientific omen", "high",
     "Doomsday Clock at 85 seconds", "verifiable countdown",
     "O Relogio do Juizo Final... esta em oitenta e cinco segundos para a meia-noite.",
     True, {"content": "85 SEC", "font": "thin modern sans", "medium": "electronic display near clock", "placement": "lower rim of clock face"}, True),

    ("Q43", 4, "Sinais reais", "2 Timoteo 3 com icones", "Overhead Biblia aberta em 2 Timoteo 3, icones modernos flutuando em P&B ao redor",
     "overhead", "overhead 75", 50, "f/4.0", "moderate",
     "an overhead shot of an open Bible at 2 Timothy 3",
     "modern icons (phone, coin, mirror, broken heart) floating in grayscale around the page",
     "Bible pages in warm cream, gothic script, grayscale modern symbols orbiting: smartphone, coin, mirror, broken heart.",
     ["open Bible at 2 Timothy 3", "floating modern icons in grayscale", "smartphone icon", "broken heart icon"],
     "scriptorium overhead", "candlelight", "contemporary diagnosis",
     "radial arrangement around book", "book in vivid warm cream", "icons in grayscale",
     "wood desk in warm brown", "absolute black surrounding",
     "overhead soft warm light", "none",
     "gold rim on page edges", "spiritual diagnosis",
     "soft flat overhead",
     "prophetic diagnosis", "medium",
     "2 Timothy 3 describing our age", "ancient text as modern mirror",
     "Segunda Timoteo tres: 'Nos ultimos dias sobrevirao tempos trabalhosos.'",
     False, None, False),

    ("Q44", 4, "Sinais reais", "Parede de celulares vicio", "Wide de parede de celulares P&B com chamas carmesim subindo entre eles",
     "wide", "frontal symmetric", 24, "f/8.0", "deep",
     "a wide grid of modern smartphones arranged like an iconostasis wall",
     "crimson flames rising between the phones like a burning wall",
     "Grid of grayscale phones each showing selfies/ego/pride icons, crimson flames rising vertically between rows.",
     ["grid of grayscale smartphones", "selfie and ego icons", "crimson flames rising"],
     "dark architectural void", "no time", "contemporary spiritual diagnosis",
     "symmetrical grid with flame verticals", "crimson flames in vivid blood red",
     "phones in desaturated grayscale", "absolute black void",
     "flames self-illuminate", "none",
     "crimson rim on phone edges", "modern idolatry",
     "dramatic crimson chiaroscuro",
     "digital pride embodied", "high",
     "2 Timothy 3 in today's feed", "contemporary idolatry",
     "Hoje ele parece o feed de qualquer rede social.",
     False, None, False),

    ("Q45", 4, "Sinais reais", "Tres silhuetas guerreiras", "Wide de tres silhuetas de costas com espadas flamejantes em ouro-vermelho",
     "wide", "symmetric frontal", 35, "f/5.6", "deep",
     "a wide symmetric shot of three silhouetted figures standing back-to-back",
     "each holding a raised flaming sword in gold and crimson",
     "One in Western suit, one in Eastern uniform, one in Slavic military coat — all in deep grayscale silhouette — swords held aloft glowing.",
     ["three silhouetted figures", "flaming golden swords", "back-to-back stance"],
     "cracked world map backdrop", "twilight", "geopolitical conflict",
     "triangular stance symmetry", "swords in vivid gold and crimson",
     "figures in warm charcoal", "desaturated grayscale world map",
     "flame light from swords", "cool blue ambient",
     "gold rim on sword blades", "nation against nation",
     "crimson raking light",
     "apocalyptic war", "high",
     "nation against nation, kingdom against kingdom", "geopolitical signs",
     "'Levanta-se nacao contra nacao, e reino contra reino.'",
     False, None, True),

    ("Q46", 4, "Sinais reais", "Tanque em campo devastado", "Medium de tanque de guerra P&B sobre campo, pergaminho profetico sobreposto em cores ricas",
     "medium", "frontal", 35, "f/5.6", "deep",
     "a medium shot of a modern battle tank in grayscale on a devastated field",
     "an aged prophetic parchment superimposed in warm gold tones in the foreground",
     "Tank in desaturated grayscale with smoke rising, parchment in foreground with Portuguese gothic text, embers.",
     ["battle tank in grayscale", "foreground prophetic parchment", "rising smoke", "floating embers"],
     "devastated battlefield", "dusk smoke", "contemporary war",
     "layered foreground-background", "parchment in vivid gold",
     "tank in warm charcoal", "desaturated grayscale field and smoke",
     "warm golden overlay light", "cool blue ambient",
     "gold rim on parchment edges", "prophecy meeting war",
     "deep smoke-filled chiaroscuro",
     "current conflict", "high",
     "Russia vs Ukraine, Israel vs Hamas", "present-tense prophecy",
     "Russia contra Ucrania. Israel contra Hamas, Hezbollah, Ira.",
     False, None, False),

    ("Q47", 4, "Sinais reais", "Tigela vazia e mascaras", "Overhead de mesa com tigela ceramica com farinha dourada, mascaras cirurgicas P&B ao redor",
     "overhead", "overhead 90", 50, "f/4.0", "moderate",
     "an overhead view of a bare wooden table with a ceramic bowl containing only golden flour",
     "the bowl centered with scattered grayscale surgical masks around it",
     "Earth-tone ceramic bowl, small amount of golden flour, surgical masks in grayscale scattered, cracked breadboard beside.",
     ["ceramic bowl with golden flour", "scattered surgical masks", "cracked breadboard"],
     "empty kitchen table", "cold morning light", "scarcity and plague",
     "centered bowl composition", "bowl and flour in vivid amber and ochre",
     "breadboard in warm brown", "desaturated grayscale masks and table edges",
     "overhead cool window light", "none",
     "gold rim on bowl edge", "famine and pandemic",
     "soft cold shadows",
     "shortage and plague", "medium",
     "global famine and COVID pandemic", "contemporary signs of plague",
     "A maior crise alimentar global em decadas. COVID — a maior pandemia em cem anos.",
     False, None, False),

    ("Q48", 4, "Sinais reais", "Rachadura com magma", "Wide de rachadura gigante no solo urbano P&B, magma dourado-carmesim emergindo",
     "wide", "low dramatic", 24, "f/5.6", "deep",
     "a wide low-angle shot of a massive fissure splitting a modern city street",
     "molten magma in gold and crimson emerging from the earth fissure",
     "Asphalt street cracked open, magma glowing orange-gold in depths, grayscale skyscrapers crumbling in background, floating embers.",
     ["massive ground fissure", "glowing magma", "crumbling grayscale skyscrapers", "embers"],
     "modern city street", "twilight quake", "geological catastrophe",
     "diagonal crack composition", "magma in vivid gold-crimson",
     "asphalt edges in warm ochre", "desaturated grayscale skyscrapers and smoke",
     "magma as key light from ground", "cool blue ambient",
     "gold rim on crack edges", "earth opening",
     "dramatic upward chiaroscuro",
     "telluric catastrophe", "high",
     "earthquakes in Morocco Japan Turkey", "seismic signs",
     "Terremotos no Marrocos, no Japao, na Turquia.",
     False, None, False),

    ("Q49", 4, "Sinais reais", "Janela gotica aberta", "Medium de janela gotica em vitral dourado-carmesim aberta sobre ceu tempestuoso",
     "medium", "frontal", 50, "f/4.0", "moderate",
     "a medium frontal shot of a gothic stained-glass window in gold and crimson hanging open",
     "the wind catching billowing curtains as storm clouds swirl beyond",
     "Lead-lined stained glass panels in vivid colors, crimson velvet curtains blowing inward, stormy grayscale sky visible beyond.",
     ["gothic stained-glass window", "crimson velvet curtains", "stormy sky beyond"],
     "ancient cathedral chamber", "storm building", "imminent proximity",
     "centered window frame", "stained glass in vivid gold and crimson",
     "curtains in warm crimson", "desaturated grayscale storm sky",
     "storm-lightning fill ambient", "warm amber backlight from chamber interior",
     "gold rim on lead lines", "open window of time",
     "dramatic storm chiaroscuro",
     "imminent storm", "medium",
     "the window is open, the hour is God's", "proximity without date",
     "A janela esta aberta. So a hora — essa, so o Pai sabe.",
     False, None, False),

    ("Q50", 4, "Sinais reais", "Ampulheta quase vazia", "Close extremo ampulheta dourada, areia quase toda embaixo, ultimos graos caindo",
     "extreme close-up", "macro frontal", 100, "f/2.8", "razor-thin",
     "an extreme macro of a golden hourglass with almost all sand in the lower bulb",
     "the final few grains of sand falling through the narrow waist",
     "Ornate gold frame hourglass, upper bulb nearly empty, narrow stream of grains falling, lower bulb almost full of amber sand.",
     ["ornate gold hourglass", "falling amber sand", "polished gold frame"],
     "sacred altar", "candle hour", "last moments",
     "centered hourglass", "hourglass in vivid gold", "sand in warm amber",
     "pedestal in warm bronze", "absolute black void",
     "single lateral key light", "none",
     "gold rim on frame edges", "time almost gone",
     "deep macro shadows",
     "terminal temporality", "high",
     "proximity is real, only the when is uncertain", "imminence",
     "A proximidade e real. A imprecisao e sobre o quando. Nao sobre o se.",
     False, None, True),

    # ========== PARTE 5 — URGENCIA REAL + CTA (Q51-Q60) ==========
    ("Q51", 5, "CTA", "Armadilha medieval", "Wide de armadilha de bronze aberta no chao, iscada com calendario dourado brilhante",
     "wide", "low frontal", 24, "f/5.6", "deep",
     "a wide low-angle shot of a medieval bronze bear-trap open on a stone floor",
     "the baited calendar in glowing gold at the center of the trap jaws",
     "Serrated bronze trap with iron teeth open wide, bait is a gold-illuminated calendar page, stone cavern surround.",
     ["open medieval bronze trap", "gold-illuminated calendar bait", "serrated iron teeth"],
     "stone cavern floor", "torchlight", "spiritual snare",
     "centered trap dominance", "trap and bait in vivid bronze and gold",
     "stone floor in warm gray", "desaturated grayscale dark cavern walls",
     "torch key light from upper left", "cool blue ambient from cave depth",
     "gold rim on trap teeth", "date-setting as spiritual trap",
     "hard raking light",
     "warning snare", "medium",
     "obsession with dates is a trap", "spiritual snare exposed",
     "A obsessao com datas e uma armadilha.",
     False, None, False),

    ("Q52", 5, "CTA", "Calendario vs coracao", "Split: esquerda calendario com dias marcados vermelho, direita coracao anatomico P&B pulsando",
     "wide", "split symmetric", 35, "f/5.6", "moderate",
     "a wide split-screen composition with calendar on left and anatomical heart on right",
     "a thin golden thread of light connecting the two across the split",
     "Left side: huge calendar with days crossed out in blood red, rich warm tones. Right side: anatomical human heart in grayscale, softly pulsing.",
     ["huge calendar with crossed days", "grayscale anatomical heart", "golden connecting thread"],
     "abstract split space", "no time", "soul vs date",
     "vertical split composition", "calendar in vivid crimson and gold",
     "heart in desaturated grayscale", "absolute black void center",
     "warm side light on calendar", "cold faint pulse on heart",
     "gold rim on golden thread", "spiritual priorities",
     "dramatic side chiaroscuro",
     "moral dichotomy", "high",
     "what really matters is the soul", "spiritual redirection",
     "Voce para de olhar para o que realmente importa — o estado da sua propria alma.",
     False, None, False),

    ("Q53", 5, "CTA", "Mateus 24:42 iluminado", "Close Biblia aberta em Mateus 24:42, feixe dourado sobre versiculo 42, pena de escrita ao lado",
     "extreme close-up", "frontal", 100, "f/2.8", "razor-thin",
     "an extreme macro of an open Bible at Matthew chapter 24",
     "a vertical golden divine beam striking verse 42 specifically",
     "Aged parchment pages, gothic Portuguese script, verse 42 glowing bright gold, quill pen resting beside.",
     ["open Bible at Matthew 24", "glowing verse 42", "quill pen"],
     "sacred reading desk", "pre-dawn", "direct command",
     "centered divine axis", "verse in vivid gold",
     "pages in warm cream", "absolute black surrounding",
     "vertical divine key from above", "none",
     "gold rim on page edges", "Christ's direct command",
     "hard divine shadow",
     "commanding revelation", "high",
     "Jesus saying 'watch'", "divine command",
     "Mateus vinte e quatro, versiculo quarenta e dois: 'Velai, pois, porque nao sabeis a que hora ha de vir o vosso Senhor.'",
     True, {"content": "Mt 24:42", "font": "aged serif Bible", "medium": "ink on parchment", "placement": "lower page with golden beam"}, True),

    ("Q54", 5, "CTA", "Sentinela medieval", "Medium de sentinela com lamparina dourada em torre, olhando para horizonte noturno",
     "medium", "3/4 profile", 50, "f/2.8", "shallow",
     "a medium three-quarter shot of a medieval watchman on a stone tower",
     "the golden oil lantern held outward into the night",
     "Crimson hooded cloak, bronze chestplate, golden oil lantern, face in partial shadow looking toward horizon, stone battlements.",
     ["medieval watchman", "crimson cloak", "golden oil lantern", "stone battlements"],
     "castle watchtower", "dead of night", "vigilance",
     "rule of thirds watchman left", "watchman in vivid crimson and bronze",
     "lantern flame in vivid gold", "desaturated grayscale twilight landscape",
     "lantern as warm key light", "cold blue ambient moonlight",
     "gold rim on armor edges", "faithful watching",
     "dramatic warm-cold chiaroscuro",
     "vigilant readiness", "medium",
     "to watch is to live ready", "faithful vigilance",
     "Velar nao e calcular. Velar e viver pronto.",
     False, None, False),

    ("Q55", 5, "CTA", "Dois tipos de cristao", "Wide split: esquerda figura ajoelhada em ruina, direita figura em pe com Biblia aberta",
     "wide", "split symmetric", 35, "f/5.6", "deep",
     "a wide split composition contrasting two figures",
     "left: a figure kneeling in ruin with torn calendar pages around. Right: a figure standing with open Bible under golden divine beam",
     "Left figure in torn robe, grayscale ruined room. Right figure in crimson robe holding open glowing Bible, golden light beam descending.",
     ["kneeling manipulated figure", "standing vigilant figure", "torn calendar pages", "glowing Bible"],
     "split interior: ruin and sanctuary", "dawn", "moral contrast",
     "vertical split", "right figure in vivid crimson and gold", "left in muted grays",
     "floor in warm brown", "desaturated grayscale ruined walls",
     "left: cold flat; right: vertical divine beam", "mixed ambient",
     "gold rim on standing figure", "ethical contrast",
     "warm-cold side chiaroscuro",
     "spiritual ethics", "medium",
     "manipulated by man vs obedient to Christ", "faithful binary",
     "O primeiro e manipulado por um homem. O segundo esta obedecendo ao proprio Jesus.",
     False, None, True),

    ("Q56", 5, "CTA", "Altar com tres elementos", "Overhead altar com pergaminho sinais, relogio parado, coroa de espinhos sob luz divina",
     "overhead", "overhead 90", 50, "f/4.0", "moderate",
     "an overhead view of a stone altar with three arranged elements",
     "a golden scroll with signs, a stopped monochrome pocket watch, a crimson crown of thorns in triangular arrangement",
     "Scroll unfurled showing gold symbols, pocket watch in grayscale with frozen hands, crown of thorns in deep crimson with drop of gold.",
     ["golden prophetic scroll", "stopped grayscale pocket watch", "crimson crown of thorns"],
     "sacred stone altar", "divine vertical light", "doctrinal synthesis",
     "triangular arrangement", "scroll in vivid gold", "crown in deep crimson",
     "watch in desaturated grayscale", "absolute black surrounding",
     "vertical overhead divine light", "none",
     "gold rim on scroll edges and crown thorns", "doctrinal triangle",
     "hard overhead shadows",
     "doctrinal synthesis", "medium",
     "signs are real, return is certain, date is God's", "trinity of truths",
     "Os sinais sao reais. A volta e certa. A data e de Deus.",
     False, None, False),

    ("Q57", 5, "CTA", "Cavaleiro vermelho", "Wide cinematografico de cavaleiro vermelho do Apocalipse em armadura sangue-carmesim",
     "wide", "epic low", 24, "f/5.6", "deep",
     "a wide cinematic epic shot of the red horseman of the Apocalypse on a blood-red horse",
     "sword raised skyward with flames licking along the blade",
     "Crimson armor with gold trim, blood-red warhorse rearing, raised flaming sword, cities burning in grayscale backdrop.",
     ["red horseman", "blood-red warhorse", "flaming sword", "burning cities"],
     "apocalyptic battlefield", "red sunset", "apocalyptic teaser",
     "centered heroic composition", "rider and horse in vivid crimson and gold",
     "armor in vivid blood red", "desaturated grayscale burning cities",
     "red sunset as key light", "fiery crimson ambient",
     "gold rim on armor edges", "apocalyptic horseman",
     "dramatic crimson chiaroscuro",
     "apocalyptic cliffhanger", "high",
     "teaser: the red horse of the second seal", "series continuity",
     "Na semana que vem, eu trago o video sobre o Cavalo Vermelho — o segundo selo do Apocalipse.",
     False, None, True),

    ("Q58", 5, "CTA", "Cascos vermelhos", "Close lateral de cascos de cavalo vermelho-sangue em movimento, poeira dourada subindo",
     "close-up", "side low", 85, "f/2.8", "razor-thin",
     "a close-up side low-angle shot of blood-red horse hooves in motion",
     "the front hoof striking down with golden dust kicking upward",
     "Heavy iron shoe on blood-red hoof, leg muscles straining, cracked earth beneath, golden dust clouds.",
     ["blood-red horse hooves", "iron horseshoes", "cracked earth", "golden dust clouds"],
     "dry cracked ground", "ominous dusk", "prophecy in motion",
     "diagonal motion composition", "hooves in vivid blood red",
     "golden dust in vivid amber", "desaturated grayscale background blur",
     "side warm key light", "cool blue ambient",
     "gold rim on horseshoes", "prophecy moving",
     "dramatic motion blur",
     "imminent prophecy", "high",
     "the red horse already riding", "second seal advancing",
     "E o cavalo vermelho ja esta cavalgando.",
     False, None, False),

    ("Q59", 5, "CTA", "Pena escrevendo", "Close macro mao humana escrevendo pergunta em pergaminho com pena dourada",
     "close-up", "macro", 85, "f/2.0", "razor-thin",
     "a close-up macro of a human hand holding a golden quill pen writing on parchment",
     "the quill tip leaving a fresh ink line forming a question mark",
     "Weathered hand, ornate gold-handled quill, ink well beside, parchment with partial Portuguese script, candle flame in edge of frame.",
     ["human hand with quill", "gold-handled quill", "aged parchment", "ink well"],
     "writing desk", "candlelight", "direct invitation",
     "diagonal quill composition", "quill and hand in vivid gold and amber",
     "parchment in warm cream", "absolute black surrounding",
     "candlelight lateral", "none",
     "gold rim on quill feather", "direct engagement",
     "raking candlelight",
     "personal invitation", "low",
     "leave a comment — do we live in the last days?", "viewer engagement",
     "Deixa um comentario: voce acha que vivemos nos ultimos dias?",
     False, None, False),

    ("Q60", 5, "CTA", "Fechamento brasa", "Tela preta absoluta com unica brasa dourada desaparecendo no centro, eco de Q01",
     "black frame", "overhead implicit", 50, "f/2.8", "n/a",
     "an absolute black frame with a single dying golden ember at the exact center",
     "the ember shrinking into nothing, final wisp of smoke rising",
     "pure void blackness, one tiny gold ember losing its glow, faint thread of smoke rising vertically.",
     ["dying single gold ember", "thin vertical smoke wisp"],
     "pure black void", "after the narration ends", "narrative closure",
     "minimalist single-point focus", "ember in dying gold",
     "smoke in warm gray", "absolute black void",
     "ember self-glow fading", "none",
     "none", "contemplative closure",
     "pure blackness",
     "contemplative finality", "low",
     "the final spark", "echo of the opening",
     "[silencio total — trilha some]",
     False, None, True),
]

for q in quadros:
    try:
        (qid, parte, ato, title, nb, shot_type, angle, fl, ap, dof,
         subj, focal, second, props, loc, tod, atm,
         rule, fg, mg, bg, key, fill, rim, mood_s, shadow,
         emotion, tension, sym_p, sym_s, narr, ins_en, ins_content, pro) = q
    except ValueError as e:
        print(f"SKIP {q[0]} — tuple size {len(q)}: {e}")
        continue

    data = {
        "id": f"video-014_PARTE{parte}_{qid}",
        "version": "nano-banana-v1",
        "model_target": "gemini-2.5-flash-image",
        "scene_title": title,
        "narrative_beat": nb,
        "canal_context": {
            "canal": "sinais-do-fim",
            "video": "video-014-arrebatamento",
            "parte_suno": parte,
            "quadro": qid,
            "ato": ato
        },
        "style_reference": STYLE_REF,
        "shot": {
            "type": shot_type,
            "camera_angle": angle,
            "focal_length_mm": fl,
            "aperture": ap,
            "depth_of_field": dof,
            "aspect_ratio": "16:9"
        },
        "subject": {
            "primary": subj,
            "focal_point": focal,
            "secondary": second,
            "props": props
        },
        "environment": {
            "location": loc,
            "time_of_day": tod,
            "atmosphere": atm
        },
        "composition": {
            "rule": rule,
            "foreground": fg,
            "midground": mg,
            "background": bg,
            "safe_zone_for_overlay": "lower 20% of frame"
        },
        "lighting": {
            "key_light": key,
            "fill_light": fill,
            "rim_light": rim,
            "mood": mood_s,
            "shadow_quality": shadow
        },
        "style": STYLE_BLOCK,
        "mood": {"emotion": emotion, "tension": tension},
        "symbolism": {"primary": sym_p, "secondary": sym_s},
        "negative_as_positive": NEG,
        "in_scene_text": {"enabled": ins_en, **(ins_content if ins_content else {})},
        "api_call_hints": hints(pro=pro),
        "narration_excerpt": narr
    }
    # Clean in_scene_text — if enabled False, no content keys
    if not ins_en:
        data["in_scene_text"] = {"enabled": False}

    path = OUT / f"{qid}.json"
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"WROTE {qid} pro={pro}")

print(f"\nTOTAL: {len(quadros)} JSONs criados em {OUT}")
