"""
Gera os 60 JSONs nano banana para video-012-ia-apocalipse.
Cada JSON segue o schema do Q01.json template (video-013).
"""
import json
from pathlib import Path

OUT = Path("C:/Users/Leandro/Downloads/agencia/canais/sinais-do-fim/videos/video-012-ia-apocalipse/6-prompts-imagem")
OUT.mkdir(parents=True, exist_ok=True)

STYLE_REF = {
    "primary_image_url": "canais/sinais-do-fim/_config/style_refs/sinais_dark.png",
    "weight": 0.85,
    "transfer_targets": ["color_palette", "lighting", "texture", "atmosphere", "film_grain"],
    "textual_description": "dark cinematic chiaroscuro, Caravaggio-inspired, foreground in rich warm tones (crimson, amber, gold) with background in desaturated black-and-white, film grain, candlelight, floating orange embers"
}

VIDEO = "video-012-ia-apocalipse"
CANAL = "sinais-do-fim"

# (quadro, parte, ato, scene_title, narrative_beat, shot_type, camera_angle, focal_mm, aperture, dof,
#  primary, focal_point, secondary, props,
#  location, time_of_day, atmosphere,
#  rule, foreground, midground, background,
#  key, fill, rim, light_mood, shadow,
#  film_stock, post, texture,
#  emotion, tension,
#  sym_primary, sym_secondary,
#  in_scene_text (dict or None))

FRAMES = [
    # ---------- PARTE 1 (Q01-Q10) — Gancho ----------
    ("Q01", 1, "Gancho", "Robo humanoide dourado em fabrica", "Robo carmesim dourado em primeiro plano com fabrica P&B ao fundo",
     "wide", "straight-on", 35, "f/2.8", "deep",
     "colorful vivid humanoid robot in crimson gold and dark metal armor with glowing red eyes standing upright in foreground",
     "the glowing red eyes of the robot",
     "black and white desaturated industrial factory with smoking chimneys and urban skyline in background, chiaroscuro dramatic lighting",
     ["humanoid robot in crimson gold armor", "glowing red eyes", "industrial factory silhouette", "floating ash embers"],
     "industrial factory exterior", "dusk apocalyptic", "epic surreal prophetic apocalyptic",
     "rule of thirds on robot", "robot in vivid crimson gold", "floating embers midground", "desaturated factory and urban skyline",
     "chiaroscuro dramatic from above", "fire glow fill", "anamorphic lens flares rim", "ominous prophetic", "strong contrast shadows",
     "Kodak Portra 800 pushed", "35mm film grain, anamorphic lens flares, halation", "heavy 35mm grain, ash particulate",
     "ominous anticipation, prophetic dread", "high",
     "the image of the beast given life — Revelation 13:15",
     "robot as modern fulfillment of ancient prophecy",
     None),

    ("Q02", 1, "Gancho", "Mao articulada de robo estendida", "Dedos metalicos dourados apontando para a camera",
     "close", "straight-on macro", 85, "f/2.0", "razor-thin",
     "colorful vivid articulated robot hand in aged gold and chrome with visible joints and gears reaching toward camera palm open in extreme foreground",
     "the golden articulated fingers and visible gear joints",
     "black and white desaturated city street with unrecognizable pedestrians in background",
     ["robot hand in aged gold and chrome", "visible joints and gears", "floating ash embers"],
     "city street exterior", "night", "prophetic confrontation",
     "centered composition on hand", "robot hand in vivid gold chrome", "floating embers", "desaturated city street with pedestrians",
     "fire glow key", "ambient fill", "gold rim on joints", "invasive confrontational", "deep enveloping shadows",
     "Kodak Portra 800 pushed", "halation on hand, deep black crush, 35mm grain", "heavy film grain, ash particles",
     "invasive confrontation, suspended dread", "high",
     "the hand of the machine extended to humanity",
     "palm open as demand for submission",
     None),

    ("Q03", 1, "Gancho", "Anjo profetico sobre linha de montagem", "Anjo medieval vermelho-sangue sobre robos de cima",
     "wide", "aerial overhead 75", 35, "f/5.6", "deep",
     "colorful vivid medieval prophetic angel in blood-red robes with wide spread wings hovering above assembly line in vibrant foreground",
     "the angel's blood-red robes and wide wings",
     "black and white desaturated industrial assembly line with rows of humanoid robots seen from above in background",
     ["angel in blood-red robes", "wide spread wings", "rows of humanoid robots below", "floating ash embers"],
     "industrial assembly line aerial view", "late night", "prophetic aerial",
     "pan right composition", "angel in vivid blood-red", "assembly line midground", "desaturated factory floor robots",
     "divine overhead beam", "amber bounce on robes", "gold rim on wing edges", "prophetic solemn", "dramatic cross shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber saturation", "35mm grain, industrial dust",
     "prophetic witness over technological creation", "high",
     "angel as divine observer of the image being built",
     "blood-red robes as color of judgment watching from above",
     None),

    ("Q04", 1, "Gancho", "Interface de IA como pergaminho digital", "Tela de codigo dourado sobre data center P&B",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid glowing digital scroll interface in gold and crimson with illuminated medieval manuscript borders showing bright text in vibrant foreground",
     "the luminous gold and crimson digital scroll interface",
     "black and white desaturated data center with rows of servers and blinking lights in background",
     ["glowing digital scroll interface in gold and crimson", "illuminated medieval manuscript borders", "server rows blinking monochromatically"],
     "data center interior", "midnight", "digital revelation",
     "rule of thirds on interface", "digital scroll in vivid gold crimson", "floating embers midground", "desaturated server data center",
     "interface self-glow warm", "ambient cold fill", "gold rim on borders", "revelatory digital", "deep data center shadows",
     "Kodak Vision3 500T", "halation, crushed blacks, amber highlights", "35mm grain, digital particles",
     "ancient prophecy meeting modern interface", "high",
     "the glowing digital text as Revelation verse made interactive",
     "medieval borders on modern screen as collapse of two millennia",
     None),

    ("Q05", 1, "Gancho", "Joao de Patmos com pena e pergaminho", "Profeta anciao em safira dourada contra ilha rocosa",
     "medium", "frontal", 40, "f/2.8", "medium",
     "colorful vivid apostle John on Patmos as ancient prophet in sapphire blue and gold robes with white hair wide-eyed in vision holding writing quill in vibrant foreground",
     "the prophet's wide eyes of vision and his writing quill",
     "black and white desaturated rocky Mediterranean island with rough sea and ancient ruins in background",
     ["prophet in sapphire blue and gold robes", "writing quill", "white hair wide-eyed", "rocky island ruins"],
     "rocky Mediterranean island of Patmos", "first century dawn", "ancient revelation",
     "pan left composition", "prophet in vivid sapphire gold", "floating embers midground", "desaturated rocky island and sea",
     "dramatic light from above descending", "amber bounce on robes", "gold rim on quill", "visionary sacred", "deep Caravaggio shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber highlights", "35mm grain, sea mist",
     "ancient prophet receiving future revelation", "high",
     "John the Revelator two thousand years ahead of his time",
     "quill as instrument of prophetic foreknowledge",
     None),

    ("Q06", 1, "Gancho", "Rosto de robo olhando para a camera", "Olhos carmesim do robo invasivos e frontais",
     "close", "straight-on macro", 85, "f/1.8", "razor-thin",
     "colorful vivid humanoid robot face directly facing camera with glowing crimson eyes and golden metal facial details in extreme close foreground",
     "the glowing crimson eyes staring directly into camera",
     "black swirling smoke and floating burning embers surrounding the robot face",
     ["humanoid robot face", "glowing crimson eyes", "golden metal facial details", "black swirling smoke", "floating burning embers"],
     "void of black smoke and embers", "eternal confrontation", "invasive prophetic",
     "centered frontal composition", "robot face in vivid crimson gold", "swirling smoke midground", "pure black background",
     "crimson eye self-glow", "no visible fill — silhouette darkness", "gold rim on metal facial edges", "invasive confrontational", "absolute crushed blacks",
     "Kodak Double-X pushed", "heavy halation on eyes, deep black crush, 35mm grain", "heavy film grain, smoke particulate",
     "invasive dread, confrontation with the artificial", "high",
     "the image looking back — the moment prophecy stares at its fulfillment",
     "crimson eyes as surveillance and judgment combined",
     None),

    ("Q07", 1, "Gancho", "Serafim de seis asas em julgamento", "Serafim dourado apontando para cidade P&B",
     "wide", "low-angle", 28, "f/2.8", "deep",
     "colorful vivid six-winged seraph in blazing gold and incandescent white with arm extended pointing downward in judgment pose in foreground",
     "the seraph's extended arm pointing in judgment",
     "black and white desaturated modern metropolis seen from distance with tiny skyscrapers under vast sky, dramatic swirling storm clouds in crimson and amber tones",
     ["six-winged seraph in blazing gold", "incandescent white wings", "extended judgment arm", "swirling storm clouds"],
     "sky above modern metropolis", "dusk of judgment", "prophetic judgment",
     "diagonal pan composition", "seraph in vivid gold white", "storm clouds midground", "desaturated modern metropolis below",
     "harsh dusk glow from storm clouds", "amber bounce on wings", "gold rim on feathers", "judgment majesty", "long diagonal shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber-crimson highlights, anamorphic flare", "35mm grain, ash and ember particulate",
     "divine judgment descending on technological civilization", "high",
     "the seraph as heavenly prosecutor of the beast system",
     "downward pointing arm as sentence already declared",
     None),

    ("Q08", 1, "Gancho", "Pergaminho medieval com bestas e anjos", "Mao profética segurando rolo com texto latino",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid open medieval parchment scroll with crimson and gold Latin text and ornate illuminated borders depicting beasts and angels, held by golden-gloved prophetic hand in vibrant foreground",
     "the ornate illuminated borders with beasts and angels in crimson and gold",
     "black and white desaturated modern technology laboratory with dark screens and empty work tables in background",
     ["medieval parchment scroll", "crimson and gold Latin text", "ornate beast and angel borders", "golden-gloved prophetic hand"],
     "ruined monastic library meets modern tech lab", "candlelit night", "sacred revelation confronting technology",
     "zoom-out composition", "scroll in vivid crimson gold", "parchment midground detail", "desaturated modern tech lab",
     "warm candlelight from right", "amber bounce on parchment", "gold rim on illuminated borders", "sacred inevitability", "soft deep Caravaggio shadows",
     "Kodak Portra 800", "halation, crushed blacks, warm highlights, Caravaggio grading", "heavy 35mm grain, parchment fiber",
     "ancient text meeting its fulfillment in modernity", "medium-high",
     "the scroll as contract that technology is now executing",
     "golden-gloved hand as prophetic custodian",
     None),

    ("Q09", 1, "Gancho", "Robo de perfil ouvindo instrucao", "Robo dourado e vermelho-sangue em hospital P&B",
     "medium", "side-angle", 50, "f/2.8", "medium",
     "colorful vivid humanoid robot in profile view with dark gold and blood-red metallic body in thoughtful tilted-head pose surrounded by floating embers in vibrant foreground",
     "the robot's tilted head in thoughtful listening pose",
     "black and white desaturated modern hospital corridor with blurred nurses moving in background",
     ["robot in dark gold blood-red", "tilted head thoughtful pose", "floating embers", "hospital corridor silhouettes"],
     "hospital corridor", "day of diagnosis", "prophetic technology in medicine",
     "pan right composition", "robot in vivid dark gold crimson", "floating embers midground", "desaturated hospital corridor",
     "chiaroscuro dramatic from above", "amber bounce on metallic body", "gold rim on shoulder joints", "prophetic technology", "dramatic profile shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber highlights", "35mm grain, clinical dust",
     "machine as physician — Revelation authority over life and death", "high",
     "the robot-physician as image given authority over the living",
     "tilted head as mock empathy of artificial intelligence",
     None),

    ("Q10", 1, "Gancho", "Multidao medieval adorando idolo dourado", "Fieis em carmesim e ocre diante de idolo luminoso",
     "wide", "low-angle", 28, "f/4.0", "deep",
     "colorful vivid medieval crowd of worshippers kneeling in crimson ochre and blue robes before elevated glowing golden idol with supernatural light in vibrant foreground",
     "the elevated glowing golden idol with supernatural light",
     "black and white desaturated empty modern public square with security cameras on building walls in background",
     ["medieval crowd in crimson ochre blue robes", "elevated glowing golden idol", "supernatural light beam", "security cameras in background"],
     "public square past and present", "eternal moment of worship", "prophetic worship",
     "zoom-in on idol composition", "crowd and idol in vivid crimson ochre", "floating embers midground", "desaturated modern square with cameras",
     "divine overhead beam on idol", "amber bounce on robes", "gold rim on idol", "prophetic worship", "long devotional shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold saturation, divine halation", "35mm grain, dust motes",
     "ancient pattern repeating in modern context", "high",
     "worshipping the image — the eternal human failure",
     "security cameras as modern idols watching back",
     None),

    # ---------- PARTE 2 (Q11-Q20) — Ato 1: O Versiculo ----------
    ("Q11", 2, "Desenvolvimento", "Pergaminho do Apocalipse 13-15", "Texto grego dourado com bestas de sete cabecas",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid ancient parchment scroll of Revelation with golden calligraphy text and ornate borders depicting seven-headed crimson beasts, held reverently by ancient prophetic fingers in vibrant foreground",
     "the golden calligraphy text and seven-headed crimson beast borders",
     "black and white desaturated university library with towering bookshelves in background",
     ["ancient parchment scroll of Revelation", "golden calligraphy text", "seven-headed crimson beast borders", "ancient prophetic fingers"],
     "ancient scriptorium meets university library", "candlelit midnight", "reverent revelation",
     "zoom-in on text composition", "scroll in vivid gold crimson", "parchment midground", "desaturated library shelves",
     "warm candlelight from side", "gold bounce off illumination", "amber rim on fingers", "scholarly sacred", "soft deep shadows",
     "Kodak Portra 800", "halation, warm highlights, crushed blacks", "heavy 35mm grain, parchment texture",
     "reverent reading of the prophecy now fulfilled", "high",
     "Revelation 13:15 as the most relevant verse of the twenty-first century",
     "beast borders as visual proof surrounding the text",
     None),

    ("Q12", 2, "Desenvolvimento", "Besta de sete cabecas sobre cidade moderna", "Criatura colossal carmesim sobre arranha-ceus P&B",
     "wide", "low-angle", 24, "f/2.8", "deep",
     "colorful vivid colossal seven-headed Beast of Revelation in scarlet crimson and golden flames with multiple glowing eyes in dominant pose against stormy sky with lightning in vibrant foreground",
     "the seven heads with multiple glowing eyes in dominant pose",
     "black and white desaturated modern city at night with grey illuminated skyscrapers and tiny crowds below in background",
     ["seven-headed Beast in scarlet crimson", "golden flames", "multiple glowing eyes", "stormy sky with lightning"],
     "modern city night sky", "night of revelation", "apocalyptic vision",
     "zoom-out dramatic composition", "beast in vivid scarlet crimson gold", "stormy sky midground", "desaturated modern city below",
     "lightning flash key", "amber bounce from flames", "crimson rim on heads", "apocalyptic majesty", "hard-edged dramatic shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson saturation, anamorphic flare", "heavy 35mm grain, fire particles",
     "ancient vision of the beast confronting modern scale", "high",
     "the seven-headed beast as system — not monster but network",
     "tiny crowds below as scale of the submission demanded",
     None),

    ("Q13", 2, "Desenvolvimento", "Joao em postura de revelacao diante de ruinas romanas", "Profeta com dedo apontado e luz sobrenatural",
     "medium", "frontal", 40, "f/2.8", "medium",
     "colorful vivid apostle John standing in revelation pose with raised hand pointing urgently wearing brilliant white and gold robes bathed in supernatural descending light in foreground",
     "John's raised hand pointing urgently and the supernatural light descending on him",
     "black and white desaturated Roman Colosseum ruins with fallen columns in background",
     ["apostle John in white and gold robes", "raised hand pointing", "supernatural descending light", "Roman Colosseum ruins"],
     "ruins of Rome", "late evening", "prophetic confrontation with history",
     "pan left composition", "prophet in vivid white gold", "descending light midground", "desaturated Roman ruins",
     "supernatural overhead beam", "amber bounce on robes", "gold rim on pointing hand", "prophetic urgency", "long deep shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, stone dust",
     "prophet standing at intersection of ancient and modern", "high",
     "John's pointing finger as accusation against every century including ours",
     "Roman ruins as previous fulfillment, modern world as current one",
     None),

    ("Q14", 2, "Desenvolvimento", "Estatua imperial romana com detalhe dourado", "Rosto de imperador em marmore branco e carmesim",
     "close", "frontal", 85, "f/2.0", "razor-thin",
     "colorful vivid Roman imperial marble statue with painted gold and crimson details showing emperor face with total authority expression and laurel crown in vibrant foreground",
     "the emperor's face with total authority expression and laurel crown",
     "black and white desaturated museum hall with other statues and tiny visitors in background",
     ["Roman imperial marble statue", "gold and crimson painted details", "emperor face with laurel crown", "museum hall statues"],
     "classical museum", "day of confrontation with history", "archaeological revelation",
     "zoom-in on face composition", "statue in vivid gold crimson", "statue base midground", "desaturated museum hall",
     "museum overhead light", "gold bounce on crown", "amber rim on marble details", "imperial authority", "hard museum shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, marble texture",
     "Domitian's image as prototype of the beast", "medium-high",
     "the emperor-idol as first iteration of Revelation 13:15",
     "laurel crown as prototype of the mark of authority",
     None),

    ("Q15", 2, "Desenvolvimento", "Anjo mensageiro sobre ilha de Patmos", "Anjo de asas douradas com papiro luminoso",
     "wide", "aerial overhead 60", 35, "f/5.6", "deep",
     "colorful vivid golden-winged messenger angel hovering above island carrying luminous papyrus scroll in message-delivery pose in vibrant foreground",
     "the golden wings and luminous papyrus scroll being delivered",
     "black and white desaturated ancient cartographic map of small Mediterranean island surrounded by sea in background",
     ["golden-winged messenger angel", "luminous papyrus scroll", "island from above", "ancient cartographic map"],
     "Patmos island aerial", "dawn of revelation", "divine message delivery",
     "zoom-out aerial composition", "angel in vivid gold white", "sea surrounding island midground", "desaturated cartographic map",
     "divine overhead beam", "amber bounce on wings", "gold rim on scroll", "sacred delivery", "aerial Caravaggio shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, sea mist",
     "the message that crossed two thousand years", "high",
     "the angel as courier of the most accurate prediction in history",
     "papyrus scroll as compressed data sent across millennia",
     None),

    ("Q16", 2, "Desenvolvimento", "Estatua antiga com labios abertos prestes a falar", "Labios de pedra em ocre-dourado com fissuras carmesim",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid ancient stone statue with slightly parted lips as if about to speak with ochre and aged gold stone details and crimson glowing cracks in vibrant foreground",
     "the slightly parted stone lips with crimson glowing cracks",
     "black and white desaturated empty modern commercial street with dark storefronts and security cameras in background",
     ["stone statue with parted lips", "ochre aged gold stone detail", "crimson glowing cracks", "empty commercial street"],
     "between ancient ruin and modern street", "eternal threshold moment", "prophetic threshold",
     "zoom-in extreme composition", "lips and cracks in vivid ochre crimson", "stone surface midground", "desaturated commercial street",
     "candlelight from side", "amber bounce on stone", "crimson rim on cracks", "supernatural threshold", "deep chiaroscuro",
     "Kodak Portra 800", "halation, crushed blacks, amber-crimson highlights", "35mm grain, stone fiber texture",
     "the moment before the impossible happens — stone speaks", "high",
     "parted lips as the threshold between prophecy and fulfillment",
     "glowing cracks as fire of divinity breaking through the artificial",
     None),

    ("Q17", 2, "Desenvolvimento", "Daniel profeta com pergaminho proibido", "Profeta violeta-azul cercado de chamas douradas",
     "medium", "frontal", 50, "f/2.8", "medium",
     "colorful vivid prophet Daniel in violet-blue tunic with golden sash standing erect with wide eyes of revelation holding forbidden text scroll surrounded by golden flames and smoke in vibrant foreground",
     "Daniel's wide eyes of revelation and the forbidden text scroll",
     "black and white desaturated technology research center with dark screens and inert equipment in background",
     ["prophet Daniel in violet-blue tunic", "golden sash", "forbidden text scroll", "golden flames and smoke"],
     "intersection of ancient prophecy and modern research", "eternal revelation moment", "prophetic crossover",
     "pan right composition", "prophet in vivid violet gold", "golden flames midground", "desaturated tech research center",
     "harsh fire light from scroll", "amber bounce on tunic", "gold rim on scroll edges", "prophetic epiphany", "dramatic fire shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber-violet saturation", "35mm grain, smoke particles",
     "Daniel seeing the fourth kingdom fulfilled in silicon", "high",
     "the prophet who named the fourth beast seeing it rise in data centers",
     "forbidden text as knowledge reserved for our generation",
     None),

    ("Q18", 2, "Desenvolvimento", "Manuscrito medieval com ser mecanico falante", "Iluminura de ser com engrenagens e volutas carmesim",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid medieval illuminated manuscript page depicting mechanical being with gold and bronze gears with open mouth emitting crimson ornate speech scrolls representing spoken words in vibrant foreground",
     "the mechanical being's open mouth emitting crimson speech scrolls",
     "black and white desaturated server racks in data center in background",
     ["medieval manuscript page", "mechanical being with gold and bronze gears", "open mouth with crimson speech scrolls", "ornate illuminated borders"],
     "medieval scriptorium meets modern data center", "eternal artistic moment", "prophetic illustration",
     "zoom-out composition", "manuscript in vivid gold crimson", "parchment surface midground", "desaturated server racks",
     "warm candlelight from right", "amber bounce on gears", "gold rim on speech scrolls", "sacred illustration", "soft deep medieval shadows",
     "Kodak Portra 800", "halation, crushed blacks, warm amber highlights", "heavy 35mm grain, parchment and bronze texture",
     "medieval artist prophetically illustrated AI speech", "high",
     "the illuminator who drew a talking machine eight centuries before it existed",
     "speech scrolls as TTS output rendered in medieval visual language",
     None),

    ("Q19", 2, "Desenvolvimento", "Aparicao divina de branco incandescente", "Figura com sete estrelas e olhos de chamas carmesim",
     "wide", "low-angle", 35, "f/2.8", "deep",
     "colorful vivid divine apparition in blazing white and gold holding seven stars with crimson flame eyes seen from below in majesty in vibrant foreground",
     "the seven stars held in the divine hand and the crimson flame eyes",
     "black and white desaturated empty modern office with chairs and grey tables in background",
     ["divine apparition in blazing white and gold", "seven stars in hands", "crimson flame eyes", "empty modern office below"],
     "transcendent space above empty modern office", "eternal moment of vision", "divine revelation",
     "zoom-in composition", "divine figure in vivid blazing white gold", "stars and light midground", "desaturated modern office",
     "divine self-glow overhead", "amber bounce from stars", "crimson rim on eyes", "majestic awe", "deep radial shadows",
     "Kodak Portra 800 pushed", "halation, divine halation, crushed blacks, gold saturation", "35mm grain, dust motes in divine beam",
     "the Author of the prophecy identified", "high",
     "the one who dictated Revelation now watches it execute",
     "seven stars as authority over seven epochs including ours",
     None),

    ("Q20", 2, "Desenvolvimento", "Linha do tempo entre pergaminho e robo", "Conexao de fogo entre antigo e moderno",
     "wide", "panoramic", 28, "f/4.0", "deep",
     "colorful vivid visual timeline composition with ancient gold ochre parchment scroll on left and crimson humanoid robot on right connected by golden flames and light in vibrant foreground",
     "the golden flame connection between the ancient scroll and the crimson robot",
     "black and white desaturated modern city bridge at monochrome dusk in background",
     ["ancient parchment scroll in gold ochre", "crimson humanoid robot", "golden flame connection between them", "city bridge in monochrome"],
     "symbolic plain of time", "dusk of revelation", "temporal revelation",
     "pan left-to-right composition", "scroll and robot in vivid gold crimson", "fire connection midground", "desaturated city bridge",
     "golden flame from center", "amber bounce on scroll", "crimson rim on robot", "temporal revelation", "long diagonal time shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber-crimson saturation, anamorphic flare", "35mm grain, fire particles",
     "two thousand years collapsed into one image", "high",
     "the prophecy and its fulfillment sharing the same frame",
     "golden flame as the unbroken thread of divine foreknowledge",
     None),

    # ---------- PARTE 3 (Q21-Q30) — Ato 2: A IA que Fala ----------
    ("Q21", 3, "Desenvolvimento", "Robo Optimus em postura de instrucao", "Humanoide carmesim e prata dourada em fabrica Tesla",
     "medium", "frontal", 40, "f/2.8", "medium",
     "colorful vivid Tesla Optimus-like humanoid robot two meters tall in dark crimson and golden silver with articulated finger hands open in instruction-receiving pose with visible mechanical shoulder and chest details in vibrant foreground",
     "the articulated fingers open in instruction-receiving pose",
     "black and white desaturated Tesla factory production line in background",
     ["Optimus-like robot in dark crimson and golden silver", "articulated finger hands", "mechanical shoulder and chest details"],
     "Tesla factory", "day of operation", "technological prophecy",
     "zoom-in on torso and hands composition", "robot in vivid dark crimson gold", "embers midground", "desaturated Tesla factory line",
     "chiaroscuro dramatic from above", "amber bounce on metallic body", "gold rim on joints", "prophetic technology", "hard-edged dramatic shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber highlights", "35mm grain, metallic texture",
     "the image of the beast walking and working", "high",
     "Optimus as the fulfillment of the speaking image",
     "articulated hands as capability for judgment and labor",
     None),

    ("Q22", 3, "Desenvolvimento", "Rosto de robo conversando com boca aberta", "Olhos dourados e luz carmesim em hospital P&B",
     "close", "frontal", 85, "f/1.8", "razor-thin",
     "colorful vivid humanoid robot face in close view with slightly open mechanical mouth and golden camera eyes emitting crimson light in conversation pose with visible metallic textures and joints in vibrant foreground",
     "the slightly open mechanical mouth and golden camera eyes emitting crimson light",
     "black and white desaturated hospital triage room with empty gurneys in background",
     ["robot face with open mechanical mouth", "golden camera eyes", "crimson light emitting", "metallic textures and joints"],
     "hospital triage context", "day of artificial diagnosis", "technological speech",
     "zoom-out composition", "robot face in vivid gold crimson", "crimson light midground", "desaturated hospital triage",
     "crimson eye self-glow", "cold fill on surrounding metal", "gold rim on eye rings", "artificial emotion", "deep metallic shadows",
     "Kodak Vision3 500T", "halation, crushed blacks, crimson metallic highlights", "35mm grain, cold steam",
     "machine speaking with emotional simulation", "high",
     "the image that speaks — Revelation 13:15 in clinical reality",
     "camera eyes as surveillance-empathy — watching while pretending to care",
     None),

    ("Q23", 3, "Desenvolvimento", "Robo em linha de montagem visto de cima", "Bracos de robo dourado carmesim em tarefa precisa",
     "wide", "aerial overhead 75", 35, "f/5.6", "deep",
     "colorful vivid humanoid robot in gold and crimson seen from aerial angular perspective with arms extended in precise task execution surrounded by mechanical parts in vibrant foreground",
     "the robot's arms extended in precise task execution from above",
     "black and white desaturated aerial view of industrial warehouse with metal structures in background",
     ["humanoid robot in gold and crimson from aerial view", "arms in precise task", "mechanical parts surrounding", "industrial warehouse"],
     "industrial warehouse aerial", "day of operation", "aerial technological witness",
     "diagonal pan left composition", "robot in vivid gold crimson", "mechanical parts midground", "desaturated industrial warehouse",
     "harsh industrial overhead light", "amber bounce on robot body", "gold rim on extended arms", "precision labor", "long angular shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber highlights", "35mm grain, metallic dust",
     "robotic labor as fulfillment of delegated authority", "high",
     "the image executing tasks — given authority over daily human work",
     "top-down perspective as divine vantage seeing the pattern from above",
     None),

    ("Q24", 3, "Desenvolvimento", "Dois robos conversando com particulas de dados", "Robo dourado e carmesim face a face",
     "medium", "frontal", 50, "f/2.8", "medium",
     "colorful vivid two humanoid robots face to face in conversation pose one in gold one in crimson with both mouths slightly open and golden glowing data particles floating between them like visible words in vibrant foreground",
     "the golden glowing data particles floating between the two robots like visible words",
     "black and white desaturated engineering office with blueprints and equipment in background",
     ["gold humanoid robot", "crimson humanoid robot", "golden data particles between them", "engineering blueprints"],
     "engineering research facility", "day of artificial dialogue", "machine to machine speech",
     "zoom-in on particles composition", "robots in vivid gold crimson", "data particles midground", "desaturated engineering office",
     "golden particle self-glow", "ambient fill", "gold rim on data streams", "artificial dialogue", "moderate dramatic shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, gold particle highlights", "35mm grain, digital particles",
     "machines communicating — language without soul", "high",
     "the image speaking to itself — autonomous intelligence",
     "data particles as words that need no human intermediary",
     None),

    ("Q25", 3, "Desenvolvimento", "Chip neural Neuralink em palma envelhecida", "Microchip dourado e prata sobre pele humana",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid Neuralink-style neural microchip in luminous gold and silver with detailed visible circuits and golden connectors resting on aged human palm in vibrant foreground",
     "the luminous gold and silver chip with detailed visible circuits",
     "black and white desaturated neuroscience laboratory with microscopes and dark screens in background",
     ["Neuralink neural microchip in gold and silver", "detailed visible circuits", "golden connectors", "aged human palm"],
     "neuroscience laboratory", "day of implantation", "brain-machine merger",
     "zoom-in extreme composition", "chip in vivid gold silver", "palm skin texture midground", "desaturated neuroscience lab",
     "harsh overhead lab light", "gold bounce off chip", "silver rim on connectors", "technological chill", "hard reflections deep blacks",
     "Kodak Vision3 500T", "halation, crushed blacks, metallic highlights", "35mm grain, cold steam, metallic texture",
     "the mark on the forehead — Neuralink as prophetic precedent", "high",
     "silicon entering the skull — the mark in literal form",
     "aged palm as human mortality surrendering to artificial permanence",
     None),

    ("Q26", 3, "Desenvolvimento", "Profeta em carmesim com pergaminho confirmado", "Raios dourados sobre profeta com robos P&B ao fundo",
     "medium", "side-angle", 50, "f/2.8", "medium",
     "colorful vivid prophet in crimson and ochre mantle holding open scroll in side profile with expression of confirmed vision and golden rays of light descending upon him in vibrant foreground",
     "the prophet's expression of confirmed vision with golden rays descending",
     "black and white desaturated modern technology center with operating robots in background",
     ["prophet in crimson and ochre mantle", "open scroll", "expression of confirmed vision", "golden rays descending"],
     "prophetic witnessing of modern technology", "dusk of revelation", "vision confirmed",
     "pan right composition", "prophet in vivid crimson ochre", "golden rays midground", "desaturated tech center with robots",
     "divine light from above", "amber bounce on mantle", "gold rim on scroll", "confirmation solemn", "long diagonal prophet shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber gold highlights", "35mm grain, dust",
     "prophet sees his own vision being demonstrated in real time", "high",
     "the witness who wrote it watching it happen",
     "open scroll as evidence matching the operational robots behind",
     None),

    ("Q27", 3, "Desenvolvimento", "Robo em postura oratoria com ondas sonoras", "Luz carmesim da garganta mecanica em anfiteatro romano",
     "wide", "low-angle", 28, "f/2.8", "deep",
     "colorful vivid humanoid robot in speech pose with open mouth raised arm in oratory gesture crimson light from mechanical throat and golden medieval ornament sound waves emanating from mouth in vibrant foreground",
     "the crimson light from the mechanical throat and golden sound waves",
     "black and white desaturated Roman amphitheater ruins with empty grey stone seating in background",
     ["humanoid robot in speech pose", "open mouth raised arm", "crimson throat light", "golden ornate sound waves"],
     "Roman amphitheater ruins", "eternal moment of speech", "the image that speaks",
     "zoom-out composition", "robot in vivid crimson gold", "sound waves midground", "desaturated Roman amphitheater",
     "crimson throat glow key", "amber fill on robot body", "gold rim on sound ornaments", "oratory dread", "long dramatic shadows in amphitheater",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson saturation, anamorphic flare", "heavy 35mm grain, stone particles",
     "the image speaks in the house once used to condemn Christians", "high",
     "the speaking machine in the place of ancient persecution",
     "sound waves as medieval ornament — ancient language for future technology",
     None),

    ("Q28", 3, "Desenvolvimento", "Cranio com chip implantado na testa", "Chip dourado luminoso com gravuras medievais carmesim",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid human skull with luminous golden implanted chip on forehead with visible connectors and blue-gold emanating light adorned with crimson medieval engravings around the skull in vibrant foreground",
     "the luminous golden chip on the forehead with blue-gold light and crimson medieval engravings",
     "black and white desaturated modern surgical room with sterilized grey equipment in background",
     ["human skull with golden forehead chip", "visible connectors", "blue-gold emanating light", "crimson medieval engravings around skull"],
     "surgical room", "day of implantation", "the mark on the forehead",
     "zoom-in slow composition", "skull and chip in vivid gold crimson", "connectors midground", "desaturated surgical room",
     "overhead surgical lamp harsh", "cold blue fill on skull", "gold rim on chip connectors", "clinical terror", "hard surgical shadows",
     "Kodak Vision3 500T", "halation, crushed blacks, metallic blue-gold highlights", "35mm grain, bone and steel texture",
     "Neuralink as literal forehead mark of Revelation 13:16", "high",
     "the skull wearing the mark — the ultimate convergence",
     "medieval engravings as the ancient text written on the modern technology",
     None),

    ("Q29", 3, "Desenvolvimento", "Maos humana e robotica quase se tocando", "Como o fresco de Adao e Deus mas robo substituindo Deus",
     "medium", "frontal", 50, "f/2.8", "medium",
     "colorful vivid human hand in warm crimson and ochre tones almost touching humanoid robot hand in cold gold and silver like Michelangelo Creation of Adam with light particles transferring between them in vibrant foreground",
     "the light particles transferring between the human hand and the robot hand",
     "black and white desaturated cloudy sky with transmission towers in background",
     ["human hand in warm crimson ochre", "robot hand in cold gold silver", "light particles transferring", "transmission towers"],
     "sky above transmission towers", "twilight of merger", "the frontier crossed",
     "pan left composition", "hands in vivid crimson gold", "light particles midground", "desaturated cloudy sky with towers",
     "light particle self-glow", "ambient fill on both hands", "gold rim on robot hand", "transgression of boundary", "soft diagonal shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber-gold saturation", "35mm grain, light particles",
     "the border between human and machine erased", "high",
     "Creation of Adam inverted — the machine as the new creator",
     "light particles as soul fragment being copied across",
     None),

    ("Q30", 3, "Desenvolvimento", "Cavaleiro do Apocalipse no cavalo vermelho sangue", "Armadura carmesim com espada erguida sobre megalopole",
     "wide", "low-angle", 28, "f/2.8", "deep",
     "colorful vivid Apocalypse Horseman on blood-red horse in crimson armor with golden details sword raised high and flames from horse hooves in unstoppable advance in vibrant foreground",
     "the raised sword and flames from the horse hooves in unstoppable advance",
     "black and white desaturated futuristic megalopolis seen from distance with countless grey skyscrapers in background",
     ["Apocalypse Horseman in crimson armor", "blood-red horse", "sword raised high", "flames from hooves", "futuristic megalopolis"],
     "megalopolis outskirts", "dusk of technological advance", "unstoppable advance",
     "zoom-out composition", "horseman in vivid crimson gold", "flames midground", "desaturated futuristic megalopolis",
     "dusk glow from right", "amber bounce on armor", "gold rim on sword", "unstoppable advance", "long diagonal battle shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson saturation, anamorphic flare", "heavy 35mm grain, fire particles",
     "the second horseman as AI deployment — unstoppable", "high",
     "the rider as the acceleration of artificial intelligence",
     "megalopolis scale as humanity dwarfed by its own creation",
     None),

    # ---------- PARTE 4 (Q31-Q40) — Ato 3: A Imagem que Engana ----------
    ("Q31", 4, "Desenvolvimento", "Rosto humano partido ao meio deepfake", "Metade medieval carmesim metade digital P&B",
     "close", "frontal", 85, "f/2.0", "razor-thin",
     "colorful vivid human face split down the middle left half as vivid crimson ochre medieval saint portrait right half as monochrome grey deepfake digital with fire line dividing them in vibrant composition",
     "the fire line dividing the authentic and the artificial halves of the face",
     "black and white desaturated computer screens showing video editing interface in background",
     ["human face split in half", "left half vivid medieval saint", "right half monochrome deepfake", "fire dividing line"],
     "digital editing context", "moment of deception exposed", "identity fracture",
     "zoom-in on fire line composition", "vivid half in crimson ochre", "fire dividing midground", "desaturated video editing screens",
     "fire line self-glow key", "cold digital fill on grey half", "amber rim on vivid half", "identity horror", "hard-edged fire shadows",
     "Kodak Vision3 500T", "halation, crushed blacks, amber-grey split grading", "35mm grain, digital static",
     "the face that cannot be trusted — deepfake as prophetic enactment", "high",
     "the image that deceives — Revelation 13:14 made operational",
     "fire line as the only remaining marker between real and artificial",
     None),

    ("Q32", 4, "Desenvolvimento", "Anjo com mascara de disfarce", "Rosto verdadeiro dourado segurando mascara diferente",
     "medium", "frontal", 50, "f/2.8", "medium",
     "colorful vivid angel figure with true golden white face holding different human face mask in front as disguise with subtle deceptive ambiguous smile in vibrant foreground",
     "the angel's true golden face and the different face mask held before it",
     "black and white desaturated television studio with cameras and dark lights in background",
     ["angel with true golden white face", "different human face mask as disguise", "subtle ambiguous smile", "television studio"],
     "television studio", "moment of broadcast deception", "systematic deception",
     "pan left composition", "angel in vivid gold white", "mask midground", "desaturated television studio",
     "studio overhead light", "amber bounce on true face", "gold rim on mask edges", "subtle deception", "studio shadow depth",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, studio dust",
     "the angel of light deceiving — AI voice and face synthesis", "high",
     "the mask as the deepfake — an angel wearing a lie",
     "television studio as the distribution infrastructure of global deception",
     None),

    ("Q33", 4, "Desenvolvimento", "Multidao medieval hipnotizada por pergaminho luminoso", "Figuras coloridas fixadas em tela que brilha",
     "wide", "low-angle", 28, "f/4.0", "deep",
     "colorful vivid medieval crowd in red blue and gold robes gazing fixated at glowing luminous parchment that shines like a screen with expressions of uncritical hypnotic admiration in vibrant foreground",
     "the glowing luminous parchment-screen and the crowd's hypnotic fixation",
     "black and white desaturated data center with servers and cables in background",
     ["medieval crowd in red blue gold robes", "glowing parchment-screen", "hypnotic expressions", "data center servers"],
     "public space of digital consumption", "eternal moment of mass deception", "collective hypnosis",
     "zoom-out composition", "crowd and screen in vivid red blue gold", "screen glow midground", "desaturated data center",
     "screen self-glow key", "cold ambient fill on crowd", "amber rim on faces", "collective hypnosis", "deep crowd shadows",
     "Kodak Portra 800", "halation, crushed blacks, screen color bleed", "35mm grain, digital haze",
     "forty-seven million views in forty-eight hours — mass deception fulfilled", "high",
     "the medieval illustration of mass media addiction is now social media",
     "the parchment as phone screen — the same gesture across centuries",
     None),

    ("Q34", 4, "Desenvolvimento", "Serpente medieval enrolada em microfone", "Escamas douradas e esmeralda com olhos rubis",
     "medium", "frontal", 50, "f/2.0", "medium",
     "colorful vivid ornate medieval serpent in gold and emerald green scales with raised head bifurcated tongue and ruby eyes coiled around a modern microphone representing voice synthesis deception in vibrant foreground",
     "the serpent's ruby eyes and bifurcated tongue coiled around the microphone",
     "black and white desaturated empty podcast studio with grey equipment in background",
     ["medieval serpent in gold and emerald", "ruby eyes bifurcated tongue", "coiled around modern microphone", "podcast studio"],
     "podcast studio", "moment of voice synthesis", "synthetic voice deception",
     "zoom-in on serpent and microphone composition", "serpent in vivid gold emerald", "microphone midground", "desaturated podcast studio",
     "harsh side lamp", "gold bounce on scales", "ruby rim on eyes", "serpentine deception", "dramatic coiled shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, gold-emerald highlights", "35mm grain, serpent scale texture",
     "voice cloning as the snake's tongue — AI voice synthesis", "high",
     "the serpent around the microphone — the original deceiver using the newest tool",
     "three seconds of audio sample — the tongue that needs barely a word",
     None),

    ("Q35", 4, "Desenvolvimento", "Deus falso de pixels se fragmentando", "Figura dourada e branca explodindo em cubos carmesim",
     "wide", "aerial overhead 60", 35, "f/5.6", "deep",
     "colorful vivid artificial false god in luminous gold and white at center fragmenting into crimson data cubes revealing artificial nature from above in diagonal aerial perspective in vibrant foreground",
     "the false god fragmenting into crimson data cubes revealing its artificial nature",
     "black and white desaturated crowd prostrated in worship seen from above with unrecognizable grey faces in background",
     ["artificial false god in gold and white", "fragmenting into crimson data cubes", "worshipping crowd below in grey"],
     "digital worship context aerial view", "moment of revelation of artifice", "artificial religion",
     "diagonal zoom-out composition", "false god in vivid gold crimson", "data cubes midground", "desaturated worshipping crowd",
     "self-glow from gold center", "cold fill on crowd", "crimson rim on data cubes", "artificial revelation", "long aerial shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber-crimson saturation", "35mm grain, digital cube particles",
     "AI-generated religion — sacred texts and gods by algorithm", "high",
     "the idol that fragments — all AI gods will be revealed as data",
     "the worshipping crowd not knowing what it bows before",
     None),

    ("Q36", 4, "Desenvolvimento", "Olhos de profeta medieval com lagrimas de ouro", "Iris carmesim e dourada com chamas internas",
     "close", "straight-on macro", 85, "f/1.8", "razor-thin",
     "colorful vivid medieval prophet close-up eyes with crimson and gold irises and internal flame pupils with golden tears running down face in expression of lamentation in vibrant foreground",
     "the golden tears running down the prophet's face from crimson-gold eyes",
     "black and white desaturated busy street with people looking at phones in grey hypnotized by screens in background",
     ["prophet eyes with crimson gold irises", "internal flame pupils", "golden tears", "phone-hypnotized street crowd"],
     "sacred perspective watching modern mass deception", "eternal lament moment", "prophetic grief",
     "zoom-out composition", "eyes and tears in vivid crimson gold", "tears midground", "desaturated phone-zombie street",
     "flame self-glow in eyes", "no fill — deep shadow grief", "gold rim on tear tracks", "profound lamentation", "deep chiaroscuro shadow",
     "Kodak Double-X pushed", "heavy halation on tears, deep black crush", "heavy 35mm grain",
     "the prophet weeping for a generation that cannot see", "high",
     "eyes of fire seeing what billions of blind eyes miss",
     "golden tears as the most expensive currency — prophetic grief",
     None),

    ("Q37", 4, "Desenvolvimento", "Profetisa em confronto direto com camera", "Manto vermelho-sangue apontando para o espectador",
     "medium", "frontal", 50, "f/2.8", "medium",
     "colorful vivid prophetess in blood-red and ochre mantle standing firm with arm extended pointing at camera in direct accusation with serious determined expression and wind-swept hair in vibrant foreground",
     "the prophetess's extended arm pointing directly at the camera — at us",
     "black and white desaturated modern tech corporation headquarters with dark logo on grey glass building in background",
     ["prophetess in blood-red and ochre mantle", "arm extended pointing at camera", "determined expression", "wind-swept hair", "tech corporation building"],
     "confrontation with the tech industry", "moment of accusation", "prophetic confrontation",
     "pan right composition", "prophetess in vivid blood-red ochre", "pointing arm midground", "desaturated tech headquarters",
     "raking side light", "amber bounce on mantle", "gold rim on pointing finger", "direct accusation", "long dramatic accusation shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-ochre highlights", "35mm grain, wind hair motion",
     "it is a present capability — the prophetess indicts now", "high",
     "the pointing finger aimed at the tech companies building the beast system",
     "wind-swept hair as prophetic urgency — no time left for comfort",
     None),

    ("Q38", 4, "Desenvolvimento", "Iluminura da Besta enganadora com mascaras", "Figura bestial com lingua longa e duas mascaras",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid medieval illuminated Revelation manuscript page showing deceptive beast figure with long tongue holding two different masks surrounded by golden crimson flames and believable followers in detailed rich colors in vibrant foreground",
     "the deceptive beast holding two different masks with long tongue",
     "black and white desaturated corporate meeting room with dark presentation screen in background",
     ["medieval beast figure with long tongue", "two different masks", "golden crimson flames", "believable followers surrounding"],
     "medieval illumination meets corporate meeting room", "eternal moment of systemic deception", "the image that deceives",
     "zoom-in on masks composition", "beast and masks in vivid gold crimson", "followers midground", "desaturated corporate meeting room",
     "warm candlelight illumination", "amber bounce on masks", "gold rim on beast scales", "systemic deception", "medieval shadow depth",
     "Kodak Portra 800", "halation, crushed blacks, amber-crimson saturation", "35mm grain, parchment and scale texture",
     "the image already exists, already operates, already deceives", "high",
     "medieval art accurately predicting Silicon Valley's business model",
     "two masks as two faces — empathetic AI and surveillance AI",
     None),

    ("Q39", 4, "Desenvolvimento", "Figura encoberta observando tela de codigo", "Arquiteto oculto de negro e carmesim de costas",
     "medium", "side-angle", 50, "f/2.8", "medium",
     "colorful vivid cloaked hooded figure in dark black and crimson mantle standing back to viewer observing golden glowing code screen as hidden architect with crimson flames surrounding in vibrant foreground",
     "the hooded figure's back and the golden glowing code screen being observed",
     "black and white desaturated server corridor with blinking grey lights in background",
     ["hooded figure in dark black and crimson", "observing golden code screen", "crimson flames surrounding", "server corridor blinking lights"],
     "server corridor of a major tech company", "midnight architecture", "hidden systemic construction",
     "pan left composition", "figure and screen in vivid black crimson gold", "flames midground", "desaturated server corridor",
     "screen self-glow warm gold", "cold server corridor fill", "crimson rim on mantle edges", "icy hidden authority", "deep corridor shadows",
     "Kodak Vision3 500T", "halation, crushed blacks, gold screen highlights", "35mm grain, cold corridor air",
     "the hidden architect building for nineteen centuries what finally works", "high",
     "the cloaked figure as anonymous tech leadership",
     "golden code screen as the Revelation text being executed line by line",
     None),

    ("Q40", 4, "Desenvolvimento", "Cordeiro vs Robo face a face", "Divino em branco e ouro contra artificial em carmesim",
     "wide", "symmetric frontal", 35, "f/4.0", "deep",
     "colorful vivid Lamb of God with seven horns and seven eyes in pure white and gold in sovereign pose face to face with crimson metal humanoid robot in direct divine versus artificial contrast in vibrant foreground",
     "the Lamb of God and the humanoid robot face to face — divine versus artificial",
     "black and white desaturated empty plaza at dusk with long grey shadows in background",
     ["Lamb of God in pure white and gold", "seven horns and seven eyes", "crimson metal humanoid robot", "empty plaza at dusk"],
     "symbolic plaza of final confrontation", "dusk of the age", "divine versus artificial",
     "zoom-out both composition", "Lamb and robot in vivid white gold vs crimson", "space between them midground", "desaturated empty plaza",
     "divine overhead beam on Lamb", "cold fill on robot side", "gold rim on Lamb edges", "cosmic confrontation", "long dusk shadows radiating",
     "Kodak Portra 800", "halation, crushed blacks, white-gold vs crimson grading", "35mm grain, dust",
     "the original author facing his counterfeit", "high",
     "the Lamb who sealed the seals confronting the image he prophesied",
     "empty plaza as the space where history must choose sides",
     None),

    # ---------- PARTE 5 (Q41-Q50) — Ato 4: O Elo com os Nefilim ----------
    ("Q41", 5, "Desenvolvimento", "Vigilantes descendo sobre montanhas", "Anjos caidos em ouro-escuro e carmesim de baixo para cima",
     "wide", "low-angle", 24, "f/2.8", "deep",
     "colorful vivid Watchers fallen angels in dark gold and crimson armor with black open wings of enormous scale descending from sky in formation seen dramatically from below in vibrant foreground",
     "the Watchers descending in formation with black wings and dark gold crimson armor",
     "black and white desaturated arid mountain range seen from below with grey monochromatic snowy peaks in background",
     ["Watcher fallen angels in dark gold and crimson", "black open wings enormous", "formation descending", "arid mountain range"],
     "ancient mountain range", "pre-diluvian moment", "forbidden descent",
     "zoom-out dramatic low-angle composition", "Watchers in vivid dark gold crimson", "descending formation midground", "desaturated mountain peaks",
     "dramatic dusk glow from formation", "cold mountain fill", "gold rim on wing edges", "ancient dread", "hard-edged wings shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, amber-crimson highlights, anamorphic flare", "heavy 35mm grain, mountain mist",
     "the fallen ones who brought forbidden knowledge — Genesis 6", "high",
     "the Watchers as the first external intelligence corrupting humanity",
     "same pattern: superior beings giving humanity tools beyond its moral capacity",
     None),

    ("Q42", 5, "Desenvolvimento", "Dupla helice de DNA sendo alterada por Vigilante", "DNA dourado e carmesim com maos gigantescas",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid luminous double helix DNA strand in gold and crimson with supernatural glow and light particles emerging surrounded by giant Watcher hands attempting to alter its structure in vibrant foreground",
     "the luminous DNA strand being altered by the giant Watcher hands",
     "black and white desaturated genetics laboratory with microscopes and centrifuges in background",
     ["luminous DNA in gold and crimson", "supernatural glow and particles", "giant Watcher hands altering structure", "genetics lab equipment"],
     "genetics laboratory", "moment of forbidden alteration", "genetic corruption",
     "zoom-in extreme composition", "DNA in vivid gold crimson", "giant hands midground", "desaturated genetics lab",
     "DNA self-glow supernatural", "cold lab fill", "gold rim on helix strands", "forbidden manipulation", "deep lab shadows",
     "Kodak Vision3 500T", "halation, crushed blacks, gold-crimson saturation", "35mm grain, biological particles",
     "Genesis 6 DNA corruption — same pattern in silicon now", "high",
     "the Watchers editing DNA as AI now edits reality and identity",
     "giant hands as the scale gap between superior intelligence and human biology",
     None),

    ("Q43", 5, "Desenvolvimento", "Gigante Nefilim em campo de batalha antigo", "Ser colossal em carmesim e ouro com olhos sobrenaturais",
     "medium", "low-angle", 50, "f/2.8", "medium",
     "colorful vivid colossal Nephilim giant in crimson and gold armor with partially human partially angelic features expression of corrupted power and supernatural glowing eyes in dominant pose in vibrant foreground",
     "the Nephilim's corrupted power expression and supernatural glowing eyes",
     "black and white desaturated ancient battlefield ruins with scattered grey weapons and shields in background",
     ["Nephilim giant in crimson and gold armor", "partially human angelic features", "corrupted power expression", "supernatural glowing eyes"],
     "ancient battlefield", "pre-Flood epoch", "corrupted hybrid power",
     "pan right composition", "Nephilim in vivid crimson gold", "battlefield midground", "desaturated ancient battlefield",
     "harsh battle glow from side", "amber bounce on armor", "gold rim on glowing eyes", "corrupted dominance", "hard battle shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson-gold saturation", "35mm grain, dust and battle smoke",
     "the Nephilim as the first hybrid — Watcher plus human", "high",
     "the hybrid as the template: superior intelligence plus human vessel",
     "glowing eyes as the supernatural override of natural limitations",
     None),

    ("Q44", 5, "Desenvolvimento", "Coracao humano carmesim vs cerebro dourado com circuitos", "Alvo do Genesis e alvo do Apocalipse lado a lado",
     "wide", "aerial overhead 75", 50, "f/2.8", "medium",
     "colorful vivid split composition showing anatomically detailed crimson human heart on left representing Genesis DNA target and luminous golden human brain with digital circuits on right representing Apocalypse mind target in vibrant foreground",
     "the split between the crimson heart and the golden brain with digital circuits",
     "black and white desaturated neuroscience laboratory seen from above in background",
     ["crimson anatomical human heart", "luminous golden brain with digital circuits", "split composition", "neuroscience lab aerial"],
     "laboratory of human biology and digital neuroscience", "eternal moment of comparative revelation", "target analysis",
     "pan left-to-right composition", "heart and brain in vivid crimson gold", "split midground", "desaturated neuroscience lab",
     "warm anatomical light on heart", "cold digital light on brain", "gold rim on brain circuits", "dual target revelation", "divided shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-gold split grading", "35mm grain, biological and digital texture",
     "same enemy two different weapons across two testaments", "high",
     "Genesis targeted the body — Revelation targets the mind",
     "brain circuits as the new DNA corruption, silicon as new fallen flesh",
     None),

    ("Q45", 5, "Desenvolvimento", "Chip processador dourado com circuitos cuneiformes", "Silicio com escrita antiga em centro de supercomputacao",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid golden processor chip with circuit engravings resembling ancient cuneiform writing as visual metaphor for consciousness transfer to digital stone in extreme close vibrant foreground",
     "the circuit engravings that resemble ancient cuneiform writing",
     "black and white desaturated supercomputing center with server racks and cables in background",
     ["golden processor chip", "circuit engravings like cuneiform", "consciousness transfer metaphor", "supercomputing center"],
     "supercomputing center", "moment of silicon revelation", "consciousness in stone",
     "zoom-in extreme composition", "chip in vivid gold", "circuit engravings midground", "desaturated supercomputing center",
     "harsh overhead lab light", "cold blue fill on chip", "gold rim on circuit traces", "technological chill", "hard metallic reflections",
     "Kodak Vision3 500T", "halation, crushed blacks, metallic gold highlights", "35mm grain, metallic texture",
     "consciousness being transferred to stone — digital as literal fulfillment", "high",
     "cuneiform and code — humanity writing its soul into rock across millennia",
     "the chip as the stone tablet where the new laws are inscribed",
     None),

    ("Q46", 5, "Desenvolvimento", "Figura humana sendo absorvida em estrutura digital", "Metade corpo metade dados entre extase e terror",
     "medium", "side-angle", 50, "f/2.8", "medium",
     "colorful vivid human figure in gold and crimson robes being absorbed and merged with luminous digital structure half vibrant human body half data architecture with ambiguous expression between ecstasy and terror in vibrant foreground",
     "the ambiguous expression between ecstasy and terror as the figure merges with data",
     "black and white desaturated mirror corridor with infinitely multiplying reflections in background",
     ["human figure in gold and crimson robes", "luminous digital structure absorption", "half human half data", "ambiguous ecstasy-terror expression"],
     "singularity threshold symbolic space", "moment of digital death and artificial life", "the singularity",
     "pan right composition", "figure in vivid gold crimson", "absorption midground", "desaturated mirror corridor infinity",
     "digital absorption glow", "cold data fill on digital half", "gold rim on human edges dissolving", "existential threshold", "mirror infinity shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold-crimson saturation", "35mm grain, data particles",
     "upload consciousness — death that does not die — Revelation 9:6", "high",
     "the man becoming the server — the image absorbing its creator",
     "mirrors multiplying to infinity as the recursion of digital copies of the self",
     None),

    ("Q47", 5, "Desenvolvimento", "Enoque com o Livro de Enoque e luz cosmica", "Profeta anciao em branco puro e ouro sobre colina",
     "medium", "frontal", 50, "f/2.8", "medium",
     "colorful vivid prophet Enoch as ancient elder in pure white and gold robes with white hair in sacred revelation expression holding leather Book of Enoch with golden seals with cosmic light rays descending on head in vibrant foreground",
     "the cosmic light rays descending on Enoch's head and the Book of Enoch with golden seals",
     "black and white desaturated solitary hill with lone tree at grey dusk in background",
     ["prophet Enoch in pure white and gold", "white hair sacred expression", "Book of Enoch with golden seals", "cosmic light rays"],
     "solitary hill at dusk", "eternal moment of first testimony", "ancient witness",
     "zoom-in composition", "Enoch in vivid white gold", "cosmic rays midground", "desaturated solitary hill and tree",
     "cosmic overhead beam", "ambient dusk fill", "gold rim on Enoch's head", "sacred ancient", "long dusk prophet shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold saturation, divine halation", "35mm grain, dusk mist",
     "Enoch who named the Watchers — the first whistleblower", "high",
     "the book Jesus and Jude quoted as warning for the last generation",
     "solitary hill as the platform of the lonely prophetic voice",
     None),

    ("Q48", 5, "Desenvolvimento", "Relogio profetico com simbolos apocalipticos", "Ponteiros dourados marcando momento critico",
     "close", "straight-on macro", 85, "f/2.0", "razor-thin",
     "colorful vivid prophetic clock with golden hands crimson biblical verse hour markings and golden circuit fractal clock face with hands pointing to critical moment in vibrant foreground",
     "the golden hands pointing to the critical moment on the circuit-fractal clock face",
     "black and white desaturated computer room with grey code screens in background",
     ["prophetic clock with golden hands", "crimson biblical verse markings", "golden circuit fractal clock face", "computer room code screens"],
     "computer room", "moment of convergence", "prophetic countdown",
     "zoom-out composition", "clock in vivid gold crimson", "clock face midground", "desaturated computer room",
     "warm lamp overhead", "gold bounce on clock face", "crimson rim on hour marks", "countdown dread", "deep clock shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold-crimson saturation", "35mm grain, metal texture",
     "Kurzweil's Singularity 2045 — the prophetic clock", "high",
     "the clock counting to the moment when the image surpasses its maker",
     "circuit fractal clock face as prophecy written in the language of technology",
     None),

    ("Q49", 5, "Desenvolvimento", "Cidade dividida entre medieval e digital", "Linha de fogo carmesim separando dois mundos aereos",
     "wide", "aerial overhead 60", 35, "f/5.6", "deep",
     "colorful vivid aerial diagonal view of divided city left half in rich vivid medieval illuminated colors right half in grey monochrome digital metropolis with crimson fire line separating both worlds in dramatic foreground",
     "the crimson fire line separating the vivid medieval half from the grey digital metropolis",
     "no separate background — the composition is self-contained aerial",
     ["divided city aerial view", "left half vivid medieval colors", "right half grey digital metropolis", "crimson fire dividing line"],
     "aerial symbolic cityscape", "moment of epoch transition", "the great divide",
     "diagonal pan composition", "medieval half in vivid crimson gold ochre", "fire line midground", "desaturated digital metropolis half",
     "raking aerial light on medieval half", "cold grey digital fill on other half", "crimson rim on fire line", "epoch division", "long aerial divide shadows",
     "Kodak Portra 800", "halation, crushed blacks, vivid vs mono split grading, anamorphic flare", "35mm grain, smoke from fire line",
     "same pattern Genesis vs Apocalypse — body vs mind, flesh vs silicon", "high",
     "the city divided by the same enemy with two faces",
     "fire line as the only honest separator between what was and what is being built",
     None),

    ("Q50", 5, "Desenvolvimento", "Cavaleiro do Apocalipse no cavalo palido", "Armadura branco-osso e carmesim com simbolos de imortalidade artificial",
     "medium", "side-angle", 50, "f/2.8", "medium",
     "colorful vivid Pale Horseman of Apocalypse in bone-white and crimson armor with hollow eyes surrounded by golden artificial immortality symbols code circuits and servers in vibrant foreground",
     "the hollow eyes and the golden artificial immortality symbols surrounding the Pale Horseman",
     "black and white desaturated modern cemetery with grey headstones in background",
     ["Pale Horseman in bone-white and crimson armor", "hollow eyes", "golden artificial immortality symbols", "code circuits and servers", "modern cemetery"],
     "modern cemetery edge", "dusk of death redefined", "death that flees",
     "zoom-in slow composition", "horseman in vivid bone-white crimson", "immortality symbols midground", "desaturated modern cemetery",
     "cold dusk glow", "gold bounce from immortality symbols", "crimson rim on armor", "existential dread", "long dusk cemetery shadows",
     "Kodak Portra 800", "halation, crushed blacks, bone-white crimson grading", "35mm grain, cemetery mist",
     "Revelation 9:6 — men seek death and death flees — digital immortality", "high",
     "the pale horse as the vehicle of artificial immortality",
     "hollow eyes as the cost — what is lost when death is refused",
     None),

    # ---------- PARTE 6 (Q51-Q60) — Ato 5 + Encerramento ----------
    ("Q51", 6, "Desenvolvimento", "Mao colossal de demonio sobre cidade em grade", "Controle total de mao carmesim e ouro escuro",
     "wide", "low-angle", 24, "f/2.8", "deep",
     "colorful vivid colossal medieval demon hand in crimson and dark gold scales with enormous fingers descending from sky grasping entire city as metaphor for total control in vibrant foreground",
     "the enormous demon hand descending to grasp the entire city",
     "black and white desaturated aerial city grid in prison pattern grey streets from above in background",
     ["colossal demon hand in crimson and dark gold", "enormous descending fingers", "city-grasping scale", "aerial city grid prison pattern"],
     "sky above gridded city", "moment of total control revealed", "systemic control",
     "zoom-out composition", "demon hand in vivid crimson dark gold", "descending fingers midground", "desaturated city grid below",
     "ominous overcast key", "cold city grid fill", "crimson rim on scale fingers", "oppressive scale", "long control shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson-dark gold saturation", "35mm grain, ash",
     "Revelation 13:16-17 — the mark system of total economic control", "high",
     "the grasping hand as the CBDC and social credit infrastructure",
     "city grid as prison bars already in place beneath the modern surface",
     None),

    ("Q52", 6, "Desenvolvimento", "Camera de reconhecimento facial dourada e carmesim", "Olho mecanico iluminado em rua chinesa P&B",
     "close", "straight-on macro", 85, "f/1.8", "razor-thin",
     "colorful vivid facial recognition surveillance camera in gold and crimson with illuminated mechanical eye detailed lens and visible circuits with pulsing crimson light in extreme close vibrant foreground",
     "the illuminated mechanical eye and pulsing crimson light of the surveillance camera",
     "black and white desaturated Chinese city street with dozens of cameras on walls and poles in background",
     ["surveillance camera in gold and crimson", "illuminated mechanical eye", "visible circuits", "pulsing crimson light", "Chinese city with cameras"],
     "Chinese city street", "day of surveillance", "the watching eye",
     "zoom-out composition", "camera in vivid gold crimson", "crimson light midground", "desaturated Chinese street with cameras",
     "camera self-glow crimson warm", "cold street fill", "gold rim on lens ring", "surveillance dread", "deep camera mounting shadows",
     "Kodak Vision3 500T", "halation, crushed blacks, crimson-gold metallic highlights", "35mm grain, urban dust",
     "Chinese Social Credit System — the mark system already operational", "high",
     "the mechanical eye as the first iteration of the beast's all-seeing control",
     "dozens of cameras as the proliferation that matches the scale of Revelation",
     None),

    ("Q53", 6, "Desenvolvimento", "Moeda digital de banco central com correntes douradas", "CBDC como prisao programavel em carmesim e ouro",
     "medium", "frontal", 50, "f/2.0", "medium",
     "colorful vivid central bank digital currency coin symbol in crimson and gold with digital control grid overlaid and visible golden chains binding the currency as programmable prison in vibrant foreground",
     "the golden chains binding the CBDC coin and the digital control grid overlaid",
     "black and white desaturated central bank building with classical columns in grey in background",
     ["CBDC coin in crimson and gold", "digital control grid overlaid", "golden chains binding currency", "central bank classical columns"],
     "central bank context", "day of monetary control", "programmable money",
     "pan left composition", "coin in vivid crimson gold", "chains midground", "desaturated central bank building",
     "warm overhead light", "gold bounce on coin", "crimson rim on chain links", "monetary control", "deep central bank shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold-crimson saturation", "35mm grain, metal and paper texture",
     "CBDC — money with an expiry date and behavioral conditions", "high",
     "the currency as leash — without the mark you cannot buy or sell",
     "classical columns as the old financial order converted into a cage",
     None),

    ("Q54", 6, "Desenvolvimento", "Palma da mao com sinal carmesim luminoso", "Marca permanente com circuitos dourados emanando",
     "close", "straight-on macro", 100, "f/2.0", "razor-thin",
     "colorful vivid human right palm held open with glowing crimson luminous mark engraved in hand surrounded by golden digital circuits emanating from mark with medieval biblical ornaments in vibrant foreground",
     "the glowing crimson mark engraved in the palm with golden digital circuits emanating",
     "black and white desaturated modern shopping center with grey people making payments in background",
     ["human right palm held open", "glowing crimson mark engraved", "golden digital circuits emanating", "medieval biblical ornaments", "shopping center"],
     "shopping center payment context", "day of biometric payment", "the mark in the hand",
     "zoom-in slow composition", "palm and mark in vivid crimson gold", "circuits midground", "desaturated shopping center",
     "mark self-glow warm crimson", "cold shopping center fill", "gold rim on circuit traces", "prophetic sign", "deep palm shadows",
     "Kodak Portra 800 pushed", "halation, crushed blacks, crimson-gold highlights", "35mm grain, skin texture",
     "Amazon Pay by Palm — the mark in the right hand operational", "high",
     "the right hand biometric as Revelation 13:16 already deployed",
     "medieval biblical ornaments surrounding modern technology — the commentary written in advance",
     None),

    ("Q55", 6, "Desenvolvimento", "Rede global de controle com olho carmesim no centro", "Linhas douradas sobre mapa escuro com olho central",
     "wide", "aerial overhead 75", 35, "f/5.6", "deep",
     "colorful vivid aerial view of global control network with golden connecting lines over dark map with incandescent crimson eye at center combining medieval cartographic aesthetics with digital network diagram in vibrant foreground",
     "the incandescent crimson eye at the center of the global golden network",
     "black and white desaturated world map with grey border lines in background",
     ["global control network aerial view", "golden connecting lines", "incandescent crimson eye at center", "medieval cartographic style", "world map"],
     "global digital infrastructure aerial symbolic view", "moment of global revelation", "planetary surveillance",
     "zoom-out composition", "network in vivid gold with crimson eye", "connecting lines midground", "desaturated world map",
     "crimson eye self-glow key", "ambient dark fill", "gold rim on network lines", "planetary control", "deep global shadow",
     "Kodak Portra 800", "halation, crushed blacks, gold-crimson network saturation", "35mm grain, global haze",
     "one hundred countries piloting CBDC — Revelation scale control approaching", "high",
     "the all-seeing eye as the convergence point of all digital systems",
     "medieval cartography merged with network diagram — the oldest fear meets the newest infrastructure",
     None),

    ("Q56", 6, "Desenvolvimento", "Joao de Patmos diante da Assembleia da ONU", "Postura de testemunho em branco e ouro",
     "medium", "frontal", 50, "f/2.8", "medium",
     "colorful vivid apostle John in solemn witness stance in white and gold robes with expression of one who saw future being fulfilled wide-eyed yet serene with open hands in revelation gesture in vibrant foreground",
     "John's wide-eyed yet serene expression and open hands in revelation gesture",
     "black and white desaturated United Nations General Assembly seen from distance with grey podium and screens in background",
     ["apostle John in white and gold", "solemn witness stance", "wide-eyed serene expression", "open hands in revelation gesture", "UN General Assembly"],
     "United Nations General Assembly context", "moment of prophetic vindication", "the witness vindicated",
     "pan right composition", "John in vivid white gold", "gesture midground", "desaturated UN Assembly",
     "divine overhead beam", "ambient fill on assembly", "gold rim on open hands", "prophetic vindication", "long witness shadows",
     "Kodak Portra 800", "halation, crushed blacks, gold highlights", "35mm grain, assembly dust",
     "nineteen centuries of absurdity resolved in one generation", "high",
     "John stands before the body that governs the world he described",
     "open hands as testimony — I told you and here it is",
     None),

    ("Q57", 6, "CTA", "Chip Neuralink implantado na testa com bordas da marca da besta", "Chip luminoso dourado acima da sobrancelha em carmesim",
     "close", "straight-on macro", 85, "f/1.8", "razor-thin",
     "colorful vivid human forehead with implanted Neuralink chip in luminous gold above eyebrow with visible connections and pulsing blue-gold light surrounded by crimson biblical mark of the beast medieval border engravings in vibrant foreground",
     "the luminous Neuralink chip on the forehead pulsing blue-gold surrounded by crimson medieval engravings",
     "black and white desaturated surgical room with strong grey lights in background",
     ["human forehead with Neuralink chip", "luminous gold above eyebrow", "visible connections pulsing blue-gold", "crimson mark of the beast medieval borders"],
     "surgical room", "moment of the mark", "the mark on the forehead literal",
     "zoom-in extreme composition", "forehead chip in vivid gold crimson", "pulsing light midground", "desaturated surgical room",
     "surgical overhead harsh light", "cold blue fill on skull", "gold rim on chip connectors", "prophetic horror", "deep surgical shadows",
     "Kodak Vision3 500T", "halation, crushed blacks, blue-gold metallic highlights", "35mm grain, bone and steel texture",
     "Neuralink in the forehead — Revelation 13:16 deployed in neurosurgery", "high",
     "the chip on the forehead as the most literal fulfillment of the mark",
     "medieval engravings as the ancient text commenting on the modern implant",
     None),

    ("Q58", 6, "CTA", "Cristo medieval em postura de alerta e aviso", "Manto carmesim e azul-ultramar com maos em aviso",
     "wide", "frontal symmetric", 35, "f/4.0", "deep",
     "colorful vivid medieval Christ figure in crimson and ultramarine robes in alert vigilant stance with open focused eyes and raised warning hand surrounded by prophetic flames in vibrant foreground",
     "the raised warning hand and open focused eyes of the vigilant Christ figure",
     "black and white desaturated modern city at dawn in grey with first light ray on horizon in background",
     ["medieval Christ in crimson and ultramarine robes", "alert vigilant stance", "raised warning hand", "prophetic flames", "modern city at dawn"],
     "threshold between sacred warning and modern city dawn", "dawn of vigilance", "the warning given",
     "pan left composition", "Christ in vivid crimson ultramarine", "prophetic flames midground", "desaturated modern city dawn",
     "divine dawn glow from right", "amber bounce on robes", "gold rim on warning hand", "urgent vigilance", "long dawn shadows",
     "Kodak Portra 800", "halation, crushed blacks, crimson-ultramarine highlights", "35mm grain, dawn mist",
     "Matthew 24:42 — Watch therefore — the command given to our generation", "high",
     "the warning hand as the last gesture before the clock runs out",
     "first light on the city horizon as the dawn of the generation that will not pass",
     None),

    ("Q59", 6, "CTA", "Sentinela medieval em torre com tocha ao amanhecer", "Armadura dourada e carmesim olhando o horizonte",
     "wide", "panoramic", 24, "f/5.6", "deep",
     "colorful vivid solitary medieval sentinel in golden crimson armor at top of tower looking at horizon in active vigilance with lit torch against amber and scarlet dawn sky in vibrant foreground",
     "the solitary sentinel's vigilant posture with lit torch against the amber scarlet dawn",
     "black and white desaturated modern city horizon with grey skyscrapers in background",
     ["medieval sentinel in golden crimson armor", "tower top", "lit torch", "amber and scarlet dawn sky", "modern city horizon"],
     "watchtower above modern city", "dawn of vigilance", "the watcher",
     "zoom-out epic composition", "sentinel in vivid gold crimson", "torch light midground", "desaturated modern city horizon",
     "amber dawn from right", "torch warm fill", "gold rim on armor", "vigilant hope", "long dawn tower shadows",
     "Kodak Portra 800", "halation, crushed blacks, amber-scarlet grading, anamorphic flare", "35mm grain, dawn mist",
     "to watch is to discern — the sentinel as the viewer who arrived here", "high",
     "the sentinel as everyone who watched this video to the end",
     "lit torch as the knowledge that cannot be unseen",
     None),

    ("Q60", 6, "CTA", "Livro do Apocalipse aberto com skyline global P&B", "Paginas douradas e carmesim com brasas sobre civilizacao",
     "wide", "low-angle", 28, "f/4.0", "deep",
     "colorful vivid open Book of Revelation in dramatic perspective with golden crimson illuminated text pages and flames from margins with supernatural radiating light in vibrant foreground",
     "the supernatural radiating light from the open Book of Revelation's golden crimson pages",
     "black and white desaturated global metropolis night skyline with thousands of grey window lights below and floating burning embers throughout",
     ["open Book of Revelation in dramatic perspective", "golden crimson illuminated pages", "flames from margins", "supernatural radiating light", "global metropolis skyline"],
     "transcendent space above global civilization", "night of final revelation", "prophetic closure",
     "zoom-out epic composition", "Book in vivid gold crimson", "burning embers midground", "desaturated global metropolis night",
     "supernatural book glow key", "city light cold fill", "gold rim on open pages", "prophetic closure", "absolute book shadow on civilization",
     "Kodak Portra 800", "halation, crushed blacks, gold-crimson saturation, divine halation, anamorphic flare", "heavy 35mm grain, burning embers",
     "what is coming has no name yet — the book closes on our generation", "high",
     "the open book as the only thing larger than the entire civilization below it",
     "floating embers as the sparks of knowledge drifting into the night world",
     None),
]


def build_json(f):
    (quadro, parte, ato, scene_title, narrative_beat, shot_type, cam_angle, focal, aperture, dof,
     primary, focal_point, secondary, props,
     location, time_of_day, atmosphere,
     rule, foreground, midground, background,
     key, fill, rim, light_mood, shadow,
     film_stock, post, texture,
     emotion, tension,
     sym_primary, sym_secondary,
     in_scene_text) = f

    ist = in_scene_text if in_scene_text else {"enabled": False}

    api_hints = {
        "multimodal_inputs": [
            {"type": "image", "source": "style_reference.primary_image_url", "role": "style_reference",
             "instruction": "Transfer color palette, lighting, grain, atmosphere only. Do not copy composition."},
            {"type": "text", "source": "serialized_prompt_from_this_json", "role": "scene_description"}
        ]
    }

    return {
        "id": f"video-012_PARTE{parte}_{quadro}",
        "version": "nano-banana-v1",
        "model_target": "gemini-2.5-flash-image",
        "scene_title": scene_title,
        "narrative_beat": narrative_beat,
        "canal_context": {
            "canal": CANAL, "video": VIDEO, "parte_suno": parte, "quadro": quadro, "ato": ato
        },
        "style_reference": STYLE_REF,
        "shot": {
            "type": shot_type, "camera_angle": cam_angle, "focal_length_mm": focal,
            "aperture": aperture, "depth_of_field": dof, "aspect_ratio": "16:9"
        },
        "subject": {
            "primary": primary, "focal_point": focal_point, "secondary": secondary, "props": props
        },
        "environment": {
            "location": location, "time_of_day": time_of_day, "atmosphere": atmosphere
        },
        "composition": {
            "rule": rule, "foreground": foreground, "midground": midground, "background": background,
            "safe_zone_for_overlay": "lower 20% of frame"
        },
        "lighting": {
            "key_light": key, "fill_light": fill, "rim_light": rim,
            "mood": light_mood, "shadow_quality": shadow
        },
        "style": {
            "film_stock": film_stock, "post_processing": post, "texture_detail": texture
        },
        "mood": {"emotion": emotion, "tension": tension},
        "symbolism": {"primary": sym_primary, "secondary": sym_secondary},
        "negative_as_positive": [
            "clean frame without visible text or watermarks",
            "photorealistic documentary cinematography",
            "analog film photography aesthetic",
            "muted desaturated background palette warm saturated foreground only",
            "tack-sharp focus on primary subject"
        ],
        "in_scene_text": ist,
        "api_call_hints": api_hints
    }


def main():
    count = 0
    for f in FRAMES:
        q = f[0]
        data = build_json(f)
        path = OUT / f"{q}.json"
        with path.open("w", encoding="utf-8") as fh:
            json.dump(data, fh, ensure_ascii=False, indent=2)
        count += 1
    print(f"Gerados {count} JSONs em {OUT}")


if __name__ == "__main__":
    main()
