"""Gera os 60 JSONs nano banana para video-020-1984-daniel."""
import json
from pathlib import Path

OUT = Path("C:/Users/Leandro/Downloads/agencia/canais/sinais-do-fim/videos/video-020-1984-daniel/6-prompts-imagem")
OUT.mkdir(parents=True, exist_ok=True)

STYLE_REF = {
    "primary_image_url": "canais/sinais-do-fim/_config/style_refs/sinais_dark.png",
    "weight": 0.85,
    "transfer_targets": ["color_palette", "lighting", "texture", "atmosphere", "film_grain"],
    "textual_description": "dark cinematic chiaroscuro, Caravaggio-inspired, foreground in rich warm tones (crimson, amber, gold) with background in desaturated black-and-white, film grain, candlelight, floating orange embers"
}

STYLE_DEFAULT = {
    "film_stock": "Kodak Portra 800 pushed two stops",
    "post_processing": "halation, crushed blacks, amber highlights, anamorphic lens flares",
    "texture_detail": "35mm film grain, dust particles, floating orange embers"
}

NEG_DEFAULT = [
    "clean frame without visible text or watermarks",
    "photorealistic documentary cinematography, not illustrated or cartoon",
    "analog film photography aesthetic, no digital art flatness",
    "muted desaturated background palette, warm saturated foreground only",
    "tack-sharp focus on primary subject"
]

def shot(t, angle="straight-on", fl=50, ap="f/2.8", dof="moderate"):
    return {"type": t, "camera_angle": angle, "focal_length_mm": fl, "aperture": ap, "depth_of_field": dof, "aspect_ratio": "16:9"}

def base(qid, parte, scene_title, narrative_beat, ato):
    return {
        "id": f"video-020_PARTE{parte}_{qid}",
        "version": "nano-banana-v1",
        "model_target": "gemini-2.5-flash-image",
        "scene_title": scene_title,
        "narrative_beat": narrative_beat,
        "canal_context": {"canal": "sinais-do-fim", "video": "video-020-1984-daniel", "parte_suno": parte, "quadro": qid, "ato": ato},
        "style_reference": STYLE_REF,
    }

def api_hints(pro=False, text_note=None):
    h = {
        "multimodal_inputs": [
            {"type": "image", "source": "style_reference.primary_image_url", "role": "style_reference",
             "instruction": "Transfer color palette, lighting, grain, atmosphere only. Do not copy composition."},
            {"type": "text", "source": "serialized_prompt_from_this_json", "role": "scene_description"}
        ]
    }
    if pro:
        h["model_override"] = "pro"
    if text_note:
        h["critical_note_for_gemini"] = text_note
    return h

# Frames definition: (qid, parte, scene_title, narrative_beat, ato, shot_type, angle, fl, ap, dof, subject, focal, secondary, props, location, tod, atmo, rule, fg, bg, key, fill, rim, sh_quality, emotion, tension, sym_primary, sym_secondary, text_enabled, text_content, text_secondary, text_font, text_medium, text_placement, pro, extra_mid)
FRAMES = [
    # PARTE 1 (Q01–Q10)
    ("Q01", 1, "Dedos tuberculosos na máquina", "Extreme close-up de dedos magros e pálidos de Orwell datilografando sobre Remington preta, lenço ensanguentado ao lado", "Gancho",
     "extreme close-up", "straight-on", 50, "f/2.0", "razor-thin",
     "gaunt pale masculine fingers, almost skeletal, typing on a black 1940s Remington typewriter", "the blood-stained white handkerchief on the desk beside the typewriter",
     "Cigarette smoke low, yellow desk lamp light cutting diagonally. Foreground fingers and typewriter in rich amber and crimson tones.",
     ["black vintage Remington typewriter", "blood-stained white handkerchief", "half-smoked cigarette with rising smoke", "yellow desk lamp"],
     "a writer's desk in an isolated Scottish island cottage", "late night 1947, yellow lamplight", "tubercular, terminal, suspended",
     "rule of thirds, extreme close framing",
     "gaunt fingers and vintage typewriter keys in rich amber and crimson tones", "desaturated black-and-white Scottish island window with gusting curtain",
     "hard diagonal yellow light from desk lamp above-right", "faint amber bounce from paper", "gold rim on knuckles and metal keys",
     "chiaroscuro apocalyptic", "deep hard-edged Caravaggio shadows",
     "terminal, suspended, diseased", "high",
     "the prophetic writer dying as he writes the warning", "blood on handkerchief foreshadowing death",
     False, None, None, None, None, None, False, None),

    ("Q02", 1, "Túmulo de Eric Arthur Blair", "Wide contre-jour de lápide com cruz céltica sob garoa, corvo em silhueta, rosa vermelha e lanterna dourada",
     "Gancho",
     "wide", "straight-on low angle", 35, "f/4.0", "deep",
     "a weathered English graveyard headstone reading ERIC ARTHUR BLAIR partially legible", "a solitary red rose and a lit golden lantern placed on the grave",
     "A silent black silhouette raven perched to the right. Celtic cross in far background. Light drizzle.",
     ["weathered headstone with carved name", "solitary vivid red rose", "lit golden lantern", "black silhouette raven", "celtic stone cross"],
     "a foggy London cemetery", "overcast dawn with light drizzle", "elegiac, revelatory, prophetic",
     "rule of thirds with headstone at left third",
     "red rose and golden lantern in rich vivid hues", "desaturated black-and-white cemetery, leafless trees, headstones in fog",
     "soft diffuse contre-jour sunlight through fog", "cold ambient blue-grey fill", "golden rim on lantern glass",
     "somber cinematic", "soft long gravestone shadows",
     "elegiac, revelatory", "medium",
     "the last man in Europe buried", "raven as prophet's messenger",
     False, None, None, None, None, None, False, None),

    ("Q03", 1, "Bíblia e 1984 sobre mesa", "Overhead de mesa com Bíblia aberta em Daniel 7, livro 1984 capa preta, pergaminho hebraico",
     "Gancho",
     "overhead", "top-down 90 degrees", 35, "f/4.0", "moderate",
     "an open leather-bound Bible on a dark oak desk showing the page of Daniel 7 illuminated by candlelight", "the golden illuminated page of Daniel chapter 7 at center",
     "Beside it lies a plain black book with subtle gold embossed number 1984, and a rolled parchment with visible Hebrew letters.",
     ["open leather Bible at Daniel 7", "plain black book with embossed 1984", "rolled Hebrew parchment", "lit white candle", "orange embers floating"],
     "a scholar's study at night", "night, candlelight only", "sacred, investigative",
     "centered symmetry",
     "Bible, book, parchment in rich ochre and gold tones", "desaturated black-and-white beyond the table edge",
     "warm vertical candle light from above", "soft amber glow from pages", "golden rim on book edges",
     "chiaroscuro apocalyptic", "deep hard-edged Caravaggio shadows",
     "sacred, investigative", "medium",
     "scripture and dystopia juxtaposed", "two books prophesying the same system",
     False, None, None, None, None, None, False, None),

    ("Q04", 1, "Casa de pedra na ilha de Jura", "Wide dramatic stone cottage on remote Scottish island with single amber-lit window, silhouette bent over typewriter inside",
     "Promessa",
     "wide establishing", "eye level", 24, "f/8.0", "deep",
     "a solitary stone cottage on a remote Scottish island", "a single amber-lit window at center revealing a hunched silhouette at a typewriter",
     "Gale-force wind bends tall grass. Desaturated storm clouds overhead. Seagulls silhouetted in black.",
     ["isolated stone cottage", "amber-lit window", "silhouetted writer inside", "stormy desaturated sky", "black silhouette seagulls"],
     "remote Jura island in the Scottish Hebrides", "dusk with gathering storm", "isolation, solitary epic",
     "rule of thirds, cottage in lower third",
     "amber glowing window in rich warm tone", "desaturated black-and-white wild island landscape and storm sky",
     "warm motivated light only from the single window", "cold blue-grey ambient from storm", "gold rim on stone doorway",
     "somber cinematic", "long soft shadows",
     "isolation, solitary epic", "medium",
     "writer exiled from civilization", "the cottage as prophetic tabernacle",
     False, None, None, None, None, None, False, None),

    ("Q05", 1, "Trincheira Guerra Civil Espanhola", "Medium of a skinny man with round glasses in soaked Republican uniform, trench of fallen soldiers in monochrome background",
     "Promessa",
     "medium", "3/4 lateral", 40, "f/4.0", "moderate",
     "a skinny man in his 40s with round wire-rimmed glasses and tired eyes in a Spanish Civil War trench", "his face illuminated by low fire glow, looking at bloodstained notebook in his hand",
     "Republican soldiers in P&B silhouetted behind him. Torn red flag barely visible. Low smoke.",
     ["skinny man with round glasses", "Republican militia uniform", "bloodstained pocket notebook", "torn flag", "monochrome fallen soldiers"],
     "a trench in the Aragon front of the Spanish Civil War", "late afternoon with distant fire glow", "witness, trauma",
     "rule of thirds",
     "man's face and notebook in rich ochre and crimson blood tones", "desaturated black-and-white trench with monochrome fallen comrades",
     "warm fire glow from below-right", "cold ambient blue fill", "ochre rim on glasses and collar",
     "chiaroscuro apocalyptic", "deep hard shadows",
     "witness, trauma", "high",
     "the writer who saw history rewritten while it happened", "war as crucible of the future novel",
     False, None, None, None, None, None, False, None),

    ("Q06", 1, "Placa de bronze — lema do Partido", "Close-up of bronze plaque with three slogans in raised letters: WAR IS PEACE / FREEDOM IS SLAVERY / IGNORANCE IS STRENGTH",
     "Promessa",
     "close-up", "straight-on", 50, "f/5.6", "moderate",
     "a weathered bronze plaque with raised golden letters reading three slogans", "the center line FREEDOM IS SLAVERY in crisp patina gold",
     "Bronze patinated in rich gold and crimson. Cracks in the concrete wall behind.",
     ["weathered bronze plaque", "raised gold letters", "cracked concrete wall"],
     "a brutalist ministry facade", "overcast daylight", "declaration, cold absolute",
     "centered symmetry",
     "bronze plaque in rich gold and crimson patina", "desaturated black-and-white cracked concrete wall",
     "hard overhead directional light", "faint cold ambient fill", "gold rim on letter edges",
     "stark cinematic", "deep hard-edged shadows",
     "declaration, cold, absolute", "high",
     "the totalitarian triple inversion", "bronze as permanence of the lie",
     True, "A GUERRA É PAZ\nA LIBERDADE É ESCRAVIDÃO\nA IGNORÂNCIA É FORÇA", None,
     "bold classical Roman capital inscribed letters in patinated gold",
     "raised carved letters on weathered bronze plaque",
     "centered on the plaque, three lines equally spaced",
     True, None),

    ("Q07", 1, "Isaías ancião com pergaminho", "Medium of ancient Hebrew prophet with long beard, crimson and gold robe, holding open parchment under vertical divine light",
     "Promessa",
     "medium", "straight-on frontal", 50, "f/4.0", "moderate",
     "an ancient Hebrew prophet in his 70s with long white beard and crimson and gold robes, Caravaggio-style", "an open aged parchment scroll in his hands showing a calligraphic verse",
     "Vertical divine shaft of light from above. Babylonian ziggurat ruins in desaturated background.",
     ["ancient prophet with long beard", "crimson and gold robe", "open aged parchment", "vertical divine light"],
     "outside a ruined Babylonian temple", "symbolic eternal dusk", "oracular, condemnatory",
     "centered symmetry",
     "prophet and parchment in rich crimson and ochre and gold", "desaturated black-and-white Babylonian ziggurat ruins",
     "vertical divine light from directly above", "amber bounce from parchment", "gold rim on beard and robe",
     "chiaroscuro apocalyptic", "deep hard Caravaggio shadows",
     "oracular, condemnatory", "high",
     "Isaiah 5:20 — calling evil good and good evil", "parchment as eternal indictment",
     True, "Ai dos que chamam ao mal bem e ao bem mal", "Isaías 5:20",
     "ancient Hebrew-inspired gothic calligraphy in aged gold ink",
     "inscribed on aged parchment scroll held by the prophet",
     "center of scroll, single legible line",
     True, None),

    ("Q08", 1, "Díptico Isaías vs Orwell", "Wide symmetric diptych: left Isaiah in ochre robe with parchment, right Orwell in 40s suit with typewriter, vertical gold light seam between, giant hourglass P&B behind",
     "Promessa",
     "wide", "straight-on symmetric", 35, "f/5.6", "deep",
     "a wide symmetric diptych composition with Isaiah the prophet on the left and George Orwell on the right facing each other", "the narrow vertical seam of golden divine light between the two figures",
     "Left: ancient prophet in crimson and ochre robes holding scroll. Right: gaunt man in 1940s brown suit holding typewriter. Behind both, a gigantic desaturated hourglass.",
     ["prophet Isaiah on left", "George Orwell on right", "vertical golden light seam", "gigantic hourglass in P&B behind"],
     "symbolic transhistorical space", "eternal dusk", "historical parallel, temporal vertigo",
     "strict symmetric diptych",
     "both figures in rich crimson and ochre tones", "desaturated black-and-white giant hourglass filling the background",
     "vertical gold light down the center seam", "cold ambient blue fill on outer edges", "gold rim on both figures",
     "epic cinematic", "deep symmetric shadows",
     "historical parallel, temporal vertigo", "high",
     "two millennia collapse into the same warning", "hourglass as time unified",
     False, None, None, None, None, None, False, None),

    ("Q09", 1, "Daniel jovem em oração acorrentado", "Close-up 3/4 of young Daniel with Semitic features, eyes closed in prayer, bronze chains on wrists",
     "Promessa",
     "close-up", "3/4", 85, "f/2.0", "razor-thin",
     "a young man in his 20s with Semitic features, olive skin, dark curly hair, closed eyes in prayer", "his hands bound in heavy oxidized bronze chains at chest level",
     "Face lit laterally by single candle. Background: shadowy throne room of Nebuchadnezzar in P&B.",
     ["young Semitic prophet", "closed eyes in prayer", "heavy bronze wrist chains", "lit white candle"],
     "a corner of Nebuchadnezzar's throne room", "night, single candle", "captivity, subversive faith",
     "rule of thirds",
     "face and chains in rich warm candle tones", "desaturated black-and-white shadowy throne columns",
     "single warm candle from camera-left", "deep negative fill", "gold rim on cheek and chain",
     "chiaroscuro apocalyptic", "deep hard Caravaggio shadows",
     "captivity, subversive faith", "medium",
     "the exile prophet who saw the final beast", "chains vs inner freedom",
     False, None, None, None, None, None, False, None),

    ("Q10", 1, "Daniel e as quatro bestas no céu", "Wide of Daniel lying on stone bed, sky opening above revealing four giant silhouetted beasts emerging from ember clouds",
     "Promessa",
     "wide", "low angle tilted up", 28, "f/5.6", "deep",
     "a young prophet lying asleep on a cold stone bed, body partially covered by rough woolen blanket", "above him, a torn open sky revealing four colossal beast silhouettes emerging from burning ember clouds",
     "The four beasts: a winged lion, a bear, a four-headed leopard, an iron-toothed monster with ten horns. All in golden and crimson silhouette.",
     ["young prophet sleeping on stone", "torn sky vision", "winged lion beast", "bear beast", "four-headed leopard", "iron-horned beast", "floating embers"],
     "a prophet's stone chamber opening to visionary sky", "night vision", "visionary, apocalyptic",
     "rule of thirds with horizon at lower third",
     "prophet and beasts in rich crimson and gold silhouette", "desaturated black-and-white stone chamber and clouds",
     "otherworldly vertical light from torn sky", "deep cold blue fill", "gold rim on beast silhouettes",
     "epic apocalyptic", "deep dramatic shadows",
     "visionary, apocalyptic", "high",
     "Daniel 7 vision of four beasts", "the fourth beast different from all others",
     False, None, None, None, None, None, False, None),

    # PARTE 2 (Q11–Q20) — A QUARTA BESTA
    ("Q11", 2, "Dentes de ferro da quarta besta", "Extreme close-up of monstrous jaw with blackened iron teeth, metallic saliva",
     "Quarta Besta",
     "extreme close-up", "straight-on frontal", 100, "f/2.8", "razor-thin",
     "the monstrous jaw of an apocalyptic beast with massive blackened iron teeth and dripping metallic saliva", "a central jagged iron tooth glistening rust-crimson",
     "Dark cavernous background in P&B. Teeth in rich rust tones. Smoke.",
     ["monstrous iron teeth", "metallic saliva drip", "cavernous dark maw"],
     "inside the mouth of the fourth beast", "symbolic perpetual twilight", "visceral, predatory",
     "centered symmetry",
     "iron teeth in rich rusted crimson and dark gold", "desaturated black-and-white cavernous maw",
     "harsh raking red firelight from below", "deep cold blue fill", "rust-gold rim on each tooth",
     "chiaroscuro apocalyptic", "deep hard shadows",
     "visceral, predatory", "high",
     "Daniel 7:7 — great iron teeth devouring", "iron as empire of absolute destruction",
     False, None, None, None, None, None, False, None),

    ("Q12", 2, "Quatro impérios em miniatura", "Overhead of map table with four miniatures: winged lion, bear, four-headed leopard, iron beast arranged around Middle East parchment",
     "Quarta Besta",
     "overhead", "top-down 90 degrees", 35, "f/8.0", "deep",
     "an ancient cartography table with four small bronze and gold miniature beasts arranged around a Middle East parchment map", "the central rolled map of the ancient Near East with Hebrew annotations",
     "The four miniatures in rich metallic colors. Surrounding table surface desaturated.",
     ["winged lion miniature", "bear miniature", "four-headed leopard miniature", "iron beast with ten horns", "antique parchment map"],
     "a cartographer's war room", "candlelight", "taxonomic, prophetic",
     "centered symmetry",
     "four miniatures in rich bronze, crimson, and gold", "desaturated black-and-white surrounding table",
     "warm overhead candlelight", "amber bounce from parchment", "gold rim on miniatures",
     "chiaroscuro apocalyptic", "soft focused shadows",
     "taxonomic, prophetic", "medium",
     "four empires preceding the end", "the fourth distinct from all others",
     False, None, None, None, None, None, False, None),

    ("Q13", 2, "Altar das três chamas", "Medium of stone altar with three vertical flames — red, gold, ochre — each projecting smoke word: PALAVRAS, TEMPOS, LEI",
     "Quarta Besta",
     "medium", "straight-on symmetric", 50, "f/4.0", "moderate",
     "a rough-hewn stone altar with three tall vertical flames of distinct colors", "the smoke rising from each flame forming three Portuguese words in visible script",
     "Background: broken Roman column in deep P&B. Embers floating.",
     ["stone altar", "three colored flames (red, gold, ochre)", "smoke forming words", "broken Roman column behind"],
     "a ruined prophetic sanctuary", "twilight", "triple revelation",
     "strict centered symmetry",
     "three flames and smoke words in rich vivid red, gold and ochre", "desaturated black-and-white broken column behind",
     "warm flame light from flames themselves", "deep negative fill", "gold rim on altar edges",
     "chiaroscuro apocalyptic", "deep flickering shadows",
     "triple revelation", "high",
     "three specific actions of the beast", "smoke as prophetic speech",
     True, "PALAVRAS      TEMPOS      LEI", None,
     "rising smoke forming ancient gothic Portuguese capital letters",
     "flame-smoke writing in the air above each flame",
     "three words arranged horizontally, one above each flame",
     True, None),

    ("Q14", 2, "Câmara de interrogatório — Ministério do Amor", "Wide of sterile P&B interrogation chamber with metal chair, surgical light, golden pedestal with rat cage",
     "Quarta Besta",
     "wide", "straight-on symmetric", 28, "f/5.6", "deep",
     "a sterile underground interrogation chamber with a central metal chair bolted to the floor", "a golden ornate pedestal to the right holding a metal cage with rats",
     "Surgical overhead light. White tiled walls desaturated. Iron door at back.",
     ["metal interrogation chair", "golden pedestal with rat cage", "surgical overhead light", "white tiled walls", "iron door"],
     "basement interrogation chamber of the Ministry of Love", "always night, surgical light", "clinical, terrifying",
     "centered symmetry",
     "golden pedestal and golden key props in rich gold and crimson", "desaturated black-and-white tiled chamber and chair",
     "harsh cold overhead surgical light", "deep shadow fill", "gold rim on pedestal and cage",
     "stark cinematic", "deep hard-edged shadows",
     "clinical, terrifying", "high",
     "Room 101 as ultimate personalized torture", "rats as each man's specific horror",
     False, None, None, None, None, None, False, None),

    ("Q15", 2, "Olho aterrorizado sob monóculo", "Extreme close-up of terrified human eye under dark lens, reflection of austere mustached face in crimson poster",
     "Quarta Besta",
     "extreme close-up", "frontal", 100, "f/2.0", "razor-thin",
     "a terrified human eye viewed through a dark round monocle lens", "the reflected image in the lens of an austere mustached dictatorial face in crimson",
     "Deep wrinkles around the eye. Background P&B blurred.",
     ["terrified human eye", "dark monocle lens", "reflected mustached face in crimson", "deep wrinkles"],
     "a paranoid citizen's room", "night, television-like glow", "intimate paranoia",
     "rule of thirds with eye at center",
     "eye and crimson reflection in rich warm tones", "desaturated black-and-white blurred surroundings",
     "harsh cold television glow from camera-left", "deep negative fill", "gold rim on monocle edge",
     "chiaroscuro apocalyptic", "deep hard shadows",
     "intimate paranoia", "high",
     "thoughtcrime — the eye betraying inner thought", "the Party watches from within the reflection",
     False, None, None, None, None, None, False, None),

    ("Q16", 2, "Ministério da Verdade — corredor de arquivo", "Wide perspective of gigantic bureaucratic archive corridor with silhouetted archivists in infinite rows, central man feeding paper into flaming wall slot",
     "Quarta Besta",
     "wide", "one-point perspective", 24, "f/8.0", "deep",
     "a gigantic bureaucratic archive corridor with a strong central vanishing point", "a single man in his 40s in ochre and crimson suit at center, back turned, feeding a paper into a wall slot emitting orange fire",
     "Endless silhouetted archivists in P&B rows extending to infinity. Cold fluorescent strips.",
     ["infinite file cabinets", "silhouetted archivists", "central man feeding memory hole", "orange flame from slot"],
     "the archives of the Ministry of Truth", "eternal office fluorescent", "totalitarian bureaucracy",
     "one-point perspective",
     "central man and flame in rich ochre, crimson and orange", "desaturated black-and-white archive corridor and archivists",
     "cold fluorescent overhead plus warm flame from the slot", "deep negative fill", "gold rim on central figure's shoulder",
     "dystopian cinematic", "long linear shadows",
     "totalitarian bureaucracy", "high",
     "erasing the past to control the future", "the memory hole as devourer of history",
     False, None, None, None, None, None, False, None),

    ("Q17", 2, "Álbum de fotos com rostos riscados", "Medium tilt-down of open photo album with half vibrant color photos, half with faces blacked out or torn away; golden magnifier over erased face",
     "Quarta Besta",
     "medium", "tilt-down 45 degrees", 50, "f/4.0", "moderate",
     "an open leather photo album on a wooden desk with old family photographs", "a vintage golden magnifying glass hovering over a photograph with its central face violently blacked out with ink",
     "Half the photos in vivid saturated color, half with faces crossed out or torn holes.",
     ["open leather photo album", "half vivid half defaced photos", "golden vintage magnifier", "ink blacked faces"],
     "a Party archivist's desk", "night, desk lamp", "erasure, silent horror",
     "rule of thirds",
     "magnifier and intact photos in rich saturated tones", "desaturated black-and-white background shelves",
     "warm focused desk lamp from camera-right", "soft amber bounce from paper", "gold rim on magnifier frame",
     "somber cinematic", "soft focused shadows",
     "erasure, silent horror", "medium",
     "non-persons — erased as if they never existed", "magnifier seeking what was destroyed",
     False, None, None, None, None, None, False, None),

    ("Q18", 2, "Balança da justiça corrompida", "Close-up of rusted justice scales in rich crimson and gold, unbalanced: one pan holds metal chain, the other a burning law book",
     "Quarta Besta",
     "close-up", "diagonal", 85, "f/2.8", "razor-thin",
     "a rusted and ornate justice scale, unbalanced", "the right pan holding a burning leather-bound law book with orange flames, the left pan holding a heavy iron chain",
     "Crimson and gold tones on scale. Background: ruined courtroom with broken columns P&B.",
     ["rusted ornate justice scales", "iron chain in left pan", "burning leather law book in right pan", "orange flames"],
     "a ruined tribunal", "symbolic dusk", "arbitrariness, insecurity",
     "rule of thirds diagonal",
     "scales and flames in rich rusted gold and crimson", "desaturated black-and-white ruined courtroom",
     "warm flame light from book", "deep negative fill", "gold rim on scale chains",
     "chiaroscuro apocalyptic", "hard flickering shadows",
     "arbitrariness, insecurity", "high",
     "the law as whatever the Party says it is today", "burning book as burned legality",
     False, None, None, None, None, None, False, None),

    ("Q19", 2, "Multidão P&B com figura iluminada no centro", "Wide overhead of P&B silhouetted crowd walking in parallel lines on white marble, single figure at center in ochre robes under golden spotlight",
     "Quarta Besta",
     "wide overhead", "60 degree tilt", 24, "f/5.6", "deep",
     "a vast marble plaza seen from above with hundreds of silhouetted human figures walking in rigid parallel lines", "a single figure at center in vivid ochre and crimson robes looking upward in despair, lit by a vertical golden spotlight",
     "Crowd entirely desaturated. Central figure in vivid color. Ash particles floating.",
     ["vast marble plaza", "silhouetted parallel-line crowd", "central figure in ochre robe", "vertical golden spotlight"],
     "a totalitarian public plaza", "eternal twilight", "systemic guilt",
     "centered radial composition",
     "central figure in rich ochre and crimson", "desaturated black-and-white marble and crowd",
     "vertical golden spotlight from above on central figure", "deep cold ambient fill", "gold rim on figure's shoulders",
     "epic cinematic", "long linear crowd shadows",
     "systemic guilt", "high",
     "permanent potential criminality under arbitrary law", "spotlight as inescapable gaze",
     False, None, None, None, None, None, False, None),

    ("Q20", 2, "Espectador diante de espelho rachado", "Medium close-up of modern hooded silhouette P&B facing cracked mirror, reflection shows human face in vibrant rich colors, golden frame",
     "Quarta Besta",
     "medium close-up", "3/4", 40, "f/4.0", "moderate",
     "a modern hooded figure in P&B silhouette seen from behind, facing a cracked antique mirror", "the reflection in the mirror showing the same person's face in vivid rich warm tones, eyes wide with recognition",
     "Ornate golden antique mirror frame. Embers floating between figure and mirror.",
     ["modern hooded silhouette", "cracked antique mirror", "vivid reflected face", "ornate golden mirror frame"],
     "a dark minimalist contemporary room", "night ambient glow", "interpellation, recognition",
     "centered symmetry",
     "golden frame and reflected face in rich warm tones", "desaturated black-and-white hooded figure and room",
     "vertical cold ambient from above on figure, warm glow from mirror reflection", "deep negative fill", "gold rim on mirror frame and reflected cheek",
     "chiaroscuro apocalyptic", "deep mirror-split shadows",
     "interpellation, recognition", "medium",
     "the viewer recognizing the system in their own life", "mirror as self-confrontation",
     False, None, None, None, None, None, False, None),

    # PARTE 3 (Q21–Q32) — OPERAÇÃO DE ERRO
    ("Q21", 3, "Paulo escreve em cela romana", "Medium of apostle Paul in Roman cell, left hand chained, right hand writing with quill on parchment, crimson and ochre robe",
     "Operação de Erro",
     "medium", "3/4 lateral", 50, "f/2.8", "razor-thin",
     "the apostle Paul in his 60s with graying beard and weathered hands, seated in a Roman stone cell", "his right hand holding a quill writing on an open parchment, left wrist bound in heavy iron chain to a stone wall",
     "Crimson and ochre robe in rich tones. Single shaft of golden light through stone slit.",
     ["aged apostle Paul", "iron wrist chain on stone", "quill and inkwell", "open parchment", "crimson ochre robe"],
     "a Roman prison cell", "symbolic late afternoon, single shaft", "imprisoned prophetic writer",
     "rule of thirds",
     "Paul and parchment in rich crimson and ochre", "desaturated black-and-white stone cell walls",
     "golden shaft of light from stone slit camera-left", "cold ambient blue fill", "gold rim on face and quill",
     "chiaroscuro apocalyptic", "deep hard Caravaggio shadows",
     "imprisoned prophetic writer", "medium",
     "2 Thessalonians written from chains", "quill as prophetic instrument",
     False, None, None, None, None, None, False, None),

    ("Q22", 3, "Energeia planes — palavras gregas", "Extreme close-up of parchment lit by candle, Greek calligraphic text visible, bronze ring finger pointing",
     "Operação de Erro",
     "extreme close-up", "slight angle", 100, "f/2.8", "razor-thin",
     "an aged parchment scroll illuminated by a single candle with elegant Greek calligraphy in gold ink", "the two Greek words ENERGEIAN PLANES at center in ancient script",
     "A masculine hand with a bronze signet ring points to the phrase. Floating embers.",
     ["aged parchment scroll", "Greek gold-ink calligraphy", "bronze signet ring", "white candle"],
     "a scholar's study table", "night, candlelight", "textual revelation",
     "rule of thirds",
     "parchment and ring in rich amber and gold", "desaturated black-and-white blurred surroundings",
     "warm candle light from camera-right", "amber bounce from parchment", "gold rim on letters and ring",
     "chiaroscuro apocalyptic", "soft focused shadows",
     "textual revelation", "medium",
     "energeia planes — active operation of deception", "original Greek as key to understanding",
     True, "ΕΝΕΡΓΕΙΑΝ ΠΛΑΝΗΣ", "2 Tessalonicenses 2:11",
     "ancient Greek uncial calligraphy in aged gold ink",
     "hand-inked on the open parchment",
     "center of scroll, one primary line",
     True, "The Greek letters must be rendered exactly as written in uncial script. This is sacred biblical Greek and accuracy is critical."),

    ("Q23", 3, "Dois cérebros conectados — duplipensar", "Wide symmetric of two floating human brains — one crimson, one gold — chained together in inverted Y, over P&B bureaucratic control panel",
     "Operação de Erro",
     "wide", "straight-on symmetric", 35, "f/5.6", "deep",
     "two anatomically realistic human brains floating midair", "the left brain glowing crimson red, the right brain glowing warm gold, linked by a heavy golden chain in inverted Y shape",
     "Below and behind: desaturated bureaucratic control panel with buttons and meters.",
     ["floating crimson brain", "floating gold brain", "heavy golden chain", "bureaucratic control panel"],
     "symbolic abstract space", "symbolic eternal", "conceptual abstraction, grotesque",
     "centered symmetry",
     "brains and chain in rich crimson and gold", "desaturated black-and-white control panel",
     "divine light from above between the brains", "cold ambient edge fill", "gold rim on brain surfaces and chain",
     "surreal cinematic", "sharp symmetric shadows",
     "conceptual abstraction, grotesque", "medium",
     "doublethink — holding contradictions simultaneously", "chains as mental imprisonment",
     False, None, None, None, None, None, False, None),

    ("Q24", 3, "Pirâmide do Ministério da Verdade", "Wide establisher of massive brutalist P&B pyramid with three giant engraved slogans on face, tiny crimson-robed figure climbing at base",
     "Operação de Erro",
     "wide establisher", "low angle", 24, "f/8.0", "deep",
     "a colossal brutalist white concrete pyramid with three enormous engraved slogans on its face", "the three slogans WAR IS PEACE / FREEDOM IS SLAVERY / IGNORANCE IS STRENGTH at massive scale",
     "A tiny figure in crimson robe ascending the steps at the base. Stormy desaturated crimson-red sky.",
     ["massive concrete pyramid", "three engraved slogans", "tiny crimson-robed climbing figure", "stormy desaturated sky"],
     "the central plaza of Oceania", "permanent overcast dusk", "monumental, oppressive",
     "centered symmetry with pyramid at frame center",
     "tiny climbing figure in rich crimson", "desaturated black-and-white pyramid and sky",
     "harsh overhead directional light on pyramid face", "deep cold ambient fill", "gold rim on pyramid edges",
     "epic dystopian", "deep geometric shadows",
     "monumental, oppressive", "high",
     "the four Ministries as absolute power", "slogans engraved as permanent lie",
     True, "WAR IS PEACE\nFREEDOM IS SLAVERY\nIGNORANCE IS STRENGTH", None,
     "gigantic carved brutalist English capital letters in weathered concrete",
     "engraved into the pyramid face, three stacked monumental lines",
     "center of the pyramid face, occupying upper 60 percent",
     True, None),

    ("Q25", 3, "Ministério da Paz — mesa de guerra", "Medium overhead of war table with rich bronze and lead tank miniatures, golden plaque MINISTÉRIO DA PAZ, silhouetted generals",
     "Operação de Erro",
     "medium overhead", "60 degree tilt", 40, "f/5.6", "moderate",
     "a long oak war planning table with bronze and lead miniature tanks, soldiers and artillery arranged on a dark map", "a heavy golden engraved plaque at the table's near edge reading MINISTÉRIO DA PAZ",
     "Silhouetted uniformed generals hunched over the map in P&B at the far end.",
     ["bronze tank miniatures", "lead soldier miniatures", "golden plaque", "silhouetted generals"],
     "the war room of the Ministry of Peace", "night, overhead lamp", "brutal irony",
     "rule of thirds",
     "miniatures and plaque in rich bronze, crimson and gold", "desaturated black-and-white generals and background",
     "warm overhead lamp from above-right", "cold ambient fill from below", "gold rim on miniatures and plaque",
     "chiaroscuro apocalyptic", "deep focused shadows",
     "brutal irony", "high",
     "Peace Ministry managing war", "miniatures as rehearsal for real death",
     True, "MINISTÉRIO DA PAZ", None,
     "bold engraved serif capital letters in warm polished gold",
     "engraved on a heavy rectangular brass plaque",
     "lower center of frame on the table edge",
     True, None),

    ("Q26", 3, "Prateleira quase vazia — Ração Vitória", "Close-up of empty P&B grocery shelf with single dented gold-labeled can RAÇÃO VITÓRIA, flies",
     "Operação de Erro",
     "close-up", "straight-on", 50, "f/4.0", "moderate",
     "an almost empty grocery store shelf with dust", "a single dented cylindrical tin can with a rich gold label reading RAÇÃO VITÓRIA at center",
     "Harsh fluorescent overhead. Cold empty white shelves extending. Two flies.",
     ["empty grocery shelves", "single dented can", "gold label RAÇÃO VITÓRIA", "flies"],
     "a state-run grocery store in Oceania", "cold fluorescent day", "privation, empty propaganda",
     "rule of thirds with can at center",
     "can and gold label in rich gold and crimson", "desaturated black-and-white shelves and store",
     "cold fluorescent overhead", "deep cool ambient fill", "gold rim on can edge",
     "stark dystopian", "hard overhead shadows",
     "privation, empty propaganda", "medium",
     "Abundance Ministry managing scarcity", "victory-labeled starvation",
     True, "RAÇÃO VITÓRIA", None,
     "bold propaganda-era serif capital letters in warm printed gold",
     "printed label on cylindrical tin can",
     "center of the can label facing camera",
     True, None),

    ("Q27", 3, "Porta de ferro — Ministério do Amor", "Wide of black iron door with small guichet, golden plaque MINISTÉRIO DO AMOR above, drying blood stains on wall",
     "Operação de Erro",
     "wide", "straight-on symmetric", 35, "f/5.6", "deep",
     "a heavy black iron door in a brutalist concrete wall with a small sliding viewport at eye level", "a heavy rectangular golden plaque bolted above the door with engraved letters",
     "Drying dark blood stains on the desaturated concrete walls beside the door. Golden chain hanging.",
     ["heavy black iron door", "small viewport slide", "golden plaque", "blood stains on concrete", "hanging golden chain"],
     "the entrance to the Ministry of Love", "night, single bulb", "cruel inversion",
     "strict centered symmetry",
     "golden plaque and chain in rich polished gold", "desaturated black-and-white door, concrete and bloodstains",
     "single warm bulb from above the door", "deep negative fill", "gold rim on plaque edges and viewport",
     "stark dystopian", "deep door-flanking shadows",
     "cruel inversion", "high",
     "Love Ministry practicing torture", "plaque as euphemism for horror",
     True, "MINISTÉRIO DO AMOR", None,
     "bold engraved serif capital letters in warm polished gold",
     "engraved on a rectangular gold plaque bolted to concrete",
     "centered above the iron door",
     True, None),

    ("Q28", 3, "Impressora rotativa cuspindo jornais", "Medium lateral of vintage rotary press spewing infinite P&B newspaper reels with contradictory headlines, golden gloved hand feeding page to flaming slot",
     "Operação de Erro",
     "medium", "lateral 3/4", 50, "f/4.0", "moderate",
     "a massive vintage rotary printing press with enormous paper reels spewing out endless black-and-white newspaper pages", "a masculine hand in a rich golden leather glove holding a printed page, feeding it into a small wall slot engulfed in orange flames",
     "Contradictory newspaper headlines visible on the reels in P&B. Floating embers.",
     ["rotary printing press", "paper newspaper reels", "contradictory headlines", "golden gloved hand", "flaming memory hole slot"],
     "the print floor of the Ministry of Truth", "eternal factory night", "factory of falsification",
     "rule of thirds",
     "gloved hand and flame in rich gold, crimson and orange", "desaturated black-and-white press and newspapers",
     "warm flame light from slot plus overhead fluorescent", "cold ambient edge fill", "gold rim on glove and page",
     "chiaroscuro apocalyptic", "deep machinery shadows",
     "factory of falsification", "high",
     "Truth Ministry producing lies", "flame as eraser of recorded truth",
     False, None, None, None, None, None, False, None),

    ("Q29", 3, "Isaías ecoa — arranjo em pétalas", "Overhead of parchment verse at center with four small gold plaques around: PAZ, ABUNDÂNCIA, AMOR, VERDADE",
     "Operação de Erro",
     "overhead", "top-down 90 degrees", 35, "f/5.6", "deep",
     "an aged parchment scroll at center reading Ai dos que chamam ao mal bem e ao bem mal in ornate calligraphy", "four small golden plaques arranged like petals around the scroll, each bearing one word: PAZ ABUNDÂNCIA AMOR VERDADE",
     "Stone surface below. Floating embers around edges.",
     ["central aged parchment", "four small golden plaques", "stone surface", "floating embers"],
     "a symbolic prophetic altar", "candlelit night", "circular confirmation",
     "strict centered radial symmetry",
     "parchment and plaques in rich gold, crimson and ochre", "desaturated black-and-white stone surface edges",
     "warm overhead vertical candle-like light", "amber bounce from parchment", "gold rim on plaque edges",
     "chiaroscuro apocalyptic", "soft radial shadows",
     "circular confirmation", "medium",
     "Isaiah 5:20 proven by four inverted ministries", "radial arrangement as cosmic seal",
     True, "Ai dos que chamam ao mal bem e ao bem mal", "PAZ · ABUNDÂNCIA · AMOR · VERDADE",
     "center: ancient gothic Portuguese calligraphy in aged gold ink. Petals: bold engraved capital letters in polished gold",
     "center inscribed on parchment; petals engraved on four small gold plaques",
     "center for scroll verse; four plaques radially at cardinal points",
     True, None),

    ("Q30", 3, "Paulo e Orwell ao longo do eixo dourado", "Wide panoramic with horizontal golden axis cutting frame; left Paul under Roman column, right Orwell under typewriter, giant P&B hourglass behind",
     "Operação de Erro",
     "wide panoramic", "eye level", 28, "f/8.0", "deep",
     "a wide panoramic frame divided by a horizontal golden axis of light, with apostle Paul on the left under a Roman column and Orwell on the right under a vintage typewriter", "the horizontal golden seam of divine light connecting the two figures",
     "Both figures in rich warm tones. Behind them a gigantic desaturated hourglass. Floating embers.",
     ["Paul with Roman column", "Orwell with typewriter", "horizontal golden axis", "gigantic P&B hourglass behind"],
     "symbolic transhistorical space", "eternal twilight", "historical convergence",
     "strict symmetric panoramic",
     "both figures in rich crimson, ochre and gold", "desaturated black-and-white giant hourglass",
     "horizontal golden axis light", "cold ambient edge fill", "gold rim on both figures",
     "epic cinematic", "deep horizontal axial shadows",
     "historical convergence", "high",
     "two men, two millennia, same machine", "axis as prophetic thread through time",
     False, None, None, None, None, None, False, None),

    ("Q31", 3, "Engrenagem dourada com texto bíblico", "Extreme close-up of golden clock gear, teeth perfectly interlocking, faint biblical text engraved in metal",
     "Operação de Erro",
     "extreme close-up", "diagonal", 100, "f/2.8", "razor-thin",
     "a massive golden clockwork gear with perfectly interlocking teeth", "the faint biblical text engraved in aged Hebrew characters on the gear face",
     "Behind: blurred dials and clock pointers in desaturated tones. Floating dust.",
     ["golden clockwork gear", "interlocking teeth", "faint Hebrew engraving", "blurred dials behind"],
     "inside a prophetic clockwork mechanism", "symbolic eternal", "prophetic mechanics",
     "rule of thirds with gear at center",
     "gear in rich gold and patinated bronze", "desaturated black-and-white dials and pointers behind",
     "warm directional light from camera-right", "deep amber ambient fill", "gold rim on each gear tooth",
     "chiaroscuro apocalyptic", "soft focused shadows",
     "prophetic mechanics", "medium",
     "the same gear turning silently for 2500 years", "interlocking teeth as divine precision",
     False, None, None, None, None, None, False, None),

    ("Q32", 3, "Transição — anjo sobre cidade vigilada", "Wide aerial of contemporary city P&B with red blinking dots on corners, giant crimson-gold angel silhouette floating above with open parchment",
     "Operação de Erro",
     "wide aerial", "high angle", 24, "f/8.0", "deep",
     "an aerial night view of a contemporary metropolis with hundreds of tiny blinking red surveillance camera dots on every corner", "a colossal angelic silhouette in crimson and gold robes floating above, holding an open parchment",
     "Desaturated night cityscape below. Angel in rich colors above. Floating embers.",
     ["contemporary aerial cityscape", "blinking red camera dots", "colossal angel silhouette", "open parchment in angel's hand"],
     "a surveilled modern city at night", "night with urban glow", "transition prophecy to reality",
     "rule of thirds with angel at upper third",
     "angel and parchment in rich crimson and gold", "desaturated black-and-white city with red dot accents",
     "divine vertical light from angel downward", "cold urban ambient fill", "gold rim on angel wings",
     "epic apocalyptic", "deep long angelic shadows",
     "transition prophecy to reality", "high",
     "prophecy hovering over surveilled present", "angel as bridge between Daniel and today",
     False, None, None, None, None, None, False, None),

    # PARTE 4 (Q33–Q46) — CHINA E A MARCA
    ("Q33", 4, "Parede-mosaico de câmeras", "Wide symmetric wall-mosaic of hundreds of P&B security cameras in grid, central single eye in rich gold with crimson iris",
     "China e a Marca",
     "wide", "straight-on symmetric", 28, "f/8.0", "deep",
     "a colossal wall formed by hundreds of identical security surveillance cameras arranged in a perfect grid", "a single organic human eye at the exact center of the grid, with rich gold sclera and crimson iris",
     "All cameras in P&B. Central eye in vivid warm tones. Floating embers.",
     ["grid of hundreds of cameras", "central organic human eye", "gold sclera crimson iris"],
     "a panoptic surveillance wall", "sterile eternal twilight", "technological omnipresence",
     "strict centered radial symmetry",
     "central eye in rich gold and crimson", "desaturated black-and-white camera grid",
     "cold overhead clinical light on cameras, warm central spotlight on eye", "deep negative fill", "gold rim on eye and grid edges",
     "stark dystopian cinematic", "deep symmetric shadows",
     "technological omnipresence", "high",
     "700 million cameras in China", "central eye as divine judgment amid surveillance",
     False, None, None, None, None, None, False, None),

    ("Q34", 4, "Ícones dourados sobre multidão", "Overhead vertical of P&B Beijing street crowd, small golden camera icons floating above each pair of heads",
     "China e a Marca",
     "overhead", "top-down 90 degrees", 35, "f/5.6", "deep",
     "a dense Beijing street seen from directly above with hundreds of pedestrians in black-and-white winter clothing", "small floating golden camera icons, one per every two people, hovering just above their heads",
     "Crowd entirely desaturated. Camera icons in rich metallic gold.",
     ["crowded Beijing street", "winter coats", "floating golden camera icons"],
     "a Beijing commercial street seen from above", "overcast daylight", "vertiginous statistic",
     "centered grid",
     "golden camera icons in rich metallic gold", "desaturated black-and-white crowd",
     "overcast overhead soft light", "cold ambient fill", "gold rim on each icon",
     "dystopian cinematic", "soft overhead shadows",
     "vertiginous statistic", "high",
     "one camera for every two inhabitants", "icons as abstraction of total surveillance",
     False, None, None, None, None, None, False, None),

    ("Q35", 4, "Tela de smartphone — pontuação 350", "Medium over-the-shoulder of smartphone in hand, large 350 score in crimson with descending golden bar, worried face blurred behind",
     "China e a Marca",
     "medium", "over-the-shoulder", 50, "f/2.8", "razor-thin",
     "a modern smartphone held in a hand, screen showing a large three-digit number 350 in blood-red with a descending golden progress bar below", "the crisp crimson number 350 at screen center",
     "Behind in blur, an anxious Asian face in P&B watching.",
     ["smartphone in hand", "large 350 score", "descending golden bar", "anxious blurred face behind"],
     "a Chinese subway car", "evening commute", "algorithmic judgment",
     "rule of thirds",
     "screen score in rich blood-red and gold", "desaturated black-and-white face and subway behind",
     "cold screen glow on face", "deep negative fill", "gold rim on phone edge",
     "stark cinematic", "soft focused shadows",
     "algorithmic judgment", "high",
     "Social Credit System scoring", "number as verdict on human worth",
     True, "350", None,
     "bold modern digital display numerals in blood-crimson",
     "illuminated LED-style display on smartphone screen",
     "center of smartphone screen, large and dominant",
     True, None),

    ("Q36", 4, "Portão de embarque bloqueado", "Wide of modern P&B airport gate, crimson-robed silhouette barred by pulsating red gate, plane waiting behind",
     "China e a Marca",
     "wide", "straight-on symmetric", 35, "f/5.6", "deep",
     "a modern airport boarding gate with a pulsating red security barrier", "a single human silhouette in vivid crimson robe blocked mid-step by the red gate",
     "Airliner visible through panoramic window behind. Cold P&B terminal.",
     ["modern boarding gate", "pulsating red security barrier", "crimson-robed silhouette", "airliner behind window"],
     "an international airport gate", "late evening terminal light", "mechanical exclusion",
     "strict centered symmetry",
     "silhouette in rich crimson", "desaturated black-and-white terminal and airliner",
     "cold fluorescent overhead plus red pulse from gate", "deep negative fill", "gold rim on figure's shoulders",
     "stark dystopian cinematic", "hard barrier shadows",
     "mechanical exclusion", "high",
     "low score denies flight", "gate as digital excommunication",
     False, None, None, None, None, None, False, None),

    ("Q37", 4, "Telão de rostos desconfiáveis", "Wide low-angle of Chinese urban plaza P&B with giant LED screen showing blurred faceless humans, scrolling red name list",
     "China e a Marca",
     "wide", "low angle", 24, "f/5.6", "deep",
     "a massive LED billboard in a Chinese urban plaza at night displaying rows of blurred faceless human outlines", "a scrolling red banner at the screen's bottom listing names in blood-crimson characters",
     "Silhouetted crowd below watching. Desaturated cityscape behind.",
     ["giant LED billboard", "blurred faceless human outlines", "scrolling red name list", "silhouetted watching crowd"],
     "a Chinese urban plaza at night", "night with LED screen glow", "public humiliation",
     "rule of thirds",
     "LED screen red list in rich blood-crimson", "desaturated black-and-white plaza and crowd",
     "cold LED screen glow downward on crowd", "deep negative fill", "gold rim on billboard frame",
     "stark dystopian cinematic", "hard long crowd shadows",
     "public humiliation", "high",
     "face exhibited on public screens", "the untrustworthy as public spectacle",
     False, None, None, None, None, None, False, None),

    ("Q38", 4, "Marca dourada em forma de QR na palma", "Close-up macro of adult human palm with glowing golden QR-code mark engraved, modern cash register behind in P&B",
     "China e a Marca",
     "close-up", "macro", 85, "f/2.0", "razor-thin",
     "a human adult palm facing upward with a glowing geometric golden mark in the shape of a stylized QR code embedded in the skin", "the luminous golden QR mark at the palm center",
     "Modern checkout register desaturated behind. Cold blue ambient.",
     ["human palm", "glowing golden QR-style mark", "modern checkout register behind"],
     "a modern store checkout", "store LED lighting", "prophetic revelation made modern",
     "rule of thirds",
     "palm and QR mark in rich warm gold", "desaturated black-and-white register and background",
     "cold overhead store LED plus warm glow from the mark", "deep negative fill", "gold rim on palm edge",
     "stark cinematic", "soft focused shadows",
     "prophetic revelation made modern", "high",
     "Revelation 13:16 — mark on the right hand", "QR as modern incarnation of the ancient mark",
     False, None, None, None, None, None, False, None),

    ("Q39", 4, "Caixa rejeitando — maçã caindo", "Medium of supermarket checkout P&B, customer's hand extended but scanner pulsing red denial, vivid red apple falling in slow motion",
     "China e a Marca",
     "medium", "3/4", 50, "f/4.0", "moderate",
     "a modern supermarket checkout counter with a customer's empty hand extended", "a vivid rich red apple caught mid-fall below the hand, scanner pulsing red above",
     "Customer body in P&B. Scanner and counter desaturated. Red pulse and apple in rich warm tones.",
     ["customer extended hand", "red pulsing scanner", "falling vivid red apple", "supermarket counter"],
     "a supermarket checkout", "cold store LED", "divinely anticipated exclusion",
     "rule of thirds",
     "red apple in rich crimson", "desaturated black-and-white customer and counter",
     "cold LED overhead plus red scanner pulse", "deep negative fill", "gold rim on apple skin",
     "stark dystopian cinematic", "soft falling shadow",
     "divinely anticipated exclusion", "high",
     "none shall buy or sell without the mark", "apple as lost Edenic commerce",
     False, None, None, None, None, None, False, None),

    ("Q40", 4, "CBDC — moeda holográfica central", "Wide symmetric of P&B flags of many nations in semicircle, holographic golden digital coin floating at center with binary code swirl",
     "China e a Marca",
     "wide", "straight-on symmetric", 35, "f/5.6", "deep",
     "a semicircle of desaturated national flags from many countries", "a floating holographic golden digital coin at center with orbiting binary code particles",
     "Floating digital ember-like particles. Deep black ambient.",
     ["semicircle of national flags", "floating golden holographic coin", "orbiting binary code"],
     "a symbolic global monetary summit", "eternal twilight", "global monetary revolution",
     "strict centered symmetry",
     "holographic coin and binary in rich gold and amber", "desaturated black-and-white flags",
     "divine vertical gold light on coin", "deep black ambient", "gold rim on flag edges",
     "epic cinematic", "deep symmetric shadows",
     "global monetary revolution", "high",
     "130 countries implementing CBDC", "digital coin as prophesied totalization",
     False, None, None, None, None, None, False, None),

    ("Q41", 4, "Moeda programável cortada por código vermelho", "Overhead of dark desk, central golden digital coin being sliced by horizontal red code line, P&B servers behind",
     "China e a Marca",
     "overhead", "top-down 90 degrees", 40, "f/4.0", "moderate",
     "a dark obsidian desk with a rich golden digital coin at center", "a horizontal bright red glowing code line slicing the coin in half",
     "Background: blurred data center servers in desaturated black-and-white. Floating digital particles.",
     ["golden digital coin", "red code line slicing", "dark obsidian desk", "blurred P&B servers"],
     "a programmable currency command room", "sterile eternal", "total transactional power",
     "centered symmetry",
     "coin and code in rich gold and crimson-red", "desaturated black-and-white servers and desk edges",
     "vertical cold light plus red code emission", "deep negative fill", "gold rim on coin edges",
     "stark cinematic", "soft focused shadows",
     "total transactional power", "high",
     "programmable currency with expiry, region, product blocks", "code as new law",
     False, None, None, None, None, None, False, None),

    ("Q42", 4, "Fragmento de Qumran sob luvas brancas", "Close-up macro of aged Qumran parchment fragment with Hebrew letters, white-gloved archaeologist hands in P&B",
     "China e a Marca",
     "close-up", "macro", 85, "f/2.8", "razor-thin",
     "an ancient aged parchment fragment from the Qumran scrolls with clearly visible Hebrew letters in faded ink", "the central Hebrew characters of Daniel illuminated by museum light",
     "White-gloved archaeologist's hands in P&B carefully holding the fragment.",
     ["aged Qumran parchment fragment", "faded Hebrew letters", "white-gloved hands", "museum lab"],
     "the Israel Antiquities Authority lab", "museum lab light", "archaeological evidence",
     "rule of thirds",
     "parchment in rich ochre and gold", "desaturated black-and-white gloves and lab background",
     "cold museum lab overhead plus warm directional on parchment", "soft ambient fill", "gold rim on parchment edges",
     "somber cinematic", "soft focused shadows",
     "archaeological evidence", "medium",
     "Daniel dated to 2nd century BC before events", "parchment as irrefutable witness",
     False, None, None, None, None, None, False, None),

    ("Q43", 4, "Linha do tempo dourada", "Wide panoramic timeline fresco: II BC parchment → Rome column → XX century telegraph → today cameras P&B, gold foreground dessaturated background",
     "China e a Marca",
     "wide panoramic", "eye level", 28, "f/8.0", "deep",
     "a wide horizontal timeline fresco with four symbolic nodes representing II BC parchment, Roman column, 20th century telegraph, contemporary camera", "the central vertical golden axis connecting all four nodes",
     "Foreground nodes in rich gold and crimson. Background timeline band desaturated.",
     ["parchment node II BC", "Roman column node", "telegraph node 20th century", "modern camera node", "horizontal timeline"],
     "a symbolic prophetic chronology", "eternal twilight", "prophetic precedence",
     "strict horizontal linear composition",
     "timeline nodes in rich gold, crimson and ochre", "desaturated black-and-white background timeline",
     "horizontal directional gold axis", "cold ambient edge fill", "gold rim on each node",
     "epic cinematic", "deep panoramic shadows",
     "prophetic precedence", "high",
     "Daniel preceded every surveillance technology", "timeline as divine foresight",
     False, None, None, None, None, None, False, None),

    ("Q44", 4, "Maquete pirâmide de controle", "Medium overhead 60 degrees of architectural maquette pyramid in rich gold and crimson, three levels: commerce base, transactions middle, identity top",
     "China e a Marca",
     "medium overhead", "60 degree tilt", 40, "f/5.6", "moderate",
     "a detailed architectural maquette of a three-tier control pyramid on an architect's drafting table", "the golden top level labeled IDENTIDADE at apex",
     "The three levels clearly visible: base COMÉRCIO, middle TRANSAÇÕES, top IDENTIDADE. Background: architect's studio P&B.",
     ["three-tier architectural maquette", "tier labels in gold", "drafting tools beside"],
     "an architect's studio", "desk lamp night", "eternal project",
     "rule of thirds",
     "maquette in rich gold, crimson and ochre", "desaturated black-and-white studio background",
     "warm focused desk lamp from camera-right", "amber bounce from model", "gold rim on tier edges",
     "chiaroscuro apocalyptic", "soft focused shadows",
     "eternal project", "medium",
     "architecture of total control is ancient", "pyramid as model of concentration",
     True, "IDENTIDADE\nTRANSAÇÕES\nCOMÉRCIO", None,
     "engraved architectural label capital letters in polished gold",
     "etched on the three tiers of the maquette",
     "three horizontal rows, one per tier, top to bottom",
     True, None),

    ("Q45", 4, "Winston Smith no apartamento exíguo", "Medium lateral of gaunt P&B man in gray suit seated at narrow table with single gold-labeled GIN VITÓRIA bottle and ration can, giant telecrania eye on back wall",
     "China e a Marca",
     "medium", "lateral", 40, "f/4.0", "moderate",
     "a gaunt middle-aged man in a drab gray suit with tired face seated at a narrow formica table in a cramped apartment", "on the table, a single rich gold-labeled glass bottle reading GIN VITÓRIA beside a dented ration can",
     "Behind him, a giant wall-mounted telecrania screen in P&B showing a stylized eye icon.",
     ["gaunt Winston-like man", "narrow formica table", "GIN VITÓRIA gold-labeled bottle", "dented ration can", "giant telecrania screen with eye"],
     "a cramped Oceania apartment", "cold fluorescent evening", "totalitarian precarity",
     "rule of thirds",
     "bottle and ration label in rich gold and crimson", "desaturated black-and-white Winston, room and telecrania",
     "cold fluorescent overhead plus blue telecrania glow", "deep negative fill", "gold rim on bottle edge",
     "stark dystopian cinematic", "deep hard shadows",
     "totalitarian precarity", "high",
     "no bank account — the Party owns everything", "bottle as sole luxury permitted",
     True, "GIN VITÓRIA", None,
     "bold propaganda-era serif capital letters in warm printed gold",
     "printed label on rectangular glass bottle",
     "center of the bottle label facing camera",
     True, None),

    ("Q46", 4, "Dragão colossal e besta de sete cabeças", "Wide of colossal P&B dragon coiled around stone throne, golden-crimson seven-headed beast enthroned, silhouetted worshipping crowd below",
     "China e a Marca",
     "wide", "low angle", 24, "f/8.0", "deep",
     "a colossal desaturated dragon coiled around a massive stone throne", "a seven-headed beast in rich crimson and gold sitting on the throne, each head slightly different",
     "A tiny silhouetted worshipping crowd kneeling at the base. Floating embers in storm sky.",
     ["colossal P&B dragon", "stone throne", "seven-headed crimson and gold beast", "silhouetted worshipping crowd", "floating embers"],
     "a symbolic apocalyptic plaza", "stormy eternal dusk", "apocalyptic adoration",
     "rule of thirds with throne at center",
     "seven-headed beast in rich crimson and gold", "desaturated black-and-white dragon, throne and crowd",
     "divine storm light from above on throne", "deep cold ambient fill", "gold rim on beast heads",
     "epic apocalyptic", "deep long throne shadows",
     "apocalyptic adoration", "high",
     "Revelation 13:4 — who can war against it", "seven heads as totalizing power",
     False, None, None, None, None, None, False, None),

    # PARTE 5 (Q47–Q60) — O'BRIEN + CTA
    ("Q47", 5, "O'Brien e Winston na cela", "Medium of elegant middle-aged man in dark suit P&B with emotionless eyes, Winston bound in metal chair in rich crimson worn robe in foreground",
     "O'Brien e Esperança",
     "medium", "3/4", 50, "f/2.8", "razor-thin",
     "an elegant middle-aged man in a tailored dark suit standing tall with cold emotionless eyes, hands clasped behind his back", "in the foreground, a younger gaunt man bound to a metal interrogation chair in worn crimson and ochre robes",
     "Harsh side light from camera-left. Clinical tile chamber P&B.",
     ["O'Brien in dark suit", "cold emotionless eyes", "bound Winston in metal chair", "worn crimson robe", "P&B clinical chamber"],
     "Room 101 in the Ministry of Love", "clinical interrogation light", "traitorous revelation",
     "rule of thirds",
     "Winston's robe in rich crimson and ochre", "desaturated black-and-white O'Brien and chamber",
     "harsh cold directional side light", "deep negative fill", "gold rim on Winston's shoulder",
     "stark dystopian cinematic", "deep hard shadows",
     "traitorous revelation", "high",
     "the torturer whom Winston thought was an ally", "robe color as last shred of humanity",
     False, None, None, None, None, None, False, None),

    ("Q48", 5, "Boca pronunciando — não existe", "Extreme close-up of thin P&B adult male lips pronouncing single word, rich red blood drop at corner",
     "O'Brien e Esperança",
     "extreme close-up", "straight-on", 100, "f/2.0", "razor-thin",
     "an extreme close-up of a middle-aged man's thin desaturated lips mid-speech, pronouncing a single word", "a rich red blood drop running from the corner of the mouth",
     "Dark ash particles drifting. Stubble visible.",
     ["thin P&B adult male lips", "mid-pronunciation", "rich red blood drop", "dark ash particles"],
     "interrogation chamber extreme proximity", "clinical side light", "final sentence",
     "centered macro",
     "blood drop in rich crimson", "desaturated black-and-white lips and skin",
     "harsh side light sculpting lips", "deep negative fill", "gold rim on wet blood",
     "stark dystopian cinematic", "deep hard shadows",
     "final sentence", "high",
     "There is no hope — the system's verdict", "blood as cost of the lie",
     False, None, None, None, None, None, False, None),

    ("Q49", 5, "Díptico Oceânia vs Apocalipse", "Wide diptych: left gray P&B chamber of Winston without exit; right glorious golden gate ajar with divine vertical light; vertical ember seam between",
     "O'Brien e Esperança",
     "wide", "straight-on symmetric", 35, "f/5.6", "deep",
     "a wide symmetric diptych with a gray dead-end interrogation chamber on the left and a partially open golden celestial gate on the right", "a vertical line of rising embers separating the two halves",
     "Left: cold P&B dead chamber. Right: warm divine gold light spilling from ajar gate.",
     ["dead gray chamber left", "celestial gold gate right", "vertical ember seam", "divine vertical light"],
     "symbolic bifurcated eternity", "eternal twilight vs divine dawn", "hope vs despair",
     "strict symmetric diptych",
     "right side in rich divine gold and crimson", "desaturated black-and-white left chamber",
     "cold dead light left, warm divine light right", "deep negative fill center", "gold rim on gate edges",
     "epic cinematic", "deep dual-axis shadows",
     "hope vs despair", "high",
     "Apocalypse continues beyond the sentence", "gate as divine continuation",
     False, None, None, None, None, None, False, None),

    ("Q50", 5, "Quarto de hospital — morte silenciosa", "Medium of 1950s P&B hospital room, bed with gaunt man covered by white sheet, vintage gold-ochre typewriter beside, lit candle, rainy window",
     "O'Brien e Esperança",
     "medium", "3/4", 40, "f/4.0", "moderate",
     "a 1950s hospital room with a simple iron-frame bed holding a gaunt man covered to the chest by a plain white sheet", "a vintage typewriter in rich gold and ochre on the bedside table beside a lit candle",
     "Rainy window behind. P&B room. Warm candle glow.",
     ["1950s iron-frame hospital bed", "gaunt covered patient", "vintage typewriter", "lit white candle", "rainy window"],
     "University College Hospital London 1950", "late night, candlelight", "silent death",
     "rule of thirds",
     "typewriter and candle in rich gold and ochre", "desaturated black-and-white bed, patient and room",
     "warm candle from bedside table", "cold ambient blue from window", "gold rim on typewriter keys",
     "somber cinematic", "soft focused shadows",
     "silent death", "medium",
     "Eric Blair dies seven months after publication", "typewriter as last companion",
     False, None, None, None, None, None, False, None),

    ("Q51", 5, "Título original riscado — The Last Man in Europe", "Close-up macro of typewritten manuscript cover page in rich ochre and crimson, red-penned strike through THE LAST MAN IN EUROPE",
     "O'Brien e Esperança",
     "close-up", "macro", 85, "f/2.8", "razor-thin",
     "a typewritten manuscript title page on cream paper with vintage serif typeface reading THE LAST MAN IN EUROPE", "a single diagonal red pen strike scored across the title by a visible aged hand",
     "P&B office desk background. Floating dust.",
     ["typewritten manuscript cover", "vintage serif title", "red pen diagonal strike", "aged editor's hand"],
     "Orwell's publisher's desk 1948", "office lamp daylight", "final naming",
     "rule of thirds",
     "manuscript and red strike in rich ochre and crimson", "desaturated black-and-white desk and hand",
     "warm desk lamp from camera-right", "soft amber bounce from paper", "gold rim on paper edge",
     "somber cinematic", "soft focused shadows",
     "final naming", "medium",
     "The Last Man in Europe — original title", "strike as editorial rebirth of title",
     True, "THE LAST MAN IN EUROPE", None,
     "vintage typewriter serif uppercase letters in warm printed ochre, red diagonal pen strike over",
     "typed on manuscript cover with red ink strike overlay",
     "centered upper third of page, with red strike diagonal",
     True, None),

    ("Q52", 5, "Calendário 1948 → 1984", "Medium overhead 45 of P&B wall calendar with 1948 struck through in rich crimson, golden card beside reading 1984, embers floating",
     "O'Brien e Esperança",
     "medium overhead", "45 degree tilt", 40, "f/4.0", "moderate",
     "a 1940s wall calendar page with the year 1948 printed bold at top, struck through by a rich crimson diagonal pen line", "beside the calendar, a golden printed card with 1984 in elegant serif numerals",
     "Desk surface in P&B. Floating embers.",
     ["1940s wall calendar", "1948 with crimson strike", "golden card 1984", "floating embers"],
     "Orwell's working desk", "overcast daylight", "symbolic editorial act",
     "rule of thirds",
     "1948 strike and 1984 card in rich crimson and gold", "desaturated black-and-white calendar and desk",
     "soft overcast daylight from above", "cold ambient fill", "gold rim on card edges",
     "somber cinematic", "soft focused shadows",
     "symbolic editorial act", "medium",
     "1984 as 1948 inverted", "digits as temporal code",
     True, "1948    1984", None,
     "1948 in printed calendar serif with crimson strike; 1984 in elegant engraved serif gold",
     "calendar print for 1948 with pen strike; printed card for 1984",
     "left: calendar 1948 with red strike; right: gold card 1984",
     True, None),

    ("Q53", 5, "Daniel sem cor no rosto", "Close-up frontal of aged Daniel in partially desaturated rich tones with horror visionary expression, four silhouetted beasts in P&B behind",
     "O'Brien e Esperança",
     "close-up", "frontal", 85, "f/2.0", "razor-thin",
     "an aged prophet Daniel with weathered Semitic features and long white beard, face partially drained of color with a look of visionary horror", "his fixed wide-open eyes catching a cold distant glint",
     "Background: four dim silhouetted beasts in P&B.",
     ["aged prophet Daniel", "weathered Semitic features", "horror-fixed eyes", "four silhouetted beasts behind"],
     "a prophet's chamber after the vision", "night lamp", "prophetic trauma",
     "rule of thirds with eyes at upper third",
     "Daniel's beard and robe in desaturated rich warm tones", "desaturated black-and-white four beasts behind",
     "single cold oil lamp from camera-left", "deep negative fill", "faint gold rim on cheek",
     "chiaroscuro apocalyptic", "deep hard shadows",
     "prophetic trauma", "high",
     "left without color on his face for days", "beasts as persistent visual memory",
     False, None, None, None, None, None, False, None),

    ("Q54", 5, "Cavernas de Qumran sobre o Mar Morto", "Wide establisher of Qumran caves at dawn, rich crimson-gold sky, P&B rock and desert, tiny archaeologist figure at cave entrance",
     "CTA",
     "wide establisher", "eye level", 24, "f/11.0", "deep",
     "a wide landscape of Qumran caves above the Dead Sea at dawn", "a tiny archaeologist silhouette entering one of the caves at frame-right",
     "Rich crimson and gold dawn sky. Desaturated rock and desert. Wind drifting sand.",
     ["Qumran cave opening", "Dead Sea below", "tiny archaeologist silhouette", "rich dawn sky"],
     "the cliffs of Qumran over the Dead Sea", "dawn", "monumental discovery",
     "rule of thirds with caves at lower third",
     "sky in rich crimson, gold and ochre", "desaturated black-and-white rock, desert and Dead Sea",
     "dawn gold directional light from camera-left", "cold blue ambient shadow fill", "gold rim on cave edges",
     "epic cinematic", "long soft dawn shadows",
     "monumental discovery", "medium",
     "Dead Sea scrolls discovery 1947-1956", "caves as prophetic vaults",
     False, None, None, None, None, None, False, None),

    ("Q55", 5, "Vitrine do Israel Antiquities Authority", "Medium frontal of modern climate-controlled P&B display case with rich ochre and gold illuminated Daniel parchment fragment, golden plaque ISRAEL ANTIQUITIES AUTHORITY",
     "CTA",
     "medium", "frontal", 50, "f/4.0", "moderate",
     "a modern climate-controlled museum display case with a small illuminated ancient parchment fragment at its center", "a heavy golden engraved plaque below the case reading ISRAEL ANTIQUITIES AUTHORITY",
     "Museum hall in P&B. Parchment in rich ochre and gold. Soft reverence.",
     ["climate-controlled display case", "illuminated Daniel fragment", "gold museum plaque", "P&B museum hall"],
     "the Israel Antiquities Authority museum hall", "museum spotlight", "unquestionable evidence",
     "centered symmetry",
     "parchment and plaque in rich ochre and gold", "desaturated black-and-white case and hall",
     "warm museum spotlight from above", "cool ambient hall fill", "gold rim on plaque and case",
     "somber cinematic", "soft focused shadows",
     "unquestionable evidence", "medium",
     "Daniel fragments catalogued and verified", "museum as sanctuary of truth",
     True, "ISRAEL ANTIQUITIES AUTHORITY", None,
     "bold engraved serif uppercase letters in polished warm gold",
     "engraved on a heavy rectangular gold plaque",
     "centered below the display case",
     True, None),

    ("Q56", 5, "Quatro pergaminhos em cruz", "Overhead symmetric of four scrolls in cross arrangement on stone table, each with a prophetic phrase, central golden hourglass",
     "CTA",
     "overhead", "top-down 90 degrees", 35, "f/5.6", "deep",
     "four aged parchment scrolls arranged in a cross pattern on a stone altar table", "a central golden ornate hourglass at the crossing point",
     "Each scroll bears one Portuguese prophetic phrase in gothic calligraphy. Background P&B.",
     ["four aged scrolls in cross", "central golden hourglass", "stone altar surface"],
     "a symbolic prophetic altar", "candlelit night", "prophetic synthesis",
     "strict cross radial symmetry",
     "scrolls and hourglass in rich gold, crimson and ochre", "desaturated black-and-white stone surface",
     "warm vertical overhead candle-like light", "amber bounce from parchments", "gold rim on scrolls and hourglass",
     "chiaroscuro apocalyptic", "soft radial shadows",
     "prophetic synthesis", "high",
     "three prophetic actions plus one question", "hourglass as center of time",
     True, "MUDAR OS TEMPOS\nMUDAR A LEI\nCOMPRAR OU VENDER\nQUEM PODE GUERREAR", None,
     "ancient gothic Portuguese uppercase calligraphy in aged gold ink",
     "inscribed on each of the four scrolls",
     "four scrolls radially at cardinal points: top, right, bottom, left",
     True, "Four phrases must each appear on its own scroll, in Portuguese, letter by letter as written. Sacred prophetic text."),

    ("Q57", 5, "Tríade Daniel, Orwell, hoje", "Wide triadic panoramic: left Daniel looking up (crimson/gold), center Orwell typewriting (gray-ochre), right contemporary world P&B with drones and screens, embers connecting all",
     "CTA",
     "wide panoramic", "eye level", 28, "f/8.0", "deep",
     "a wide panoramic triadic composition with three planes: left Daniel the prophet looking upward in crimson and gold robes, center Orwell typewriting in gray and ochre suit, right a contemporary surveillance scene with drones and screens", "the three planes linked by a continuous horizontal stream of floating embers across the whole frame",
     "Left and center in rich warm tones. Right plane desaturated.",
     ["Daniel looking upward", "Orwell typewriting", "contemporary drones and screens", "horizontal ember stream linking three"],
     "symbolic transhistorical panorama", "eternal twilight", "epic synthesis",
     "strict triadic panoramic",
     "left and center in rich crimson, ochre and gold", "desaturated black-and-white right plane",
     "horizontal directional warm light crossing frame", "cold ambient edge fill", "gold rim on all three figures",
     "epic cinematic", "deep panoramic shadows",
     "epic synthesis", "high",
     "Daniel saw, Orwell named, world builds", "embers as prophetic thread across time",
     False, None, None, None, None, None, False, None),

    ("Q58", 5, "Mão sobre bifurcação", "Close-up of generic human hand in rich crimson and gold suspended over forked path: one gold rising to light, one P&B descending to shadow",
     "CTA",
     "close-up", "slight high angle", 85, "f/2.8", "razor-thin",
     "a human hand seen from above in warm vivid tones, suspended just above a forking path engraved on stone", "the golden path rising into divine light at left, the desaturated path descending into shadow at right",
     "Floating embers around the hand indicating hesitation.",
     ["human hand in warm tones", "forked stone path", "rising golden path", "descending shadow path"],
     "a symbolic choice space", "eternal twilight", "moral summons",
     "rule of thirds",
     "hand and golden path in rich crimson and gold", "desaturated black-and-white descending path",
     "divine vertical light on hand", "cold negative fill on shadow side", "gold rim on knuckles",
     "chiaroscuro apocalyptic", "soft focused shadows",
     "moral summons", "high",
     "what you do with what you know, while there's still choice", "forking path as free will",
     False, None, None, None, None, None, False, None),

    ("Q59", 5, "Três portões — Verdade, Paz, Amor", "Wide symmetric of three giant arched gates each with golden plaque VERDADE, PAZ, AMOR, P&B crowd with smartphones below",
     "CTA",
     "wide", "straight-on symmetric", 24, "f/8.0", "deep",
     "three colossal arched stone gates arranged in a row", "each gate bearing a golden engraved plaque at its keystone reading VERDADE PAZ AMOR left to right",
     "A vast crowd of silhouetted contemporary people below with raised smartphones glowing cold blue, all in P&B.",
     ["three arched stone gates", "three golden keystone plaques", "silhouetted crowd", "raised smartphones"],
     "a symbolic final public square", "eternal twilight", "final interpellation",
     "strict symmetric triadic",
     "three plaques and gate edges in rich gold and crimson", "desaturated black-and-white gates, crowd and phones",
     "divine vertical light on three gates", "cold crowd fill from phone glow", "gold rim on each plaque",
     "epic cinematic", "deep symmetric shadows",
     "final interpellation", "high",
     "which ministry do you see operating today", "three gates as choice of recognition",
     True, "VERDADE        PAZ        AMOR", None,
     "bold engraved serif uppercase letters in polished warm gold",
     "engraved on keystone plaques of each gate",
     "three keystones top center of each gate",
     True, "Three separate words on three separate plaques in Portuguese. Each plaque on its own gate keystone."),

    ("Q60", 5, "Encerramento — Bíblia selada", "Overhead of open Bible at Daniel 7 sealed by rich golden wax seal at lower corner, pen and candle flickering last ember",
     "CTA",
     "overhead", "top-down 90 degrees", 35, "f/4.0", "moderate",
     "an open leather Bible page showing Daniel 7 with ornate gothic typography", "a rich golden wax seal imprinted at the lower corner of the page, and a feather quill with a single dying candle beside",
     "A final solitary ember rising from the candle. Desaturated stone surface around.",
     ["open Bible at Daniel 7", "golden wax seal", "feather quill", "dying candle", "single rising ember"],
     "a closing prophetic desk", "candle dying night", "intimate invitation, final seal",
     "centered symmetry",
     "Bible, seal and candle in rich gold, crimson and ochre", "desaturated black-and-white stone edges",
     "warm vertical dying candlelight from above", "amber bounce from pages", "gold rim on wax seal",
     "chiaroscuro apocalyptic", "soft focused shadows",
     "intimate invitation, final seal", "medium",
     "scripture sealed — answer in comments", "dying ember as invitation to next viewer",
     False, None, None, None, None, None, False, None),
]

assert len(FRAMES) == 60, f"expected 60 frames, got {len(FRAMES)}"

for F in FRAMES:
    try:
        (qid, parte, scene_title, narrative_beat, ato,
         shot_type, angle, fl, ap, dof,
         subject_primary, focal, secondary, props,
         location, tod, atmo,
         rule, fg, bg,
         key, fill, rim, light_mood, sh_quality,
         emotion, tension,
         sym_p, sym_s,
         text_enabled, text_content, text_secondary, text_font, text_medium, text_placement,
         pro, text_note) = F
    except ValueError as e:
        print(f"SKIP {F[0]} — tuple size {len(F)}: {e}")
        continue

    j = base(qid, parte, scene_title, narrative_beat, ato)
    j["shot"] = shot(shot_type, angle, fl, ap, dof)
    j["subject"] = {
        "primary": subject_primary,
        "focal_point": focal,
        "secondary": secondary,
        "props": props,
    }
    j["environment"] = {"location": location, "time_of_day": tod, "atmosphere": atmo}
    j["composition"] = {
        "rule": rule,
        "foreground": fg,
        "background": bg,
        "safe_zone_for_overlay": "lower 20% of frame",
    }
    j["lighting"] = {
        "key_light": key,
        "fill_light": fill,
        "rim_light": rim,
        "mood": "chiaroscuro apocalyptic",
        "shadow_quality": sh_quality,
    }
    j["style"] = STYLE_DEFAULT
    j["mood"] = {"emotion": emotion, "tension": tension}
    j["symbolism"] = {"primary": sym_p, "secondary": sym_s}
    j["negative_as_positive"] = NEG_DEFAULT
    if text_enabled:
        d = {
            "enabled": True,
            "content": text_content,
            "font_style": text_font,
            "medium": text_medium,
            "placement": text_placement,
            "legibility": "crisp and readable",
            "language": "Portuguese",
        }
        if text_secondary:
            d["content_secondary"] = text_secondary
        j["in_scene_text"] = d
    else:
        j["in_scene_text"] = {"enabled": False}

    j["api_call_hints"] = api_hints(pro=pro, text_note=text_note)

    path = OUT / f"{qid}.json"
    path.write_text(json.dumps(j, ensure_ascii=False, indent=2), encoding="utf-8")

print(f"Geradas {len(FRAMES)} JSONs em {OUT}")
# Count pro overrides
pros = sum(1 for F in FRAMES if F[-2])
print(f"Model pro overrides: {pros}")
