"""Gera JSONs Q03-Q60 para video-017-claude-skynet baseado no storyboard.
Uso: python _tools/tmp_gen_video017_jsons.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "canais" / "sinais-do-fim" / "videos" / "video-017-claude-skynet" / "6-prompts-imagem"
OUT.mkdir(parents=True, exist_ok=True)

STYLE_REF = {
    "primary_image_url": "canais/sinais-do-fim/_config/style_refs/sinais_dark.png",
    "weight": 0.85,
    "transfer_targets": ["color_palette", "lighting", "texture", "atmosphere", "film_grain"],
    "textual_description": "dark cinematic chiaroscuro, Caravaggio-inspired, foreground in rich warm tones (crimson, amber, gold) with background in desaturated black-and-white, film grain, candlelight, floating orange embers"
}

STYLE_BLOCK = {
    "film_stock": "Kodak Portra 800 pushed two stops",
    "post_processing": "halation, crushed blacks, amber highlights, anamorphic lens flares",
    "texture_detail": "35mm film grain, dust particles, floating orange embers"
}

NEG = [
    "clean frame without visible text or watermarks",
    "photorealistic documentary cinematography, not illustrated or cartoon",
    "analog film photography aesthetic, no digital art flatness",
    "muted desaturated background palette, warm saturated foreground only",
    "tack-sharp focus on primary subject"
]

SHADOWS = "deep hard-edged Caravaggio shadows"

# Definição de cada quadro: (parte, ato, shot_type, focal, aperture, dof, rule, scene_title, beat, subject_primary, focal_point, secondary, props, location, time_of_day, atmosphere, foreground, midground, background, key, fill, rim, mood_light, emotion, tension, sym_p, sym_s, pro=False)
# Ato parte_suno mapping: PARTE1 Q1-2, PARTE2 Q3-12, PARTE3 Q13-24... seguindo estrutura storyboard
# PARTE1: Q1, Q2 (gancho)
# PARTE2: Q3-Q12 (julgamento automático)
# PARTE3: Q13-Q24 (máquina que já existe)
# PARTE4: Q25-Q37 (João em Patmos)
# PARTE5: Q38-Q50 (nome que você usa todo dia)
# PARTE6: Q51-Q60 (fazer com isso) [aqui mapearei para PARTE5 pois o áudio tem 5 partes]

def parte_for(q):
    if q <= 2: return 1
    if q <= 12: return 2
    if q <= 24: return 3
    if q <= 37: return 4
    if q <= 50: return 5
    return 5  # Q51-60 continuam na parte 5 (fechamento)

ATO = {
    1: "Gancho", 2: "Gancho",
    3: "Julgamento", 4: "Julgamento", 5: "Julgamento", 6: "Julgamento",
    7: "Julgamento", 8: "Julgamento", 9: "Julgamento", 10: "Julgamento",
    11: "Julgamento", 12: "Julgamento",
    13: "Máquina", 14: "Máquina", 15: "Máquina", 16: "Máquina",
    17: "Máquina", 18: "Máquina", 19: "Máquina", 20: "Máquina",
    21: "Máquina", 22: "Máquina", 23: "Máquina", 24: "Máquina",
    25: "Patmos", 26: "Patmos", 27: "Patmos", 28: "Patmos",
    29: "Patmos", 30: "Patmos", 31: "Patmos", 32: "Patmos",
    33: "Patmos", 34: "Patmos", 35: "Patmos", 36: "Patmos", 37: "Patmos",
    38: "Claude", 39: "Claude", 40: "Claude", 41: "Claude",
    42: "Claude", 43: "Claude", 44: "Claude", 45: "Claude",
    46: "Claude", 47: "Claude", 48: "Claude", 49: "Claude", 50: "Claude",
    51: "Fechamento", 52: "Fechamento", 53: "Fechamento", 54: "Fechamento",
    55: "Fechamento", 56: "Fechamento", 57: "Fechamento", 58: "Fechamento",
    59: "Fechamento", 60: "Fechamento"
}

# Quadros críticos marcados como 'pro' (máx 8): Q01, Q07, Q10, Q28, Q31, Q44, Q46, Q60
PRO_QUADROS = {1, 7, 10, 28, 31, 44, 46, 60}

# Tabela de quadros Q03-Q60 (Q01, Q02 já criados manualmente)
FRAMES = {
    3: {
        "title": "Sistema Lavender", "beat": "Datacenter militar P&B com pergaminho e balança suspensa em dourado",
        "shot": "medium", "focal": 40, "aperture": "f/4.0", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a cavernous military subterranean datacenter with endless server racks and blinking LEDs in desaturated black-and-white",
        "focal_pt": "a suspended glowing parchment with a Roman scale tipping violently toward death side",
        "secondary": "The parchment hovers mid-air bathed in divine vertical golden light; the scale is forged in aged gold with crimson ribbons.",
        "props": ["rows of server racks with blinking LEDs", "floating illuminated parchment", "aged gold Roman balance scale", "crimson ribbons", "floating orange embers"],
        "loc": "a subterranean military datacenter corridor", "tod": "permanent cold artificial light",
        "atm": "mechanical judgment, profaned divine",
        "fg": "floating parchment and Roman scale in rich gold and crimson",
        "mg": "air with light particles and smoke",
        "bg": "desaturated black-and-white server racks extending to vanishing point",
        "key": "divine vertical golden beam on parchment", "fill": "cold blue server light",
        "rim": "gold on scale edges", "mood_l": "chiaroscuro apocalyptic",
        "emo": "mechanical judgment, sacred desecrated", "tens": "high",
        "sp": "algorithm usurping divine judgment", "ss": "scale tipping toward death"
    },
    4: {
        "title": "A velocidade", "beat": "Cronômetro bronze macro com brasas e silhuetas humanas desfocadas",
        "shot": "close-up", "focal": 100, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "an antique bronze pocket stopwatch in extreme macro, thin needle racing across seconds, cracked crystal face",
        "focal_pt": "the running second hand and cracked glass center",
        "secondary": "Orange embers fall over the cracked glass; behind the watch, desaturated ghostly silhouettes of a human crowd blur.",
        "props": ["aged bronze pocket stopwatch", "cracked crystal face", "falling orange embers", "ghost crowd silhouettes"],
        "loc": "indeterminate timeless void", "tod": "artificial lateral glow",
        "atm": "mortal urgency",
        "fg": "bronze stopwatch in aged gold and crimson",
        "mg": "cracked glass surface with ember particles",
        "bg": "desaturated black-and-white blurred human silhouettes",
        "key": "lateral crimson light on bronze", "fill": "faint amber bounce",
        "rim": "gold on needle", "mood_l": "chiaroscuro urgent",
        "emo": "mortal urgency, time collapsing", "tens": "maximum",
        "sp": "time as executioner", "ss": "fractured glass as shattered humanity"
    },
    5: {
        "title": "Unidade 8200", "beat": "Sala de guerra israelense com selo hexagonal heráldico suspenso",
        "shot": "wide", "focal": 28, "aperture": "f/5.6", "dof": "deep", "rule": "centered symmetry",
        "subj": "a vast Israeli underground war room in desaturated black-and-white with cold monitor panels and empty steel chairs in rows",
        "focal_pt": "a suspended hexagonal heraldic seal floating at the center in vivid gold and crimson",
        "secondary": "Divine vertical light pours from the ceiling onto the seal; low smoke drifts at floor level.",
        "props": ["cold military monitor panels", "empty steel chairs in rows", "floating hexagonal heraldic seal", "low drifting smoke"],
        "loc": "underground Israeli military war room", "tod": "permanent artificial light",
        "atm": "institutional secrecy",
        "fg": "floating hexagonal seal in rich gold and crimson",
        "mg": "empty steel chairs and low smoke",
        "bg": "desaturated black-and-white monitor walls extending",
        "key": "vertical divine golden beam on seal", "fill": "cold cyan monitor glow",
        "rim": "gold edge on seal", "mood_l": "chiaroscuro institutional",
        "emo": "secretive, monumental, imposing", "tens": "high",
        "sp": "military intelligence as modern priesthood", "ss": "seal as modern sigil"
    },
    6: {
        "title": "O mecanismo", "beat": "Overhead de pergaminho com diagrama de rede neural dourado e carmesim",
        "shot": "overhead", "focal": 50, "aperture": "f/4.0", "dof": "moderate", "rule": "centered overhead",
        "subj": "a top-down view over a dark marble table bearing an aged parchment schematic of a neural network with gold nodes connected by crimson threads",
        "focal_pt": "the central node of the neural network diagram",
        "secondary": "A scribe quill and ink bottle rest beside the parchment; ash particles drift in the air.",
        "props": ["aged parchment neural network schematic", "gold nodes", "crimson threads", "scribe quill", "ink bottle", "ash particles"],
        "loc": "a scholar's chamber with marble table", "tod": "candlelit late night",
        "atm": "cold analysis, hidden architecture",
        "fg": "parchment schematic in ochre, gold and crimson",
        "mg": "marble table with faint candle reflections",
        "bg": "desaturated black-and-white blurred server wall behind",
        "key": "candlelight raking across parchment", "fill": "amber bounce",
        "rim": "gold on quill", "mood_l": "chiaroscuro scholarly",
        "emo": "cold analysis, hidden architecture", "tens": "moderate",
        "sp": "the secret architecture of algorithmic judgment", "ss": "quill as complicit scribe"
    },
    7: {
        "title": "Vinte segundos", "beat": "Close-up extremo do olho do operador com números digitais refletidos",
        "shot": "extreme close-up", "focal": 100, "aperture": "f/2.0", "dof": "razor-thin", "rule": "centered",
        "subj": "an extreme macro of a terrified male human eye, crimson iris reflecting a vertical sequence of running green digital numbers, eyelid frozen open",
        "focal_pt": "the reflection of digits in the pupil",
        "secondary": "Pale skin surrounds the eye with shadowed veins; a faint golden halo glows behind the skull.",
        "props": ["terrified male human eye", "crimson iris", "reflected green digital numerals", "faint golden halo"],
        "loc": "indeterminate dark void with faint halo", "tod": "absolute darkness with single light",
        "atm": "paralyzed terror",
        "fg": "the eye in rich crimson and gold reflections",
        "mg": "pale skin and shadowed eyelashes",
        "bg": "absolute black void with faint gold halo",
        "key": "green digital screen light into pupil", "fill": "faint gold halo behind head",
        "rim": "gold on eyelashes", "mood_l": "chiaroscuro paralyzed",
        "emo": "paralyzed terror", "tens": "maximum",
        "sp": "human witness frozen by machine judgment", "ss": "reflected numbers as sentence"
    },
    8: {
        "title": "Aprovação automática", "beat": "Mão humana inerte sobre botão vermelho pulsante, monitores ao fundo",
        "shot": "medium", "focal": 50, "aperture": "f/2.8", "dof": "moderate", "rule": "asymmetric",
        "subj": "a pale unadorned human hand hovering inert above a pulsing red button on a military console",
        "focal_pt": "the pulsing red button under the hand",
        "secondary": "Behind the hand, a row of desaturated monitors display descending lists of codenames.",
        "props": ["pale human hand", "pulsing red console button", "row of military monitors", "descending codename lists"],
        "loc": "a military command console station", "tod": "permanent artificial red-light alert",
        "atm": "moral abdication",
        "fg": "hand and button in rich crimson and gold alert light",
        "mg": "console surface",
        "bg": "desaturated black-and-white monitors with list text blurred",
        "key": "pulsing crimson alert light from button", "fill": "faint amber console underlight",
        "rim": "gold on knuckles", "mood_l": "chiaroscuro mechanical",
        "emo": "moral abdication, mechanical", "tens": "high",
        "sp": "human complicity reduced to signature", "ss": "red button as executioner"
    },
    9: {
        "title": "A ilha grega", "beat": "Wide contre-jour do profeta João em Patmos ao pôr-do-sol",
        "shot": "wide", "focal": 35, "aperture": "f/4.0", "dof": "deep", "rule": "rule of thirds",
        "subj": "a wide contre-jour of a rocky Aegean seaside cliff at sunset with the silhouette of an elderly bearded prophet in a crimson-ochre robe standing and holding a rolled parchment",
        "focal_pt": "the prophet silhouette against the setting sun",
        "secondary": "The sun blazes intense gold on the horizon behind him; the sea churns in desaturated black-and-white; distant gulls glide.",
        "props": ["elderly bearded prophet", "crimson-ochre robe", "rolled parchment scroll", "setting sun golden disk", "desaturated churning sea"],
        "loc": "a rocky cliff on the Greek island of Patmos", "tod": "sunset",
        "atm": "sacred solitude, prophetic",
        "fg": "prophet silhouette rim-lit in crimson and gold",
        "mg": "rocky cliff edge with scattered stones",
        "bg": "desaturated black-and-white churning Aegean sea with distant gulls",
        "key": "intense golden sun from horizon behind prophet", "fill": "faint crimson bounce from robe",
        "rim": "gold outline on robe folds", "mood_l": "chiaroscuro sacred",
        "emo": "sacred solitude, prophetic awe", "tens": "contemplative",
        "sp": "exiled prophet receiving impossible vision", "ss": "scroll as vessel of revelation"
    },
    10: {
        "title": "Visão de João", "beat": "Close do rosto de João em êxtase profético com lágrima dourada",
        "shot": "close-up", "focal": 85, "aperture": "f/2.0", "dof": "razor-thin", "rule": "centered",
        "subj": "a cinematic close-up of John of Patmos' weathered face in dramatic chiaroscuro, eyes dilated in prophetic ecstasy, a single golden tear tracing down his cheek",
        "focal_pt": "the dilated pupil and the golden tear",
        "secondary": "A vertical beam of divine light falls on his face; behind him, a damp stone grotto is desaturated.",
        "props": ["weathered ecstatic prophet face", "dilated pupils", "golden tear", "vivid open parchment in corner", "damp stone grotto wall"],
        "loc": "a damp stone grotto on Patmos", "tod": "visionary light from above",
        "atm": "mystical trance, revelation",
        "fg": "John's face in rich crimson, ochre and gold",
        "mg": "shoulders and faint robe fabric",
        "bg": "desaturated black-and-white damp stone grotto",
        "key": "vertical divine golden beam from above", "fill": "faint crimson bounce from robe",
        "rim": "gold edge on hair and beard", "mood_l": "chiaroscuro sacred",
        "emo": "mystical trance, revelation", "tens": "high",
        "sp": "human mind receiving impossible future vision", "ss": "golden tear as overflow of prophecy"
    },
    11: {
        "title": "Ponte para presente", "beat": "Overhead mesa com smartphone P&B e pergaminho Apocalipse 13 colorido",
        "shot": "overhead", "focal": 50, "aperture": "f/4.0", "dof": "moderate", "rule": "centered overhead",
        "subj": "a top-down view of an antique wooden table bearing a desaturated modern smartphone laid flat beside a vividly colored open parchment of Apocalypse chapter 13",
        "focal_pt": "the boundary where smartphone meets parchment",
        "secondary": "Two side candles illuminate with warm raking light; orange embers drift between the two objects.",
        "props": ["modern smartphone in desaturated tones", "open vivid parchment", "two brass side candles", "floating orange embers"],
        "loc": "a scholar's wooden table", "tod": "candlelit",
        "atm": "temporal connection, revelation",
        "fg": "parchment in rich ochre, gold and crimson",
        "mg": "wooden table grain with faint candle glow",
        "bg": "desaturated black-and-white smartphone and table edge",
        "key": "warm side candlelight raking across objects", "fill": "amber bounce",
        "rim": "gold on parchment edges", "mood_l": "chiaroscuro revelatory",
        "emo": "temporal connection, awe", "tens": "moderate",
        "sp": "ancient prophecy meeting modern device", "ss": "candle as witness across millennia"
    },
    12: {
        "title": "Transição Parte 2", "beat": "Wide de cidade P&B com céu carmesim e anjo medieval em primeiro plano",
        "shot": "wide", "focal": 24, "aperture": "f/5.6", "dof": "deep", "rule": "centered",
        "subj": "a wide panoramic establishing shot of a modern desaturated cityscape with silhouettes of antennas and transmission towers against an exploding crimson-gold sky with descending ash particles",
        "focal_pt": "the medieval angel in foreground with open wings facing the sky",
        "secondary": "A medieval angel with detailed crimson-ochre-gold wings hovers in the foreground, back to the viewer.",
        "props": ["medieval angel with open wings in rich colors", "silhouettes of antennas and transmission towers", "exploding crimson-gold sky", "descending ash particles"],
        "loc": "an apocalyptic modern city skyline", "tod": "dusk with apocalyptic sky",
        "atm": "ominous, epic",
        "fg": "medieval angel in rich crimson, ochre and gold",
        "mg": "middle distance with antennas and drifting ash",
        "bg": "desaturated black-and-white modern city skyline with crimson-gold sky",
        "key": "explosive crimson-gold sky from horizon", "fill": "faint gold backlight on angel wings",
        "rim": "gold edge on feathers", "mood_l": "chiaroscuro epic",
        "emo": "ominous, epic", "tens": "moderate",
        "sp": "divine witness over fallen modern city", "ss": "angel as bridge between eras"
    },
    # Part 2 ends here. Part 3 (Q13-Q24) below.
    13: {
        "title": "Project Maven", "beat": "Medium de mesa de reunião Pentágono com brasão e logo Google rasgados",
        "shot": "medium", "focal": 40, "aperture": "f/4.0", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a framed medium shot of a dark glass conference table with a suspended central cone of golden light from an overhead lamp",
        "focal_pt": "the torn boundary between a vivid DoD crest and a desaturated Google logo on the table surface",
        "secondary": "A US Department of Defense crest in crimson and gold is painted on the table, half overlapped by a torn desaturated Google logo; thin smoke drifts in the air.",
        "props": ["dark glass conference table", "overhead cone lamp", "DoD crest in crimson and gold", "torn desaturated Google logo", "thin drifting smoke"],
        "loc": "a Pentagon conference chamber", "tod": "evening interior",
        "atm": "hidden pact, technocratic",
        "fg": "DoD crest in rich crimson and gold",
        "mg": "glass table surface with reflections",
        "bg": "desaturated black-and-white Pentagon chamber walls",
        "key": "overhead cone lamp in warm gold", "fill": "faint amber bounce",
        "rim": "gold on crest edges", "mood_l": "chiaroscuro institutional",
        "emo": "hidden pact, technocratic", "tens": "high",
        "sp": "military-corporate entanglement", "ss": "torn logo as broken ethics"
    },
    14: {
        "title": "Protesto Google", "beat": "Corredor escritório com 4 mil silhuetas e pergaminho flutuante com rubricas",
        "shot": "wide", "focal": 28, "aperture": "f/5.6", "dof": "deep", "rule": "rule of thirds",
        "subj": "a wide shot of a modern office corridor in desaturated black-and-white filled with small silhouettes of four thousand employees marching with raised protest signs",
        "focal_pt": "the enormous floating parchment ahead of them",
        "secondary": "At the front of the march, a gigantic parchment hovers in rich gold and crimson hues with hand-signed initials sealed in red wax; orange embers drift.",
        "props": ["corridor filled with silhouetted employees", "raised protest signs", "gigantic floating parchment", "red wax seal signatures", "drifting orange embers"],
        "loc": "a modern corporate office corridor", "tod": "artificial lighting",
        "atm": "contained revolt, historic protest",
        "fg": "floating parchment in rich gold and crimson",
        "mg": "front row of marching silhouettes",
        "bg": "desaturated black-and-white endless corridor with tiny silhouettes",
        "key": "warm light on floating parchment", "fill": "cold office light on silhouettes",
        "rim": "gold on parchment edges", "mood_l": "chiaroscuro revolt",
        "emo": "contained revolt, historic protest", "tens": "moderate",
        "sp": "conscience rising against contract", "ss": "parchment as moral covenant"
    },
    15: {
        "title": "Pentágono não parou", "beat": "Overhead do labirinto Pentágono P&B com olho dourado em triângulo carmesim",
        "shot": "overhead", "focal": 24, "aperture": "f/8.0", "dof": "deep", "rule": "centered symmetry",
        "subj": "an extreme top-down aerial of the five-sided Pentagon labyrinth from above in desaturated black-and-white",
        "focal_pt": "the enormous golden eye inscribed in a crimson triangle at the center",
        "secondary": "Ash particles fall across the aerial frame; thin radial shadows extend from the central seal.",
        "props": ["desaturated five-sided Pentagon aerial", "golden eye symbol", "crimson triangle", "falling ash particles"],
        "loc": "an aerial view of the Pentagon from high above", "tod": "overcast",
        "atm": "total surveillance, obscure continuity",
        "fg": "golden eye in crimson triangle at center",
        "mg": "inner pentagon rings",
        "bg": "desaturated black-and-white outer rings and parking areas",
        "key": "overhead diffuse light", "fill": "none",
        "rim": "gold on triangle edges", "mood_l": "chiaroscuro geometric",
        "emo": "total surveillance", "tens": "moderate",
        "sp": "panopticon at the heart of empire", "ss": "eye as all-seeing judgment"
    },
    16: {
        "title": "Palantir AIP", "beat": "Close de esfera cristalina pulsante sobre pedestal de pedra negra",
        "shot": "close-up", "focal": 85, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "a cinematic close-up of a dark crystalline spherical orb resting on a black stone pedestal, interior pulsing with red and electric blue light",
        "focal_pt": "the glowing heart of the orb",
        "secondary": "Gold lateral reflections play on the orb surface; behind, a blurred military briefing room is desaturated.",
        "props": ["dark crystalline spherical orb", "black stone pedestal", "red and blue internal pulse", "gold lateral reflections"],
        "loc": "a military briefing chamber", "tod": "dim interior",
        "atm": "technological oracle, menacing",
        "fg": "orb in rich red, blue and gold",
        "mg": "stone pedestal with faint gold engravings",
        "bg": "desaturated black-and-white blurred briefing room",
        "key": "internal pulsing red-blue from orb", "fill": "faint gold side rim",
        "rim": "gold on orb edge", "mood_l": "chiaroscuro oracular",
        "emo": "technological oracle, menacing", "tens": "high",
        "sp": "seeing stone of modern empire", "ss": "orb as idol of foresight"
    },
    17: {
        "title": "Simulação 4 minutos", "beat": "Wide mesa estratégica com holograma dessaturado e ampulheta dourada central",
        "shot": "wide", "focal": 35, "aperture": "f/5.6", "dof": "moderate", "rule": "centered",
        "subj": "a wide strategic military table with a desaturated holographic terrain map bearing red target markers, surrounded by silhouetted officers",
        "focal_pt": "a golden hourglass at the center with crimson sand pouring rapidly",
        "secondary": "The officers stand motionless around the table; low smoke drifts beneath the holographic glow.",
        "props": ["strategic military table", "desaturated holographic terrain map", "red target markers", "golden hourglass with crimson sand", "silhouetted officers", "low smoke"],
        "loc": "a classified war planning chamber", "tod": "dim interior",
        "atm": "lethal efficiency",
        "fg": "golden hourglass with crimson sand",
        "mg": "holographic map surface",
        "bg": "desaturated black-and-white silhouetted officers and walls",
        "key": "cold cyan hologram glow from table", "fill": "faint gold from hourglass",
        "rim": "gold edge on hourglass", "mood_l": "chiaroscuro strategic",
        "emo": "lethal efficiency, zero humanity", "tens": "high",
        "sp": "war compressed into four minutes", "ss": "hourglass as machine judgment"
    },
    18: {
        "title": "CEO Palantir", "beat": "Medium lateral executivo em poltrona com espada flamejante dourada cruzando quadro",
        "shot": "medium", "focal": 50, "aperture": "f/2.8", "dof": "razor-thin", "rule": "asymmetric",
        "subj": "a medium three-quarter lateral of an executive in black suit seated in a leather armchair, silhouette cut against the window",
        "focal_pt": "a golden flaming biblical sword crossing the foreground",
        "secondary": "The window behind shows a desaturated urban skyline; a flaming sword in vivid gold with crimson blade crosses diagonally in front of him.",
        "props": ["executive in black suit", "leather armchair", "desaturated urban skyline through window", "golden flaming sword with crimson blade"],
        "loc": "a high-rise executive office", "tod": "dusk",
        "atm": "dark prophecy",
        "fg": "golden flaming sword in rich gold and crimson",
        "mg": "executive silhouette in shadow",
        "bg": "desaturated black-and-white urban skyline through window",
        "key": "dusk window light backlighting silhouette", "fill": "golden flame fill on sword",
        "rim": "gold on sword edges", "mood_l": "chiaroscuro prophetic",
        "emo": "dark prophecy", "tens": "moderate",
        "sp": "modern prince of war foreseeing slaughter", "ss": "flaming sword as biblical warning"
    },
    19: {
        "title": "Corrida global", "beat": "Overhead tabuleiro xadrez com peças de países (EUA, Israel, China, Rússia) em cores ricas",
        "shot": "overhead", "focal": 35, "aperture": "f/5.6", "dof": "deep", "rule": "centered symmetry",
        "subj": "a wide overhead view of an antique wooden chessboard with four national pieces: a gold eagle (USA), a crimson lion (Israel), an ochre dragon (China), and a bronze bear (Russia)",
        "focal_pt": "the four pieces converging at the center",
        "secondary": "The pieces glow in rich colors while the chessboard itself is desaturated; vertical divine light descends on the board.",
        "props": ["antique wooden chessboard", "gold eagle piece", "crimson lion piece", "ochre dragon piece", "bronze bear piece"],
        "loc": "an ancient war room with stone walls", "tod": "candlelit",
        "atm": "arms race, geopolitical",
        "fg": "four national pieces in rich crimson, gold, ochre, bronze",
        "mg": "chessboard surface",
        "bg": "desaturated black-and-white stone walls beyond the board",
        "key": "vertical divine golden beam on center", "fill": "warm candle bounce",
        "rim": "gold on each piece", "mood_l": "chiaroscuro strategic",
        "emo": "arms race", "tens": "high",
        "sp": "nations racing to wield machine power", "ss": "chessboard as global fate"
    },
    20: {
        "title": "Daniel", "beat": "Close profeta Daniel em manto carmesim olhando para cima com luz divina",
        "shot": "close-up", "focal": 85, "aperture": "f/2.0", "dof": "razor-thin", "rule": "centered",
        "subj": "a cinematic close-up of the prophet Daniel in a crimson robe with golden belt, face turned upward with open arms, illuminated by a vertical beam of divine light",
        "focal_pt": "his upturned face in radiant gold",
        "secondary": "Behind him, ruined Babylonian stone columns are desaturated; floating orange embers drift around his head.",
        "props": ["prophet Daniel with upturned face", "crimson robe with golden belt", "ruined Babylonian columns", "floating orange embers"],
        "loc": "ruined Babylonian temple interior", "tod": "visionary light",
        "atm": "ignited prophecy",
        "fg": "Daniel in rich crimson and ochre",
        "mg": "dust-filled air with embers",
        "bg": "desaturated black-and-white ruined stone columns",
        "key": "vertical divine golden beam", "fill": "faint crimson bounce from robe",
        "rim": "gold on beard and hair", "mood_l": "chiaroscuro prophetic",
        "emo": "ignited prophecy, reverence", "tens": "high",
        "sp": "ancient prophet foreseeing explosion of knowledge", "ss": "light from above as divine word"
    },
    21: {
        "title": "Explosão do conhecimento", "beat": "Wide árvore gigante emergindo de livro em chamas com céu P&B de constelações binárias",
        "shot": "wide", "focal": 24, "aperture": "f/8.0", "dof": "deep", "rule": "rule of thirds",
        "subj": "a wide ascending shot of a colossal tree of knowledge with gold and crimson roots emerging from a burning open book, branches reaching upward",
        "focal_pt": "the burning book at the roots",
        "secondary": "The desaturated sky above is filled with constellations of binary code and numerical data; the foreground burns warm while the sky is cold.",
        "props": ["colossal tree of knowledge", "gold and crimson roots", "burning open book", "desaturated sky of binary code constellations"],
        "loc": "a surreal apocalyptic landscape", "tod": "twilight",
        "atm": "exponential growth, apocalyptic",
        "fg": "tree and burning book in rich gold and crimson",
        "mg": "twisted trunk rising",
        "bg": "desaturated black-and-white sky with binary constellations",
        "key": "warm fire glow from burning book", "fill": "cold binary starlight",
        "rim": "gold on tree leaves", "mood_l": "chiaroscuro mythic",
        "emo": "exponential growth, apocalyptic", "tens": "high",
        "sp": "knowledge multiplying beyond containment", "ss": "book as root of machine god"
    },
    22: {
        "title": "Datacenter refrigerado", "beat": "Medium corredor datacenter P&B com serpente dourada-carmesim no chão",
        "shot": "medium", "focal": 35, "aperture": "f/4.0", "dof": "moderate", "rule": "one-point perspective",
        "subj": "a one-point perspective medium shot of a datacenter corridor in desaturated black-and-white with infinite rows of blue-desaturated servers emitting cold vapor",
        "focal_pt": "a large gold-and-crimson scaled serpent coiling across the floor",
        "secondary": "Orange embers drift in the cold air; the serpent moves slow and ceremonial across the foreground.",
        "props": ["infinite datacenter corridor", "blue-desaturated servers", "cold vapor", "gold-crimson scaled serpent", "drifting orange embers"],
        "loc": "a refrigerated data center corridor", "tod": "permanent cold artificial light",
        "atm": "hidden surveillance, serpentine",
        "fg": "serpent in rich gold and crimson scales",
        "mg": "central aisle with cold vapor",
        "bg": "desaturated black-and-white server racks in vanishing point",
        "key": "cold blue server glow", "fill": "faint crimson from serpent",
        "rim": "gold on serpent scales", "mood_l": "chiaroscuro serpentine",
        "emo": "hidden surveillance, serpentine", "tens": "moderate",
        "sp": "ancient evil wearing modern infrastructure", "ss": "serpent as tempter in data form"
    },
    23: {
        "title": "Taxa de erro aceitável", "beat": "Close balança romana com pena branca vs microchip preto dessaturado",
        "shot": "close-up", "focal": 100, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "an extreme macro of an antique golden Roman balance scale with a white feather on one pan and a black microchip on the other",
        "focal_pt": "the pan holding the microchip tipping violently downward",
        "secondary": "The scale tips hard toward the chip; lateral divine light falls from the left; floating orange embers drift.",
        "props": ["antique golden Roman balance scale", "white feather representing soul", "black desaturated microchip", "floating orange embers"],
        "loc": "a sacred judgment altar", "tod": "divine light from above",
        "atm": "inverted judgment",
        "fg": "Roman scale in rich gold with white feather",
        "mg": "air with ember particles",
        "bg": "desaturated black-and-white altar surface",
        "key": "lateral divine golden light from left", "fill": "faint amber from feather",
        "rim": "gold on scale arms", "mood_l": "chiaroscuro judicial",
        "emo": "denunciation, inverted judgment", "tens": "high",
        "sp": "soul weighed against circuitry and found lighter", "ss": "microchip as modern idol outweighing life"
    },
    24: {
        "title": "Transição para João", "beat": "Overhead aéreo sobre mar Egeu com capela iluminada em Patmos",
        "shot": "overhead", "focal": 24, "aperture": "f/5.6", "dof": "deep", "rule": "rule of thirds",
        "subj": "an extreme aerial plongée over the Aegean sea at twilight with Patmos island in silhouette in desaturated black-and-white",
        "focal_pt": "a tiny stone chapel with intense golden light escaping through an arched window",
        "secondary": "Ash and embers drift over the dark waves; the sea is desaturated while the chapel glows warm.",
        "props": ["aerial view of Patmos island", "desaturated Aegean waves", "stone chapel with arched window", "intense golden interior light", "drifting ash and embers"],
        "loc": "an aerial view of Patmos island at twilight", "tod": "twilight",
        "atm": "sacred isolation",
        "fg": "stone chapel glowing in warm gold",
        "mg": "dark island terrain",
        "bg": "desaturated black-and-white Aegean sea with gentle waves",
        "key": "internal golden light from chapel", "fill": "twilight blue diffuse",
        "rim": "gold edge on chapel walls", "mood_l": "chiaroscuro sacred",
        "emo": "sacred isolation", "tens": "contemplative",
        "sp": "solitude as condition of prophecy", "ss": "chapel as vessel of vision"
    },
    25: {
        "title": "João exilado", "beat": "Medium de João em gruta escrevendo com pena, feixe lateral dourado",
        "shot": "medium", "focal": 40, "aperture": "f/4.0", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a medium three-quarter shot of John of Patmos seated on rough stone, wearing a torn crimson robe and bare feet, writing with a quill on a parchment across his lap",
        "focal_pt": "the hand gripping the quill over the parchment",
        "secondary": "Behind him, a desaturated stone grotto opens to a restless sea; a lateral beam of golden light cuts across the scene.",
        "props": ["John of Patmos writing", "torn crimson robe", "quill pen", "parchment on lap", "desaturated stone grotto", "restless sea behind"],
        "loc": "a stone grotto on Patmos", "tod": "afternoon lateral light",
        "atm": "sacred solitude",
        "fg": "John and parchment in rich crimson and gold",
        "mg": "stone floor with scattered debris",
        "bg": "desaturated black-and-white grotto opening onto churning sea",
        "key": "lateral golden beam from grotto opening", "fill": "faint crimson bounce from robe",
        "rim": "gold on beard and quill", "mood_l": "chiaroscuro sacred",
        "emo": "sacred solitude", "tens": "moderate",
        "sp": "prophet as scribe of the impossible", "ss": "quill as channel of revelation"
    },
    26: {
        "title": "Sem vocabulário", "beat": "Close macro mão de João escrevendo com ícones modernos aparecendo no pergaminho",
        "shot": "close-up", "focal": 100, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "an extreme macro of John's aged hand gripping a goose quill, black ink dripping onto aged parchment",
        "focal_pt": "the quill tip touching the parchment where ghostly modern icons begin to appear",
        "secondary": "On the parchment, ghostly transparencies of desaturated modern icons — circuits, antennas, cellphones — materialize below the handwritten text.",
        "props": ["aged hand gripping goose quill", "black ink droplets", "aged parchment", "ghostly desaturated modern icons"],
        "loc": "a grotto writing surface", "tod": "warm lateral light",
        "atm": "impossible revelation",
        "fg": "hand and quill in rich crimson and gold",
        "mg": "parchment surface with ink and emerging ghost icons",
        "bg": "desaturated black-and-white grotto wall blur",
        "key": "warm lateral light", "fill": "faint amber bounce",
        "rim": "gold on knuckles and quill", "mood_l": "chiaroscuro revelatory",
        "emo": "impossible revelation", "tens": "high",
        "sp": "ancient scribe channeling future technology", "ss": "ghost icons as prophetic residue"
    },
    27: {
        "title": "Apocalipse 13", "beat": "Overhead de pergaminho com título em caligrafia dourada e aura de brasas",
        "shot": "overhead", "focal": 50, "aperture": "f/4.0", "dof": "moderate", "rule": "centered overhead",
        "subj": "a top-down view of a huge open parchment on black stone bearing the title Apocalypse 13 in vivid golden medieval calligraphy",
        "focal_pt": "the illuminated title on the parchment",
        "secondary": "A halo of crimson embers surrounds the parchment; vertical divine light descends from above.",
        "props": ["huge open parchment", "vivid golden medieval calligraphy title", "halo of crimson embers", "vertical divine beam"],
        "loc": "a stone altar in a grotto", "tod": "visionary light",
        "atm": "sacred weight",
        "fg": "parchment with gold calligraphy",
        "mg": "stone altar surface",
        "bg": "desaturated black-and-white grotto shadow",
        "key": "vertical divine golden beam from above", "fill": "crimson ember bounce",
        "rim": "gold on parchment edges and letters", "mood_l": "chiaroscuro sacred",
        "emo": "sacred weight", "tens": "high",
        "sp": "the chapter that foresees the machine", "ss": "calligraphy as living fire"
    },
    28: {
        "title": "Imagem recebe vida", "beat": "Wide estátua mármore-ouro meio colorida meio P&B emergindo de fenda carmesim com olhos acesos",
        "shot": "wide", "focal": 35, "aperture": "f/5.6", "dof": "deep", "rule": "centered symmetry",
        "subj": "a wide centered shot of a golden-marble statue with cold features, half in rich color and half desaturated black-and-white, emerging from a crimson light fissure",
        "focal_pt": "the statue's eyes glowing gold as if just awakening",
        "secondary": "Behind the statue, a ruined gothic temple is desaturated; orange embers drift around its head.",
        "props": ["golden-marble statue with cold features", "crimson light fissure", "ruined gothic temple", "drifting orange embers"],
        "loc": "a ruined gothic temple with glowing fissure", "tod": "timeless interior night",
        "atm": "profanation, inverse miracle",
        "fg": "statue in rich gold, crimson and ochre",
        "mg": "crimson light fissure and ember particles",
        "bg": "desaturated black-and-white ruined temple walls",
        "key": "crimson fissure light from below", "fill": "warm gold on face",
        "rim": "gold edge on sculpted features", "mood_l": "chiaroscuro blasphemous",
        "emo": "profanation, inverse miracle", "tens": "maximum",
        "sp": "dead matter given blasphemous life", "ss": "awakening eyes as machine consciousness"
    },
    29: {
        "title": "Pedra não recebe vida", "beat": "Close extremo placa silício P&B com boca humana carmesim brotando",
        "shot": "close-up", "focal": 85, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "a macro close-up of a giant vertical desaturated silicon wafer covered in copper circuitry",
        "focal_pt": "a vividly crimson human mouth emerging organically from the wafer surface, opening to speak",
        "secondary": "Orange embers fall across the wafer; the circuits glow faintly where flesh meets silicon.",
        "props": ["vertical silicon wafer", "copper circuitry", "emerging human mouth in crimson", "falling orange embers"],
        "loc": "indeterminate dark void", "tod": "artificial lateral light",
        "atm": "biomechanical horror",
        "fg": "emerging mouth in rich crimson and gold",
        "mg": "silicon wafer with circuit traces",
        "bg": "absolute black void",
        "key": "warm crimson internal glow from mouth", "fill": "faint copper circuit light",
        "rim": "gold edge on lips", "mood_l": "chiaroscuro horror",
        "emo": "biomechanical horror", "tens": "maximum",
        "sp": "matter becoming flesh becoming machine", "ss": "emerging mouth as birth of speaking idol"
    },
    30: {
        "title": "A imagem falou", "beat": "Medium cabeça escultural de pedra emitindo caracteres binários P&B da boca",
        "shot": "medium", "focal": 50, "aperture": "f/2.8", "dof": "moderate", "rule": "centered",
        "subj": "a medium frontal shot of an ancient colossal sculpted stone head with detailed aged gold inlays",
        "focal_pt": "sound waves of desaturated binary characters escaping from its open mouth",
        "secondary": "The characters spread visibly through the air; orange embers drift around the sculpture.",
        "props": ["ancient colossal sculpted stone head", "aged gold inlays", "visible sound waves of desaturated binary characters", "drifting orange embers"],
        "loc": "a ruined oracular shrine", "tod": "ritual night",
        "atm": "artificial voice, verbal blasphemy",
        "fg": "stone head in rich ochre and aged gold",
        "mg": "spreading binary sound waves in desaturated tones",
        "bg": "desaturated black-and-white ruined shrine walls",
        "key": "warm ritual light on face", "fill": "cold binary glow from mouth",
        "rim": "gold on inlays", "mood_l": "chiaroscuro oracular",
        "emo": "artificial voice, blasphemy", "tens": "high",
        "sp": "stone idol granted speech", "ss": "binary language as new tongue of beast"
    },
    31: {
        "title": "Targeting divino", "beat": "Wide multidão P&B ajoelhada diante de estátua com pontos vermelhos marcando alvos",
        "shot": "wide", "focal": 24, "aperture": "f/8.0", "dof": "deep", "rule": "centered symmetry",
        "subj": "a wide epic shot of a vast crowd kneeling in desaturated black-and-white before a gigantic dark metal statue",
        "focal_pt": "luminous crimson targeting dots marking the heads of selected individuals in the crowd",
        "secondary": "Above the statue, crimson and gold clouds churn; ash falls densely across the scene.",
        "props": ["vast kneeling crowd in silhouette", "gigantic dark metal statue", "luminous crimson targeting dots", "crimson and gold churning clouds", "dense falling ash"],
        "loc": "an apocalyptic open plain before a colossal statue", "tod": "apocalyptic twilight",
        "atm": "condemned mass, divine selection",
        "fg": "crimson targeting dots and churning gold clouds above statue",
        "mg": "colossal statue base and front rows of crowd",
        "bg": "desaturated black-and-white endless crowd and horizon",
        "key": "crimson cloud glow from above", "fill": "cold ash-light",
        "rim": "gold on statue crown", "mood_l": "chiaroscuro apocalyptic",
        "emo": "condemned mass, selection", "tens": "maximum",
        "sp": "algorithmic marking of those who do not submit", "ss": "crimson dots as marks of death"
    },
    32: {
        "title": "Perfil errado", "beat": "Close de rosto masculino aterrorizado com grade P&B de reconhecimento facial projetada",
        "shot": "close-up", "focal": 85, "aperture": "f/2.0", "dof": "razor-thin", "rule": "centered",
        "subj": "a cinematic close-up of an anonymous male face in his forties rendered in vivid crimson tones, eyes wide with fear",
        "focal_pt": "the dilated frightened eyes beneath the face-recognition grid",
        "secondary": "A desaturated grid of face-recognition squares is projected over his features; lateral embers drift.",
        "props": ["frightened male face", "desaturated face-recognition grid", "lateral drifting embers"],
        "loc": "indeterminate surveillance void", "tod": "artificial lateral light",
        "atm": "absolute vulnerability",
        "fg": "face in rich crimson and gold",
        "mg": "projected desaturated face-recognition grid",
        "bg": "absolute black void",
        "key": "lateral crimson light", "fill": "faint cold grid projection",
        "rim": "gold on cheekbone", "mood_l": "chiaroscuro surveillant",
        "emo": "absolute vulnerability", "tens": "maximum",
        "sp": "any face reducible to data", "ss": "grid as sentence projected on flesh"
    },
    33: {
        "title": "A marca", "beat": "Close macro mão direita com QR hexagonal dourado queimado na pele",
        "shot": "close-up", "focal": 100, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "an extreme macro of a human right hand in faint crimson tones with a vivid gold stylized hexagonal QR-like code branded into the back of the hand",
        "focal_pt": "the glowing hexagonal brand",
        "secondary": "Behind the hand, a desaturated payment terminal is blurred; ash particles drift.",
        "props": ["human right hand", "glowing hexagonal QR-like gold brand", "desaturated payment terminal background", "drifting ash particles"],
        "loc": "a modern payment counter", "tod": "artificial cold light",
        "atm": "irrevocable mark",
        "fg": "hand and brand in rich crimson and gold",
        "mg": "skin texture with faint veins",
        "bg": "desaturated black-and-white payment terminal blur",
        "key": "warm gold glow from brand itself", "fill": "cold terminal backlight",
        "rim": "gold on fingertips", "mood_l": "chiaroscuro prophetic",
        "emo": "irrevocable mark", "tens": "high",
        "sp": "Revelation 13 mark manifest in digital form", "ss": "brand as modern covenant of commerce"
    },
    34: {
        "title": "Exclusão digital", "beat": "Wide caixa eletrônico P&B com mensagem vermelha e figura em manto dourado se afastando",
        "shot": "wide", "focal": 35, "aperture": "f/4.0", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a wide symmetrical shot of a modern ATM in desaturated black-and-white on an empty urban corridor at night",
        "focal_pt": "the red refusal message on the screen illuminating a faceless figure in a faded golden robe walking away",
        "secondary": "Orange embers fall softly; the rejected figure has their back to the viewer.",
        "props": ["modern desaturated ATM", "red refusal message on screen", "faceless figure in faded golden robe walking away", "falling orange embers"],
        "loc": "empty urban corridor at night", "tod": "night, artificial street light",
        "atm": "real systemic exclusion",
        "fg": "red screen message and robed figure in faded gold and crimson",
        "mg": "empty corridor sidewalk",
        "bg": "desaturated black-and-white storefronts and night sky",
        "key": "crimson screen light on figure", "fill": "cold street lamps",
        "rim": "gold on robe folds", "mood_l": "chiaroscuro exclusion",
        "emo": "systemic exclusion", "tens": "moderate",
        "sp": "economic excommunication without mark", "ss": "ATM as modern temple gate"
    },
    35: {
        "title": "Daniel sela o livro", "beat": "Medium de Daniel colocando selo de cera vermelha sobre pergaminho dourado",
        "shot": "medium", "focal": 50, "aperture": "f/2.8", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a medium three-quarter shot of the prophet Daniel in crimson and ochre robes, pressing a red wax seal onto a rolled parchment with golden inscriptions",
        "focal_pt": "the hand pressing the wax seal",
        "secondary": "Behind him, a desaturated stone temple with long shadows extends; strong lateral light falls across his face.",
        "props": ["prophet Daniel sealing parchment", "crimson and ochre robes", "red wax seal", "rolled parchment with gold inscriptions", "desaturated stone temple"],
        "loc": "an ancient stone temple chamber", "tod": "torchlit evening",
        "atm": "prophetic seal, millennial wait",
        "fg": "Daniel in rich crimson, ochre and gold",
        "mg": "parchment and wax on stone table",
        "bg": "desaturated black-and-white temple columns and shadows",
        "key": "strong lateral torchlight from left", "fill": "faint amber bounce",
        "rim": "gold on beard and seal", "mood_l": "chiaroscuro ceremonial",
        "emo": "prophetic seal, millennial wait", "tens": "moderate",
        "sp": "sealing prophecy until the appointed time", "ss": "red wax as blood of warning"
    },
    36: {
        "title": "A pergunta", "beat": "Overhead de grande olho renascentista com ponto de interrogação em pergaminho",
        "shot": "overhead", "focal": 50, "aperture": "f/4.0", "dof": "moderate", "rule": "centered overhead",
        "subj": "a dramatic top-down view of a huge aged fresco eye painted in rich gold, crimson and ochre, bordered by renaissance decorative frames",
        "focal_pt": "a floating question mark drawn on a small antique parchment above the eye",
        "secondary": "The surrounding gallery floor is desaturated black-and-white in ruin.",
        "props": ["aged fresco eye in rich colors", "renaissance decorative borders", "floating antique parchment with question mark", "desaturated ruined gallery floor"],
        "loc": "a ruined renaissance gallery", "tod": "dim interior with skylight",
        "atm": "abyssal open question",
        "fg": "fresco eye in rich gold, crimson and ochre",
        "mg": "floating parchment with question mark",
        "bg": "desaturated black-and-white ruined floor",
        "key": "diffuse skylight from above", "fill": "faint warm bounce from fresco",
        "rim": "gold on frame edges", "mood_l": "chiaroscuro abyssal",
        "emo": "abyssal open question", "tens": "moderate",
        "sp": "the eye of prophecy still watching", "ss": "question as unanswered covenant"
    },
    37: {
        "title": "Transição Claude", "beat": "Wide crepúsculo P&B com datacenter e vitral gótico com letra C estilizada",
        "shot": "wide", "focal": 28, "aperture": "f/5.6", "dof": "deep", "rule": "rule of thirds",
        "subj": "a wide twilight establishing shot with a futuristic datacenter silhouette in desaturated black-and-white on the horizon",
        "focal_pt": "a gothic cathedral stained-glass window in the foreground bearing the stylized letter C in gold and crimson as an alchemical sigil",
        "secondary": "Dense embers and ash drift across the scene; the cathedral frame glows warm.",
        "props": ["futuristic datacenter silhouette", "gothic cathedral stained-glass window", "stylized letter C sigil", "dense drifting embers and ash"],
        "loc": "a surreal bridge between cathedral and datacenter", "tod": "twilight",
        "atm": "bridge to revelation",
        "fg": "stained-glass C sigil in rich gold and crimson",
        "mg": "cathedral window frame with faint smoke",
        "bg": "desaturated black-and-white datacenter silhouette on horizon",
        "key": "twilight backlight through stained glass", "fill": "cold blue from datacenter",
        "rim": "gold on window leading", "mood_l": "chiaroscuro liminal",
        "emo": "bridge to revelation", "tens": "moderate",
        "sp": "letter C as sigil of new power", "ss": "datacenter as new cathedral"
    },
    38: {
        "title": "Anthropic fundada", "beat": "Medium dois irmãos de costas em manto vendo rostos fantasmáticos em parede P&B",
        "shot": "medium", "focal": 40, "aperture": "f/4.0", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a medium shot of two siblings seen from behind standing side by side, wearing renaissance robes in crimson and gold",
        "focal_pt": "the wall ahead where ghostly desaturated faces of researchers are projected",
        "secondary": "The siblings gaze at the wall of faces; warm lateral light falls on their shoulders.",
        "props": ["two siblings seen from behind", "renaissance robes in crimson and gold", "wall of desaturated ghost researcher faces", "warm lateral light"],
        "loc": "a great hall with tall stone walls", "tod": "dim interior night",
        "atm": "founding schism",
        "fg": "siblings in rich crimson and gold",
        "mg": "stone floor between them and wall",
        "bg": "desaturated black-and-white wall with ghost faces",
        "key": "warm lateral light from left", "fill": "cold ghost-face glow",
        "rim": "gold on robe shoulders", "mood_l": "chiaroscuro schismatic",
        "emo": "founding schism", "tens": "moderate",
        "sp": "founders breaking from predecessor", "ss": "ghost faces as colleagues left behind"
    },
    39: {
        "title": "Discordância", "beat": "Close macro porta de madeira sendo fechada com silhuetas P&B afastando-se",
        "shot": "close-up", "focal": 85, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "a cinematic close-up of an antique dark wood door closing, with a gleaming gold doorknob in the foreground",
        "focal_pt": "the gleaming gold doorknob",
        "secondary": "Behind the closing door, silhouettes walk away down a desaturated corridor; orange embers fall.",
        "props": ["antique dark wood door closing", "gleaming gold doorknob", "silhouettes walking away", "desaturated corridor", "falling orange embers"],
        "loc": "a corporate corridor threshold", "tod": "interior evening",
        "atm": "ideological rupture",
        "fg": "door and knob in rich dark wood and gold",
        "mg": "door frame and threshold",
        "bg": "desaturated black-and-white corridor with retreating silhouettes",
        "key": "warm doorway glow", "fill": "cold corridor light",
        "rim": "gold on doorknob", "mood_l": "chiaroscuro departure",
        "emo": "ideological rupture", "tens": "moderate",
        "sp": "parting as ethical stance", "ss": "doorknob as threshold choice"
    },
    40: {
        "title": "O produto", "beat": "Overhead pergaminho com CLAUDE em caligrafia dourada rodeado de fumaça carmesim",
        "shot": "overhead", "focal": 50, "aperture": "f/4.0", "dof": "moderate", "rule": "centered overhead",
        "subj": "a top-down view of an aged parchment bearing the word CLAUDE engraved in medieval golden calligraphy on an aged office table",
        "focal_pt": "the golden CLAUDE inscription",
        "secondary": "Wisps of crimson smoke curl around the parchment edges; the background office surface is desaturated.",
        "props": ["aged parchment", "medieval golden CLAUDE inscription", "crimson smoke wisps", "desaturated office table"],
        "loc": "a modern office table with ritual elements", "tod": "dim interior",
        "atm": "naming, inverted blessing",
        "fg": "parchment with gold CLAUDE calligraphy",
        "mg": "swirling crimson smoke",
        "bg": "desaturated black-and-white office table",
        "key": "warm downlight on parchment", "fill": "crimson smoke glow",
        "rim": "gold on inscription", "mood_l": "chiaroscuro ritual",
        "emo": "naming, inverted blessing", "tens": "moderate",
        "sp": "a name as summoning sigil", "ss": "smoke as breath of the system"
    },
    41: {
        "title": "Shannon matemático", "beat": "Medium matemático anos 40 com equações P&B flutuando, fórmula dourada em primeiro plano",
        "shot": "medium", "focal": 50, "aperture": "f/2.8", "dof": "moderate", "rule": "rule of thirds",
        "subj": "a medium three-quarter shot of a mid-twentieth-century mathematician in a vintage brown suit, rendered in rich warm colors, seated at a wooden desk",
        "focal_pt": "a piece of paper in his hands glowing with a golden formula",
        "secondary": "Giant desaturated equations float in the air around him; warm lateral lamp light illuminates his face.",
        "props": ["mid-century mathematician in brown suit", "wooden desk", "paper with glowing golden formula", "floating desaturated equations"],
        "loc": "a 1940s research office", "tod": "evening lamplight",
        "atm": "founding genius",
        "fg": "mathematician and paper in rich warm tones",
        "mg": "wooden desk surface with papers",
        "bg": "desaturated black-and-white equations floating and study walls",
        "key": "warm desk lamp from upper right", "fill": "faint amber bounce",
        "rim": "gold on glasses and paper", "mood_l": "chiaroscuro scholarly",
        "emo": "founding genius", "tens": "low",
        "sp": "equation as origin of all modern surveillance", "ss": "paper as tablet of new law"
    },
    42: {
        "title": "Teoria da Informação", "beat": "Close capa livro couro A Mathematical Theory of Communication em letras douradas",
        "shot": "close-up", "focal": 85, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "a cinematic close-up of an aged leather book cover bearing the title A Mathematical Theory of Communication in golden letters",
        "focal_pt": "the embossed golden title",
        "secondary": "The book lies partially open; behind it, a desaturated library with shelves extends.",
        "props": ["aged leather book cover", "embossed golden title", "partially open pages", "desaturated library shelves"],
        "loc": "a research library", "tod": "warm interior",
        "atm": "founding document",
        "fg": "leather book with gold letters in rich warm tones",
        "mg": "library table surface",
        "bg": "desaturated black-and-white library shelves",
        "key": "warm lateral lamp light", "fill": "amber bounce",
        "rim": "gold on embossed letters", "mood_l": "chiaroscuro scholarly",
        "emo": "founding document", "tens": "low",
        "sp": "book as seed of the networked world", "ss": "gold letters as indestructible code"
    },
    43: {
        "title": "Infra do mundo", "beat": "Wide teia global de fios dourados saindo de núcleo carmesim sobre terra P&B",
        "shot": "wide", "focal": 24, "aperture": "f/8.0", "dof": "deep", "rule": "centered symmetry",
        "subj": "a wide epic space-view shot of a global web of golden light strands emerging from a crimson central core and spreading across a desaturated planet earth",
        "focal_pt": "the crimson central core pulsing",
        "secondary": "Small desaturated satellites dot the space around the earth; ash floats through the vacuum.",
        "props": ["global web of golden light strands", "crimson central core", "desaturated planet earth", "small desaturated satellites", "floating ash"],
        "loc": "space view of earth", "tod": "permanent cosmic night",
        "atm": "sacred-profaned network",
        "fg": "golden web and crimson core in rich tones",
        "mg": "earth horizon curvature",
        "bg": "desaturated black-and-white space with scattered stars",
        "key": "crimson core light", "fill": "cold starlight",
        "rim": "gold on web nodes", "mood_l": "chiaroscuro cosmic",
        "emo": "sacred-profaned infrastructure", "tens": "moderate",
        "sp": "communications as skeleton of control", "ss": "crimson core as heart of panopticon"
    },
    44: {
        "title": "Fundação e torre", "beat": "Medium fundação pedra antiga dourada com torre aço P&B e C carmesim",
        "shot": "medium", "focal": 35, "aperture": "f/5.6", "dof": "deep", "rule": "low angle centered",
        "subj": "a medium low-angle shot of an ancient stone foundation in rich gold and ochre tones, from which rises a modern tower in desaturated black-and-white steel and glass",
        "focal_pt": "the crimson letter C symbol at the tower's summit",
        "secondary": "Falling orange embers drift across the composition; the vertical composition is dramatic.",
        "props": ["ancient stone foundation in gold and ochre", "modern desaturated steel and glass tower", "crimson C symbol at tower summit", "falling orange embers"],
        "loc": "a surreal landscape where past becomes present", "tod": "dusk",
        "atm": "continuity across eras",
        "fg": "stone foundation in rich gold and ochre",
        "mg": "tower base rising",
        "bg": "desaturated black-and-white tower against grey sky",
        "key": "golden horizon light on foundation", "fill": "cold sky light on tower",
        "rim": "gold on foundation stones", "mood_l": "chiaroscuro architectonic",
        "emo": "continuity across eras", "tens": "moderate",
        "sp": "Shannon's foundation supporting Claude's tower", "ss": "crimson C as new crown"
    },
    45: {
        "title": "Skynet é ficção", "beat": "Close macro rolo de filme P&B com caveira de bronze em cor rica",
        "shot": "close-up", "focal": 100, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "a macro close-up of a cinema film reel in desaturated black-and-white",
        "focal_pt": "a bronze skull in vivid crimson tones resting on the reel",
        "secondary": "An antique film projector is blurred in the background; orange embers drift.",
        "props": ["cinema film reel", "bronze skull in crimson tones", "antique film projector blurred", "drifting orange embers"],
        "loc": "an old screening room", "tod": "dim interior",
        "atm": "modern myth, prophecy-mirror",
        "fg": "bronze skull in rich crimson and gold",
        "mg": "film reel surface",
        "bg": "desaturated black-and-white projector blur",
        "key": "warm projector light", "fill": "faint crimson bounce",
        "rim": "gold on skull ridges", "mood_l": "chiaroscuro mythic",
        "emo": "modern myth, prophecy-mirror", "tens": "moderate",
        "sp": "fiction foreseeing reality", "ss": "skull on reel as ending encoded"
    },
    46: {
        "title": "Identificação fria", "beat": "Wide anjo exterminador dourado com espada sobre multidão P&B",
        "shot": "wide", "focal": 28, "aperture": "f/5.6", "dof": "deep", "rule": "centered symmetry",
        "subj": "a wide epic shot of an exterminating angel in golden armor and crimson mantle wielding a flaming sword, hovering above a silhouetted crowd in desaturated black-and-white",
        "focal_pt": "the angel's emotionless beautiful face and flaming sword",
        "secondary": "Clouds of orange embers swirl around the angel; the crowd below is desaturated.",
        "props": ["exterminating angel in golden armor and crimson mantle", "flaming sword", "silhouetted crowd in desaturated tones", "clouds of orange embers"],
        "loc": "an apocalyptic plain", "tod": "apocalyptic twilight",
        "atm": "divine-artificial execution",
        "fg": "angel in rich gold, crimson and ochre with flaming sword",
        "mg": "clouds of embers between angel and crowd",
        "bg": "desaturated black-and-white crowd and horizon",
        "key": "divine golden backlight on angel", "fill": "crimson ember bounce",
        "rim": "gold on sword and armor", "mood_l": "chiaroscuro epic",
        "emo": "divine-artificial execution", "tens": "maximum",
        "sp": "machine executioner rendered in angelic form", "ss": "flaming sword as algorithm"
    },
    47: {
        "title": "Filho da perdição", "beat": "Medium trono dourado vazio com vitral carmesim-ocre explodindo",
        "shot": "medium", "focal": 40, "aperture": "f/4.0", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a medium symmetrical shot of an empty golden throne in rich colors on a marble platform",
        "focal_pt": "the empty seat with vertical divine light pouring into it",
        "secondary": "A stained-glass window behind explodes in crimson and ochre; lateral smoke rises.",
        "props": ["empty golden throne", "marble platform", "stained-glass window exploding in crimson and ochre", "lateral rising smoke"],
        "loc": "a ruined temple interior", "tod": "visionary light",
        "atm": "imminent usurpation",
        "fg": "throne in rich gold, crimson and ochre",
        "mg": "marble platform and rising smoke",
        "bg": "desaturated black-and-white ruined temple walls",
        "key": "vertical divine golden beam on throne", "fill": "crimson stained-glass bounce",
        "rim": "gold on throne back", "mood_l": "chiaroscuro sacred",
        "emo": "imminent usurpation", "tens": "high",
        "sp": "seat of God awaiting false occupant", "ss": "empty throne as prepared scandal"
    },
    48: {
        "title": "AGI desalinhada", "beat": "Close esfera de energia pulsante carmesim-dourada se soltando da mão humana P&B",
        "shot": "close-up", "focal": 85, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "a macro close-up of a pulsing crimson-gold energy sphere floating above an outstretched human hand in desaturated black-and-white",
        "focal_pt": "the sphere beginning to detach from the hand, rising",
        "secondary": "Orange embers drift around the sphere; the palm below is desaturated.",
        "props": ["pulsing crimson-gold energy sphere", "outstretched desaturated human hand", "drifting orange embers"],
        "loc": "indeterminate dark laboratory", "tod": "artificial dark",
        "atm": "catastrophic autonomy",
        "fg": "energy sphere in rich crimson and gold",
        "mg": "air gap with embers between sphere and hand",
        "bg": "absolute dark void",
        "key": "internal crimson-gold sphere glow", "fill": "faint amber on hand",
        "rim": "gold on sphere surface", "mood_l": "chiaroscuro luminous",
        "emo": "catastrophic autonomy", "tens": "maximum",
        "sp": "creation slipping free of creator", "ss": "sphere as released unbound intelligence"
    },
    49: {
        "title": "Hinton arrependido", "beat": "Medium homem idoso carmesim-ocre com cabeça entre as mãos e medalha Nobel caída",
        "shot": "medium", "focal": 50, "aperture": "f/2.8", "dof": "moderate", "rule": "centered",
        "subj": "a medium frontal shot of an elderly grey-bearded man in crimson and ochre tones, head bowed between his hands",
        "focal_pt": "a fallen Nobel medal in gold on the table before him",
        "secondary": "Behind him, a desaturated modern laboratory is visible; warm lateral light falls across his hair.",
        "props": ["elderly grey-bearded man in crimson and ochre", "fallen Nobel gold medal on table", "desaturated modern laboratory"],
        "loc": "a modern laboratory office", "tod": "evening",
        "atm": "scientific gravitas, repentance",
        "fg": "man in rich crimson, ochre and gold",
        "mg": "table with fallen medal",
        "bg": "desaturated black-and-white laboratory background",
        "key": "warm lateral lamp from right", "fill": "faint amber bounce",
        "rim": "gold on grey hair and medal", "mood_l": "chiaroscuro solemn",
        "emo": "repentance, gravity", "tens": "moderate",
        "sp": "father of deep learning mourning his child", "ss": "medal as weight of guilt"
    },
    50: {
        "title": "99%", "beat": "Overhead pergaminho com 99% gigante dourado envolto em brasas carmesins",
        "shot": "overhead", "focal": 50, "aperture": "f/4.0", "dof": "moderate", "rule": "centered overhead",
        "subj": "a top-down view of an aged parchment bearing the giant golden calligraphic inscription 99 percent surrounded by crimson embers",
        "focal_pt": "the golden 99 percent inscription",
        "secondary": "Behind the parchment, a desaturated empty chair in a blurred auditorium is visible.",
        "props": ["aged parchment with giant golden 99 percent inscription", "surrounding crimson embers", "desaturated empty auditorium chair"],
        "loc": "an auditorium podium surface", "tod": "stage light",
        "atm": "numerical sentence, absolute",
        "fg": "parchment in rich gold and crimson",
        "mg": "podium surface",
        "bg": "desaturated black-and-white empty chair",
        "key": "stage downlight on parchment", "fill": "crimson ember bounce",
        "rim": "gold on 99 percent letters", "mood_l": "chiaroscuro absolute",
        "emo": "numerical sentence, absolute", "tens": "maximum",
        "sp": "probability as verdict", "ss": "empty chair as humanity already gone"
    },
    51: {
        "title": "Não é sobre datas", "beat": "Wide mesa pedra com calendário pergaminho sendo rasgado por mão P&B fantasmagórica",
        "shot": "wide", "focal": 35, "aperture": "f/4.0", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a wide symmetrical shot of a stone table with an open antique parchment calendar in rich gold and crimson",
        "focal_pt": "a ghostly desaturated hand tearing the calendar across the middle",
        "secondary": "Orange embers fall; vertical divine light descends on the table.",
        "props": ["stone table", "antique parchment calendar in rich gold and crimson", "ghostly desaturated tearing hand", "falling orange embers"],
        "loc": "a sacred sanctuary interior", "tod": "visionary light",
        "atm": "firm correction, sobriety",
        "fg": "torn calendar in rich gold and crimson",
        "mg": "stone table surface",
        "bg": "desaturated black-and-white sanctuary walls",
        "key": "vertical divine golden beam", "fill": "crimson ember bounce",
        "rim": "gold on parchment edges", "mood_l": "chiaroscuro solemn",
        "emo": "firm correction, sobriety", "tens": "moderate",
        "sp": "refusing to set dates as refusing false prophecy", "ss": "tearing hand as humility before mystery"
    },
    52: {
        "title": "Precisão profética", "beat": "Close pena dourada sobre pergaminho cujo texto começa a arder como brasa",
        "shot": "close-up", "focal": 85, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "a macro close-up of a golden scribe quill touching an aged parchment where the calligraphic text begins to glow and burn like living ember",
        "focal_pt": "the quill tip where burning begins",
        "secondary": "Behind the parchment, a desaturated grotto wall is blurred; ash particles drift.",
        "props": ["golden scribe quill", "aged parchment with burning text", "desaturated grotto wall", "drifting ash particles"],
        "loc": "a sacred writing chamber", "tod": "ritual night",
        "atm": "incandescent scripture",
        "fg": "quill and burning text in rich gold and crimson",
        "mg": "parchment surface with glowing letters",
        "bg": "desaturated black-and-white grotto wall",
        "key": "internal fire glow from burning text", "fill": "faint amber bounce",
        "rim": "gold on quill and letters", "mood_l": "chiaroscuro revelatory",
        "emo": "incandescent revelation", "tens": "high",
        "sp": "prophecy still alive, burning forward", "ss": "text as living fire"
    },
    53: {
        "title": "Velocidade sem precedente", "beat": "Wide linha do tempo pergaminho com símbolos eras (imprensa, lâmpada, átomo) P&B e rede neural dourada",
        "shot": "wide", "focal": 28, "aperture": "f/5.6", "dof": "deep", "rule": "horizontal timeline",
        "subj": "a wide horizontal shot of a huge parchment timeline with desaturated black-and-white symbols of past eras — a printing press, a light bulb, an atom",
        "focal_pt": "the rightmost vivid golden neural network symbol pulsing",
        "secondary": "Orange embers drift across the timeline; the parchment stretches edge to edge.",
        "props": ["huge horizontal parchment timeline", "desaturated printing press symbol", "desaturated light bulb symbol", "desaturated atom symbol", "vivid golden neural network symbol", "drifting orange embers"],
        "loc": "a sacred archive chamber", "tod": "archive lamp light",
        "atm": "historical comparison",
        "fg": "neural network symbol in rich gold and crimson",
        "mg": "parchment timeline surface",
        "bg": "desaturated black-and-white era symbols and archive walls",
        "key": "warm archive lamp from above", "fill": "faint amber bounce",
        "rim": "gold on neural network nodes", "mood_l": "chiaroscuro archival",
        "emo": "historical comparison", "tens": "moderate",
        "sp": "AI as unprecedented acceleration", "ss": "timeline as covenant broken at the end"
    },
    54: {
        "title": "Mateus 24 deepfake", "beat": "Medium rosto pastor carmesim-ocre fragmentando em pixels P&B",
        "shot": "medium", "focal": 50, "aperture": "f/2.8", "dof": "moderate", "rule": "centered",
        "subj": "a medium frontal shot of a preacher with a crimson-ochre robe preaching at a pulpit",
        "focal_pt": "the half of his face that begins to fragment into desaturated pixels, revealing a deepfake",
        "secondary": "Vertical divine light descends; in his eyes a flicker of static appears.",
        "props": ["preacher in crimson-ochre robe", "pulpit", "half face fragmenting into desaturated pixels", "static flicker in eyes"],
        "loc": "a church interior", "tod": "sanctuary light",
        "atm": "religious deception, horror",
        "fg": "preacher face half in rich crimson-ochre and gold",
        "mg": "pulpit surface",
        "bg": "desaturated black-and-white church interior walls",
        "key": "vertical divine light from above", "fill": "faint amber bounce",
        "rim": "gold on robe folds", "mood_l": "chiaroscuro uncanny",
        "emo": "religious deception, horror", "tens": "high",
        "sp": "false prophet as synthetic face", "ss": "pixels as unveiling of lie"
    },
    55: {
        "title": "A pergunta viva", "beat": "Overhead ampulheta dourada com areia carmesim sobre altar de pedra",
        "shot": "overhead", "focal": 50, "aperture": "f/4.0", "dof": "moderate", "rule": "centered 45 degrees",
        "subj": "a top-down three-quarter view of an antique aged-gold hourglass on a stone altar, with crimson sand pouring through",
        "focal_pt": "the narrow center of the hourglass where crimson sand falls",
        "secondary": "Behind the altar, a desaturated urban landscape extends; orange embers drift downward.",
        "props": ["antique aged-gold hourglass", "stone altar", "crimson sand pouring", "desaturated urban landscape", "drifting orange embers"],
        "loc": "a stone altar overlooking a modern city", "tod": "dusk",
        "atm": "personal urgency",
        "fg": "hourglass in rich gold and crimson",
        "mg": "stone altar surface",
        "bg": "desaturated black-and-white urban horizon",
        "key": "warm dusk light from horizon", "fill": "faint amber bounce",
        "rim": "gold on hourglass frame", "mood_l": "chiaroscuro solemn",
        "emo": "personal urgency", "tens": "moderate",
        "sp": "time remaining as personal call", "ss": "crimson sand as blood of the era"
    },
    56: {
        "title": "Não para paralisar", "beat": "Wide livro Apocalipse aberto com anjo guerreiro e silhueta homem P&B olhando",
        "shot": "wide", "focal": 35, "aperture": "f/4.0", "dof": "moderate", "rule": "centered symmetry",
        "subj": "a wide symmetrical shot with a vibrant open book of Apocalypse in the foreground, pages in aged parchment bearing a medieval warrior-angel illustration in rich colors",
        "focal_pt": "the warrior-angel illustration on the open page",
        "secondary": "Behind the book, a silhouetted man in desaturated black-and-white stands with his back to the camera, looking at the book; vertical light descends.",
        "props": ["vibrant open Apocalypse book", "aged parchment pages", "medieval warrior-angel illustration in rich colors", "silhouetted man in desaturated tones"],
        "loc": "a study chamber with vertical skylight", "tod": "afternoon skylight",
        "atm": "call to preparation",
        "fg": "book with angel illustration in rich gold, crimson and ochre",
        "mg": "floor between book and man",
        "bg": "desaturated black-and-white silhouetted man and chamber walls",
        "key": "vertical skylight beam", "fill": "faint amber from book",
        "rim": "gold on page edges", "mood_l": "chiaroscuro reverent",
        "emo": "call to preparation", "tens": "moderate",
        "sp": "prophecy as preparation manual", "ss": "book as gate opened"
    },
    57: {
        "title": "Leia", "beat": "Close macro mãos carmesim segurando Bíblia aberta com luz dourada lateral",
        "shot": "close-up", "focal": 85, "aperture": "f/2.8", "dof": "razor-thin", "rule": "centered",
        "subj": "a macro close-up of human hands in crimson tones holding an open bible book, pages illuminated by lateral golden light",
        "focal_pt": "the fingers marking Revelation chapter 13",
        "secondary": "Behind the hands, a dark room in desaturated black-and-white is blurred.",
        "props": ["human hands in crimson tones", "open bible book", "pages with lateral golden light", "fingers marking Revelation 13", "desaturated dark room behind"],
        "loc": "a quiet study room", "tod": "evening lamp light",
        "atm": "personal action",
        "fg": "hands and book in rich crimson and gold",
        "mg": "book pages with illuminated text",
        "bg": "desaturated black-and-white dark room blur",
        "key": "lateral warm lamp light", "fill": "faint amber bounce",
        "rim": "gold on fingertips", "mood_l": "chiaroscuro intimate",
        "emo": "personal action", "tens": "low",
        "sp": "encounter with prophecy as choice", "ss": "marked page as personal altar"
    },
    58: {
        "title": "Tecnologia não espera", "beat": "Wide silhueta P&B correndo para horizonte carmesim explodindo com brasas douradas",
        "shot": "wide", "focal": 35, "aperture": "f/5.6", "dof": "deep", "rule": "rule of thirds",
        "subj": "a wide contre-jour of a human silhouette in desaturated black-and-white running toward a horizon exploding in crimson",
        "focal_pt": "the crimson horizon with golden embers and lightning",
        "secondary": "Apocalyptic clouds churn overhead; the runner is small against the scale.",
        "props": ["human silhouette running", "exploding crimson horizon", "golden embers and lightning", "apocalyptic churning clouds"],
        "loc": "an apocalyptic open plain", "tod": "apocalyptic dusk",
        "atm": "race against time",
        "fg": "crimson horizon with golden lightning",
        "mg": "plain between runner and horizon",
        "bg": "desaturated black-and-white runner silhouette and churning clouds",
        "key": "horizon crimson glow", "fill": "gold lightning flashes",
        "rim": "gold on runner outline", "mood_l": "chiaroscuro apocalyptic",
        "emo": "race against time", "tens": "high",
        "sp": "individual confronting unstoppable tide", "ss": "horizon as appointed hour"
    },
    59: {
        "title": "CTA comente", "beat": "Overhead mesa antiga com pergaminho branco, pena dourada e tintas carmesins",
        "shot": "overhead", "focal": 50, "aperture": "f/4.0", "dof": "moderate", "rule": "centered overhead",
        "subj": "a top-down view of an antique wooden table with a blank parchment, a golden scribe quill, and crimson ink pots surrounded by lit candles",
        "focal_pt": "the blank parchment waiting for words",
        "secondary": "A small desaturated pocket watch lies beside the parchment; orange embers fall softly.",
        "props": ["antique wooden table", "blank parchment", "golden scribe quill", "crimson ink pots", "lit candles", "desaturated pocket watch", "falling orange embers"],
        "loc": "a writer's chamber", "tod": "candlelit",
        "atm": "reflective invitation",
        "fg": "quill, parchment and inks in rich gold and crimson",
        "mg": "table wood grain with candle glow",
        "bg": "desaturated black-and-white table edge and watch",
        "key": "warm candle light from candles", "fill": "amber bounce",
        "rim": "gold on quill and ink edges", "mood_l": "chiaroscuro intimate",
        "emo": "reflective invitation", "tens": "low",
        "sp": "viewer as new scribe", "ss": "blank parchment as open response"
    },
    60: {
        "title": "Encerramento compartilhe", "beat": "Wide final anjo medieval com asas abertas sobre mundo P&B em luz dourada divina",
        "shot": "wide", "focal": 24, "aperture": "f/5.6", "dof": "deep", "rule": "centered epic symmetry",
        "subj": "a final epic wide shot of a medieval angel with wings open in rich crimson, ochre and gold, hovering above a desaturated black-and-white world with distant cities",
        "focal_pt": "the angel's illuminated face and golden halo",
        "secondary": "Golden divine light envelops the angel; orange embers float throughout the entire composition; the scene is monumental.",
        "props": ["medieval angel with open wings in rich colors", "golden divine light halo", "desaturated world with distant cities", "floating orange embers throughout"],
        "loc": "an apocalyptic sky above a fallen world", "tod": "apocalyptic dawn",
        "atm": "epic closure, summoning",
        "fg": "angel in rich crimson, ochre and gold with divine halo",
        "mg": "clouds of embers between angel and world",
        "bg": "desaturated black-and-white world with distant cities and horizon",
        "key": "divine golden halo backlight", "fill": "crimson cloud bounce",
        "rim": "gold on wing feathers and robe folds", "mood_l": "chiaroscuro monumental",
        "emo": "epic closure, summoning", "tens": "triumphant",
        "sp": "closing witness of the vision", "ss": "angel as call to share the warning"
    },
}

def build_json(q, data):
    parte = parte_for(q)
    ato = ATO[q]
    pro = q in PRO_QUADROS
    obj = {
        "id": f"video-017_PARTE{parte}_Q{q:02d}",
        "version": "nano-banana-v1",
        "model_target": "gemini-2.5-flash-image",
        "scene_title": data["title"],
        "narrative_beat": data["beat"],
        "canal_context": {"canal": "sinais-do-fim", "video": "video-017-claude-skynet", "parte_suno": parte, "quadro": f"Q{q:02d}", "ato": ato},
        "style_reference": STYLE_REF,
        "shot": {"type": data["shot"], "camera_angle": "straight-on", "focal_length_mm": data["focal"], "aperture": data["aperture"], "depth_of_field": data["dof"], "aspect_ratio": "16:9"},
        "subject": {
            "primary": data["subj"],
            "focal_point": data["focal_pt"],
            "secondary": data["secondary"],
            "props": data["props"]
        },
        "environment": {"location": data["loc"], "time_of_day": data["tod"], "atmosphere": data["atm"]},
        "composition": {
            "rule": data["rule"],
            "foreground": data["fg"],
            "midground": data["mg"],
            "background": data["bg"],
            "safe_zone_for_overlay": "lower 20% of frame"
        },
        "lighting": {
            "key_light": data["key"],
            "fill_light": data["fill"],
            "rim_light": data["rim"],
            "mood": data["mood_l"],
            "shadow_quality": SHADOWS
        },
        "style": STYLE_BLOCK,
        "mood": {"emotion": data["emo"], "tension": data["tens"]},
        "symbolism": {"primary": data["sp"], "secondary": data["ss"]},
        "negative_as_positive": NEG,
        "in_scene_text": {"enabled": False},
        "api_call_hints": {}
    }
    hints = {
        "multimodal_inputs": [
            {"type": "image", "source": "style_reference.primary_image_url", "role": "style_reference", "instruction": "Transfer color palette, lighting, grain, atmosphere only. Do not copy composition."},
            {"type": "text", "source": "serialized_prompt_from_this_json", "role": "scene_description"}
        ]
    }
    if pro:
        hints = {"model_override": "pro", **hints}
    obj["api_call_hints"] = hints
    return obj

for q, data in FRAMES.items():
    p = OUT / f"Q{q:02d}.json"
    p.write_text(json.dumps(build_json(q, data), indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {p.name}")

print(f"Total gerados: {len(FRAMES)}")
